/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiResponseFromDiscriminatorValue, createAppProblemDetailsFromDiscriminatorValue, type ApiResponse, type AppProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/invitations/{invitationId}
 */
export interface WithInvitationItemRequestBuilder extends BaseRequestBuilder<WithInvitationItemRequestBuilder> {
    /**
     * Revoke a staff invitation (Admin only)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ApiResponse>}
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {AppProblemDetails} error when the service returns a 404 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ApiResponse | undefined>;
    /**
     * Revoke a staff invitation (Admin only)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithInvitationItemRequestBuilderUriTemplate = "{+baseurl}/staff/invitations/{invitationId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithInvitationItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithInvitationItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createApiResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
