/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createFindAuditLogsResponseFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, type AppProblemDetails, type FindAuditLogsResponse, type ValidationProblemDetails } from '../../models/index.js';
// @ts-ignore
import { ActionsRequestBuilderRequestsMetadata, type ActionsRequestBuilder } from './actions/index.js';
// @ts-ignore
import { ExportRequestBuilderRequestsMetadata, type ExportRequestBuilder } from './exportEscaped/index.js';
// @ts-ignore
import { type WithLogItemRequestBuilder, WithLogItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/audit-logs
 */
export interface AuditLogsRequestBuilder extends BaseRequestBuilder<AuditLogsRequestBuilder> {
    /**
     * The actions property
     */
    get actions(): ActionsRequestBuilder;
    /**
     * The export property
     */
    get exportEscaped(): ExportRequestBuilder;
    /**
     * Gets an item from the MainApi.Client.staff.auditLogs.item collection
     * @param logId Unique identifier of the item
     * @returns {WithLogItemRequestBuilder}
     */
     byLogId(logId: string) : WithLogItemRequestBuilder;
    /**
     * List audit logs with pagination and filters
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FindAuditLogsResponse>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FindAuditLogsResponse | undefined>;
    /**
     * List audit logs with pagination and filters
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AuditLogsRequestBuilderUriTemplate = "{+baseurl}/staff/audit-logs";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AuditLogsRequestBuilderNavigationMetadata: Record<Exclude<keyof AuditLogsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byLogId: {
        requestsMetadata: WithLogItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["logId"],
    },
    actions: {
        requestsMetadata: ActionsRequestBuilderRequestsMetadata,
    },
    exportEscaped: {
        requestsMetadata: ExportRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AuditLogsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AuditLogsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFindAuditLogsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
