/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createFindStaffProfileUsersResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, type AppProblemDetails, type FindStaffProfileUsersResult, type ValidationProblemDetails } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/profiles/{profileId}/users
 */
export interface UsersRequestBuilder extends BaseRequestBuilder<UsersRequestBuilder> {
    /**
     * Find users assigned to a staff profile
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FindStaffProfileUsersResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {AppProblemDetails} error when the service returns a 404 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<UsersRequestBuilderGetQueryParameters> | undefined) : Promise<FindStaffProfileUsersResult | undefined>;
    /**
     * Find users assigned to a staff profile
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<UsersRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Find users assigned to a staff profile
 */
export interface UsersRequestBuilderGetQueryParameters {
    limit?: string;
    page?: string;
    q?: string;
    sortId?: string;
    sortOrder?: string;
}
/**
 * Uri template for the request builder.
 */
export const UsersRequestBuilderUriTemplate = "{+baseurl}/staff/profiles/{profileId}/users{?limit*,page*,q*,sort_id*,sort_order*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const UsersRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "sortId": "sort_id",
    "sortOrder": "sort_order",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const UsersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: UsersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFindStaffProfileUsersResultFromDiscriminatorValue,
        queryParametersMapper: UsersRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
