/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createInvitationDetailsFromDiscriminatorValue, type AppProblemDetails, type InvitationDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /invitations/{token}/details
 */
export interface DetailsRequestBuilder extends BaseRequestBuilder<DetailsRequestBuilder> {
    /**
     * Get invitation details by token
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InvitationDetails>}
     * @throws {AppProblemDetails} error when the service returns a 404 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<InvitationDetails | undefined>;
    /**
     * Get invitation details by token
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DetailsRequestBuilderUriTemplate = "{+baseurl}/invitations/{token}/details";
/**
 * Metadata for all the requests in the request builder.
 */
export const DetailsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DetailsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            404: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createInvitationDetailsFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
