/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
	createAppProblemDetailsFromDiscriminatorValue,
	createValidationProblemDetailsFromDiscriminatorValue,
	type AppProblemDetails,
	type ValidationProblemDetails,
} from '../../../models/index.js';
// @ts-ignore
import {
	type BaseRequestBuilder,
	type Parsable,
	type ParsableFactory,
	type RequestConfiguration,
	type RequestInformation,
	type RequestsMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/audit-logs/export
 */
export interface ExportRequestBuilder
	extends BaseRequestBuilder<ExportRequestBuilder> {
	/**
	 * Export audit logs as CSV or JSON
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {Promise<ArrayBuffer>}
	 * @throws {AppProblemDetails} error when the service returns a 401 status code
	 * @throws {AppProblemDetails} error when the service returns a 403 status code
	 * @throws {ValidationProblemDetails} error when the service returns a 422 status code
	 * @throws {AppProblemDetails} error when the service returns a 500 status code
	 */
	get(
		requestConfiguration?:
			| RequestConfiguration<ExportRequestBuilderGetQueryParameters>
			| undefined,
	): Promise<ArrayBuffer | undefined>;
	/**
	 * Export audit logs as CSV or JSON
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {RequestInformation}
	 */
	toGetRequestInformation(
		requestConfiguration?:
			| RequestConfiguration<ExportRequestBuilderGetQueryParameters>
			| undefined,
	): RequestInformation;
}
/**
 * Export audit logs as CSV or JSON
 */
export interface ExportRequestBuilderGetQueryParameters {
	action?: string;
	endDate?: string;
	format?: string;
	startDate?: string;
	targetId?: string;
	userId?: string;
}
/**
 * Uri template for the request builder.
 */
export const ExportRequestBuilderUriTemplate =
	'{+baseurl}/staff/audit-logs/export{?Action*,EndDate*,Format*,StartDate*,TargetId*,UserId*}';
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ExportRequestBuilderGetQueryParametersMapper: Record<string, string> = {
	action: 'Action',
	endDate: 'EndDate',
	format: 'Format',
	startDate: 'StartDate',
	targetId: 'TargetId',
	userId: 'UserId',
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ExportRequestBuilderRequestsMetadata: RequestsMetadata = {
	get: {
		uriTemplate: ExportRequestBuilderUriTemplate,
		responseBodyContentType: 'application/problem+json',
		errorMappings: {
			401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
		},
		adapterMethodName: 'sendPrimitive',
		responseBodyFactory: 'ArrayBuffer',
		queryParametersMapper: ExportRequestBuilderGetQueryParametersMapper,
	},
};
/* tslint:enable */
/* eslint-enable */
