/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
	AcceptRequestBuilderRequestsMetadata,
	type AcceptRequestBuilder,
} from './accept/index.js';
// @ts-ignore
import {
	DetailsRequestBuilderRequestsMetadata,
	type DetailsRequestBuilder,
} from './details/index.js';
// @ts-ignore
import {
	type BaseRequestBuilder,
	type KeysToExcludeForNavigationMetadata,
	type NavigationMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /invitations/{token}
 */
export interface WithTokenItemRequestBuilder
	extends BaseRequestBuilder<WithTokenItemRequestBuilder> {
	/**
	 * The accept property
	 */
	get accept(): AcceptRequestBuilder;
	/**
	 * The details property
	 */
	get details(): DetailsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithTokenItemRequestBuilderUriTemplate =
	'{+baseurl}/invitations/{token}';
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithTokenItemRequestBuilderNavigationMetadata: Record<
	Exclude<
		keyof WithTokenItemRequestBuilder,
		KeysToExcludeForNavigationMetadata
	>,
	NavigationMetadata
> = {
	accept: {
		requestsMetadata: AcceptRequestBuilderRequestsMetadata,
	},
	details: {
		requestsMetadata: DetailsRequestBuilderRequestsMetadata,
	},
};
/* tslint:enable */
/* eslint-enable */
