/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createFindSocialAccountsForTenantResponseFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, type AppProblemDetails, type FindSocialAccountsForTenantResponse, type ValidationProblemDetails } from '../models/index.js';
// @ts-ignore
import { ConnectRequestBuilderRequestsMetadata, type ConnectRequestBuilder } from './connect/index.js';
// @ts-ignore
import { type WithSocialAccountItemRequestBuilder, WithSocialAccountItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /social-accounts
 */
export interface SocialAccountsRequestBuilder extends BaseRequestBuilder<SocialAccountsRequestBuilder> {
    /**
     * The connect property
     */
    get connect(): ConnectRequestBuilder;
    /**
     * Gets an item from the PublyApp.Api.Client.socialAccounts.item collection
     * @param socialAccountId Unique identifier of the item
     * @returns {WithSocialAccountItemRequestBuilder}
     */
     bySocialAccountId(socialAccountId: string) : WithSocialAccountItemRequestBuilder;
    /**
     * Find social accounts for the current tenant
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FindSocialAccountsForTenantResponse>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 429 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<SocialAccountsRequestBuilderGetQueryParameters> | undefined) : Promise<FindSocialAccountsForTenantResponse | undefined>;
    /**
     * Find social accounts for the current tenant
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SocialAccountsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Find social accounts for the current tenant
 */
export interface SocialAccountsRequestBuilderGetQueryParameters {
    cursor?: string;
    limit?: string;
    projectId?: string;
    sortId?: string;
    sortOrder?: string;
}
/**
 * Uri template for the request builder.
 */
export const SocialAccountsRequestBuilderUriTemplate = "{+baseurl}/social-accounts{?cursor*,limit*,project_id*,sort_id*,sort_order*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const SocialAccountsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "projectId": "project_id",
    "sortId": "sort_id",
    "sortOrder": "sort_order",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SocialAccountsRequestBuilderNavigationMetadata: Record<Exclude<keyof SocialAccountsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySocialAccountId: {
        navigationMetadata: WithSocialAccountItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["socialAccountId"],
    },
    connect: {
        requestsMetadata: ConnectRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SocialAccountsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SocialAccountsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFindSocialAccountsForTenantResponseFromDiscriminatorValue,
        queryParametersMapper: SocialAccountsRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
