/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createRequestPasswordResetResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, serializeRequestPasswordResetBody, serializeRequestPasswordResetResult, type AppProblemDetails, type RequestPasswordResetBody, type RequestPasswordResetResult, type ValidationProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth/request-password-reset
 */
export interface RequestPasswordResetRequestBuilder extends BaseRequestBuilder<RequestPasswordResetRequestBuilder> {
    /**
     * Request Password Reset
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RequestPasswordResetResult>}
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     post(body: RequestPasswordResetBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RequestPasswordResetResult | undefined>;
    /**
     * Request Password Reset
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RequestPasswordResetBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RequestPasswordResetRequestBuilderUriTemplate = "{+baseurl}/auth/request-password-reset";
/**
 * Metadata for all the requests in the request builder.
 */
export const RequestPasswordResetRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RequestPasswordResetRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRequestPasswordResetResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRequestPasswordResetBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
