/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createTenantUserCompanyBulkActionResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, serializeTenantUserCompanyBulkActionResult, serializeTenantUserCompanyIdsForStaffBody, type AppProblemDetails, type TenantUserCompanyBulkActionResult, type TenantUserCompanyIdsForStaffBody, type ValidationProblemDetails } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/tenant-users/{userId}/companies/bulk-suspend
 */
export interface BulkSuspendRequestBuilder extends BaseRequestBuilder<BulkSuspendRequestBuilder> {
    /**
     * Suspend a tenant user in selected companies
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TenantUserCompanyBulkActionResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {AppProblemDetails} error when the service returns a 404 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     post(body: TenantUserCompanyIdsForStaffBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TenantUserCompanyBulkActionResult | undefined>;
    /**
     * Suspend a tenant user in selected companies
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: TenantUserCompanyIdsForStaffBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BulkSuspendRequestBuilderUriTemplate = "{+baseurl}/staff/tenant-users/{userId}/companies/bulk-suspend";
/**
 * Metadata for all the requests in the request builder.
 */
export const BulkSuspendRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: BulkSuspendRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTenantUserCompanyBulkActionResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeTenantUserCompanyIdsForStaffBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
