/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createSystemJobDefinitionDetailFromDiscriminatorValue, type AppProblemDetails, type SystemJobDefinitionDetail } from '../../../../models/index.js';
// @ts-ignore
import { CronRequestBuilderRequestsMetadata, type CronRequestBuilder } from './cron/index.js';
// @ts-ignore
import { EnabledRequestBuilderRequestsMetadata, type EnabledRequestBuilder } from './enabled/index.js';
// @ts-ignore
import { TriggerRequestBuilderRequestsMetadata, type TriggerRequestBuilder } from './trigger/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/jobs/system-jobs/{systemJobId}
 */
export interface WithSystemJobItemRequestBuilder extends BaseRequestBuilder<WithSystemJobItemRequestBuilder> {
    /**
     * The cron property
     */
    get cron(): CronRequestBuilder;
    /**
     * The enabled property
     */
    get enabled(): EnabledRequestBuilder;
    /**
     * The trigger property
     */
    get trigger(): TriggerRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SystemJobDefinitionDetail>}
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {AppProblemDetails} error when the service returns a 404 status code
     * @throws {AppProblemDetails} error when the service returns a 429 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SystemJobDefinitionDetail | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithSystemJobItemRequestBuilderUriTemplate = "{+baseurl}/staff/jobs/system-jobs/{systemJobId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithSystemJobItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithSystemJobItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    cron: {
        requestsMetadata: CronRequestBuilderRequestsMetadata,
    },
    enabled: {
        requestsMetadata: EnabledRequestBuilderRequestsMetadata,
    },
    trigger: {
        requestsMetadata: TriggerRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithSystemJobItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithSystemJobItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSystemJobDefinitionDetailFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
