/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
	createAppProblemDetailsFromDiscriminatorValue,
	createGetStaffInvitationLinkResultFromDiscriminatorValue,
	type AppProblemDetails,
	type GetStaffInvitationLinkResult,
} from '../../../../models/index.js';
// @ts-ignore
import {
	type BaseRequestBuilder,
	type Parsable,
	type ParsableFactory,
	type RequestConfiguration,
	type RequestInformation,
	type RequestsMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/invitations/{invitationId}/link
 */
export interface LinkRequestBuilder
	extends BaseRequestBuilder<LinkRequestBuilder> {
	/**
	 * Get staff invitation link
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {Promise<GetStaffInvitationLinkResult>}
	 * @throws {AppProblemDetails} error when the service returns a 400 status code
	 * @throws {AppProblemDetails} error when the service returns a 401 status code
	 * @throws {AppProblemDetails} error when the service returns a 403 status code
	 * @throws {AppProblemDetails} error when the service returns a 404 status code
	 * @throws {AppProblemDetails} error when the service returns a 500 status code
	 */
	get(
		requestConfiguration?: RequestConfiguration<object> | undefined,
	): Promise<GetStaffInvitationLinkResult | undefined>;
	/**
	 * Get staff invitation link
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {RequestInformation}
	 */
	toGetRequestInformation(
		requestConfiguration?: RequestConfiguration<object> | undefined,
	): RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LinkRequestBuilderUriTemplate =
	'{+baseurl}/staff/invitations/{invitationId}/link';
/**
 * Metadata for all the requests in the request builder.
 */
export const LinkRequestBuilderRequestsMetadata: RequestsMetadata = {
	get: {
		uriTemplate: LinkRequestBuilderUriTemplate,
		responseBodyContentType: 'application/json',
		errorMappings: {
			400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			404: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
		},
		adapterMethodName: 'send',
		responseBodyFactory:
			createGetStaffInvitationLinkResultFromDiscriminatorValue,
	},
};
/* tslint:enable */
/* eslint-enable */
