/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createFindJobQueueItemsResponseFromDiscriminatorValue, type AppProblemDetails, type FindJobQueueItemsResponse } from '../../../models/index.js';
// @ts-ignore
import { type WithQueueItemItemRequestBuilder, WithQueueItemItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/jobs/queue
 */
export interface QueueRequestBuilder extends BaseRequestBuilder<QueueRequestBuilder> {
    /**
     * Gets an item from the PublyApp.Api.Client.staff.jobs.queue.item collection
     * @param queueItemId Unique identifier of the item
     * @returns {WithQueueItemItemRequestBuilder}
     */
     byQueueItemId(queueItemId: string) : WithQueueItemItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FindJobQueueItemsResponse>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {AppProblemDetails} error when the service returns a 429 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<QueueRequestBuilderGetQueryParameters> | undefined) : Promise<FindJobQueueItemsResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<QueueRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface QueueRequestBuilderGetQueryParameters {
    cursor?: string;
    jobType?: string;
    limit?: string;
    sortId?: string;
    sortOrder?: string;
    status?: string;
    tenantId?: string;
}
/**
 * Uri template for the request builder.
 */
export const QueueRequestBuilderUriTemplate = "{+baseurl}/staff/jobs/queue{?cursor*,job_type*,limit*,sort_id*,sort_order*,status*,tenant_id*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const QueueRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "jobType": "job_type",
    "sortId": "sort_id",
    "sortOrder": "sort_order",
    "tenantId": "tenant_id",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const QueueRequestBuilderNavigationMetadata: Record<Exclude<keyof QueueRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byQueueItemId: {
        requestsMetadata: WithQueueItemItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["queueItemId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const QueueRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: QueueRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFindJobQueueItemsResponseFromDiscriminatorValue,
        queryParametersMapper: QueueRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
