/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createCheckEmailVerificationTokenResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, type AppProblemDetails, type CheckEmailVerificationTokenResult, type ValidationProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth/check-email-verification-token
 */
export interface CheckEmailVerificationTokenRequestBuilder extends BaseRequestBuilder<CheckEmailVerificationTokenRequestBuilder> {
    /**
     * Check Email Verification Token
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CheckEmailVerificationTokenResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<CheckEmailVerificationTokenRequestBuilderGetQueryParameters> | undefined) : Promise<CheckEmailVerificationTokenResult | undefined>;
    /**
     * Check Email Verification Token
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CheckEmailVerificationTokenRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Check Email Verification Token
 */
export interface CheckEmailVerificationTokenRequestBuilderGetQueryParameters {
    id?: string;
    token?: string;
}
/**
 * Uri template for the request builder.
 */
export const CheckEmailVerificationTokenRequestBuilderUriTemplate = "{+baseurl}/auth/check-email-verification-token?Id={Id}&Token={Token}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const CheckEmailVerificationTokenRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "id": "Id",
    "token": "Token",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CheckEmailVerificationTokenRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CheckEmailVerificationTokenRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCheckEmailVerificationTokenResultFromDiscriminatorValue,
        queryParametersMapper: CheckEmailVerificationTokenRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
