# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1.2.17 AS base

# Set working directory
WORKDIR /usr/src/app

# Copy application files
COPY . /app

# Set working directory to /app
WORKDIR /app

# Install dependencies
RUN bun install

# Expose the port your app runs on (change 3000 to your app's port)
EXPOSE 3000

# Command to run your application
CMD ["bun", "run", "start"]
