# This file is used to start the PostgreSQL service locally
# It is used to test/develop the services locally
# It is not used to deploy the services to the cloud
# It is not used to deploy the services to the cloud

name: publyapp-services
services:
  publyapp-postgres:
    image: postgres:18-alpine
    container_name: publyapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: publyapp_db
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5454:5432
    networks:
      - publyapp-network

volumes:
  postgres-volume:
    name: postgres-volume

networks:
  publyapp-network:
    external: false
