/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createCreateStaffUserResultFromDiscriminatorValue, createFindStaffUsersResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, serializeCreateStaffUserBody, serializeCreateStaffUserResult, type AppProblemDetails, type CreateStaffUserBody, type CreateStaffUserResult, type FindStaffUsersResult, type ValidationProblemDetails } from '../../models/index.js';
// @ts-ignore
import { WithUserItemRequestBuilderRequestsMetadata, type WithUserItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/staff-users
 */
export interface StaffUsersRequestBuilder extends BaseRequestBuilder<StaffUsersRequestBuilder> {
    /**
     * Gets an item from the MainApi.Client.staff.staffUsers.item collection
     * @param userId Unique identifier of the item
     * @returns {WithUserItemRequestBuilder}
     */
    byUserId(userId: string): WithUserItemRequestBuilder;
    /**
     * Find staff members
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FindStaffUsersResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
    get(requestConfiguration?: RequestConfiguration<StaffUsersRequestBuilderGetQueryParameters> | undefined): Promise<FindStaffUsersResult | undefined>;
    /**
     * Create a new staff member
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreateStaffUserResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
    post(body: CreateStaffUserBody, requestConfiguration?: RequestConfiguration<object> | undefined): Promise<CreateStaffUserResult | undefined>;
    /**
     * Find staff members
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
    toGetRequestInformation(requestConfiguration?: RequestConfiguration<StaffUsersRequestBuilderGetQueryParameters> | undefined): RequestInformation;
    /**
     * Create a new staff member
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
    toPostRequestInformation(body: CreateStaffUserBody, requestConfiguration?: RequestConfiguration<object> | undefined): RequestInformation;
}
/**
 * Find staff members
 */
export interface StaffUsersRequestBuilderGetQueryParameters {
    limit?: string;
    page?: string;
    sortId?: string;
    sortOrder?: string;
}
/**
 * Uri template for the request builder.
 */
export const StaffUsersRequestBuilderUriTemplate = "{+baseurl}/staff/staff-users{?Limit*,Page*,SortId*,SortOrder*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const StaffUsersRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "limit": "Limit",
    "page": "Page",
    "sortId": "SortId",
    "sortOrder": "SortOrder",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const StaffUsersRequestBuilderNavigationMetadata: Record<Exclude<keyof StaffUsersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byUserId: {
        requestsMetadata: WithUserItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["userId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const StaffUsersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StaffUsersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory: createFindStaffUsersResultFromDiscriminatorValue,
        queryParametersMapper: StaffUsersRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: StaffUsersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory: createCreateStaffUserResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateStaffUserBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
