/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiResponseFromDiscriminatorValue, createCreateStaffMemberResultFromDiscriminatorValue, createStaffMemberItemFromDiscriminatorValue, serializeCreateStaffMemberBody, serializeCreateStaffMemberResult, type ApiResponse, type CreateStaffMemberBody, type CreateStaffMemberResult, type StaffMemberItem } from '../../models/index.js';
// @ts-ignore
import { type WithUserItemRequestBuilder, WithUserItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/staff-members
 */
export interface StaffMembersRequestBuilder extends BaseRequestBuilder<StaffMembersRequestBuilder> {
    /**
     * Gets an item from the MainApi.Client.staff.staffMembers.item collection
     * @param userId Unique identifier of the item
     * @returns {WithUserItemRequestBuilder}
     */
     byUserId(userId: string) : WithUserItemRequestBuilder;
    /**
     * Find staff members
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<StaffMemberItem[]>}
     * @throws {ApiResponse} error when the service returns a 400 status code
     * @throws {ApiResponse} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<StaffMemberItem[] | undefined>;
    /**
     * Create a new staff member
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreateStaffMemberResult>}
     * @throws {ApiResponse} error when the service returns a 400 status code
     * @throws {ApiResponse} error when the service returns a 500 status code
     */
     post(body: CreateStaffMemberBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreateStaffMemberResult | undefined>;
    /**
     * Find staff members
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Create a new staff member
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateStaffMemberBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const StaffMembersRequestBuilderUriTemplate = "{+baseurl}/staff/staff-members";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const StaffMembersRequestBuilderNavigationMetadata: Record<Exclude<keyof StaffMembersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byUserId: {
        requestsMetadata: WithUserItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["userId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const StaffMembersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StaffMembersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createStaffMemberItemFromDiscriminatorValue,
    },
    post: {
        uriTemplate: StaffMembersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreateStaffMemberResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateStaffMemberBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
