/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, type AppProblemDetails, type ValidationProblemDetails } from '../../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StaffGetResponse}
 */
// @ts-ignore
export function createStaffGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStaffGetResponse;
}
/**
 * The deserialization information for the current model
 * @param StaffGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStaffGetResponse(staffGetResponse: Partial<StaffGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param StaffGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStaffGetResponse(writer: SerializationWriter, staffGetResponse: Partial<StaffGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!staffGetResponse || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(staffGetResponse.additionalData);
}
export interface StaffGetResponse extends AdditionalDataHolder, Parsable {
}
/**
 * Builds and executes requests for operations under /staff/permissions/scopes/staff
 */
export interface StaffRequestBuilder extends BaseRequestBuilder<StaffRequestBuilder> {
    /**
     * Find staff permissions
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<StaffGetResponse>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<StaffRequestBuilderGetQueryParameters> | undefined) : Promise<StaffGetResponse | undefined>;
    /**
     * Find staff permissions
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<StaffRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Find staff permissions
 */
export interface StaffRequestBuilderGetQueryParameters {
    language?: string;
}
/**
 * Uri template for the request builder.
 */
export const StaffRequestBuilderUriTemplate = "{+baseurl}/staff/permissions/scopes/staff{?language*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const StaffRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StaffRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createStaffGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
