/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiResponseFromDiscriminatorValue, createGetVerificationLinkSuccessResultFromDiscriminatorValue, type ApiResponse, type GetVerificationLinkSuccessResult } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth/verification-link
 */
export interface VerificationLinkRequestBuilder extends BaseRequestBuilder<VerificationLinkRequestBuilder> {
    /**
     * Get Verification Link
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetVerificationLinkSuccessResult>}
     * @throws {ApiResponse} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<VerificationLinkRequestBuilderGetQueryParameters> | undefined) : Promise<GetVerificationLinkSuccessResult | undefined>;
    /**
     * Get Verification Link
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<VerificationLinkRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get Verification Link
 */
export interface VerificationLinkRequestBuilderGetQueryParameters {
    userId?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const VerificationLinkRequestBuilderUriTemplate = "{+baseurl}/auth/verification-link?UserId={UserId}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const VerificationLinkRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "userId": "UserId",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const VerificationLinkRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: VerificationLinkRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetVerificationLinkSuccessResultFromDiscriminatorValue,
        queryParametersMapper: VerificationLinkRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
