/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createTenantUserDetailsForStaffResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, serializeTenantUserDetailsForStaffResult, serializeUpdateTenantUserEmailForStaffBody, type AppProblemDetails, type TenantUserDetailsForStaffResult, type UpdateTenantUserEmailForStaffBody, type ValidationProblemDetails } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/tenant-users/{userId}/email
 */
export interface EmailRequestBuilder extends BaseRequestBuilder<EmailRequestBuilder> {
    /**
     * Update a tenant user's shared identity email
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TenantUserDetailsForStaffResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {AppProblemDetails} error when the service returns a 404 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 429 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     patch(body: UpdateTenantUserEmailForStaffBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TenantUserDetailsForStaffResult | undefined>;
    /**
     * Update a tenant user's shared identity email
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: UpdateTenantUserEmailForStaffBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const EmailRequestBuilderUriTemplate = "{+baseurl}/staff/tenant-users/{userId}/email";
/**
 * Metadata for all the requests in the request builder.
 */
export const EmailRequestBuilderRequestsMetadata: RequestsMetadata = {
    patch: {
        uriTemplate: EmailRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTenantUserDetailsForStaffResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateTenantUserEmailForStaffBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
