/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createCreateTenantAsStaffResultFromDiscriminatorValue, createFindTenantsAsStaffResponseFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, serializeCreateTenantAsStaffBody, serializeCreateTenantAsStaffResult, type AppProblemDetails, type CreateTenantAsStaffBody, type CreateTenantAsStaffResult, type FindTenantsAsStaffResponse, type ValidationProblemDetails } from '../../models/index.js';
// @ts-ignore
import { BulkDeleteRequestBuilderRequestsMetadata, type BulkDeleteRequestBuilder } from './bulkDelete/index.js';
// @ts-ignore
import { BulkReactivateRequestBuilderRequestsMetadata, type BulkReactivateRequestBuilder } from './bulkReactivate/index.js';
// @ts-ignore
import { BulkSuspendRequestBuilderRequestsMetadata, type BulkSuspendRequestBuilder } from './bulkSuspend/index.js';
// @ts-ignore
import { type WithTenantItemRequestBuilder, WithTenantItemRequestBuilderNavigationMetadata, WithTenantItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { BulkReactivateRequestBuilderRequestsMetadata, type BulkReactivateRequestBuilder } from './bulkReactivate/index.js';
// @ts-ignore
import { BulkSuspendRequestBuilderRequestsMetadata, type BulkSuspendRequestBuilder } from './bulkSuspend/index.js';
// @ts-ignore
import { type WithTenantItemRequestBuilder, WithTenantItemRequestBuilderNavigationMetadata, WithTenantItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/tenants
 */
export interface StaffUsersRequestBuilder extends BaseRequestBuilder<StaffUsersRequestBuilder> {
    /**
     * The bulkDelete property
     */
    get bulkDelete(): BulkDeleteRequestBuilder;
    /**
     * The bulkReactivate property
     */
    get bulkReactivate(): BulkReactivateRequestBuilder;
    /**
     * The bulkSuspend property
     */
    get bulkSuspend(): BulkSuspendRequestBuilder;
    /**
     * Gets an item from the MainApi.Client.staff.tenants.item collection
     * @param tenantId Unique identifier of the item
     * @returns {WithTenantItemRequestBuilder}
     */
    byUserId(userId: string): WithUserItemRequestBuilder;
    /**
     * Find staff members
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FindStaffUsersResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
    get(requestConfiguration?: RequestConfiguration<StaffUsersRequestBuilderGetQueryParameters> | undefined): Promise<FindStaffUsersResult | undefined>;
    /**
     * Create a new staff member
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreateStaffUserResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
    post(body: CreateStaffUserBody, requestConfiguration?: RequestConfiguration<object> | undefined): Promise<CreateStaffUserResult | undefined>;
    /**
     * Find staff members
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
    toGetRequestInformation(requestConfiguration?: RequestConfiguration<StaffUsersRequestBuilderGetQueryParameters> | undefined): RequestInformation;
    /**
     * Create a new staff member
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
    toPostRequestInformation(body: CreateStaffUserBody, requestConfiguration?: RequestConfiguration<object> | undefined): RequestInformation;
}
/**
 * Find tenants with pagination
 */
export interface TenantsRequestBuilderGetQueryParameters {
    cursor?: string;
    limit?: string;
    q?: string;
    sortId?: string;
    sortOrder?: string;
    status?: string;
}
/**
 * Uri template for the request builder.
 */
export const TenantsRequestBuilderUriTemplate = "{+baseurl}/staff/tenants{?Status*,cursor*,limit*,q*,sort_id*,sort_order*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const TenantsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "sortId": "sort_id",
    "sortOrder": "sort_order",
    "status": "Status",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const StaffUsersRequestBuilderNavigationMetadata: Record<Exclude<keyof StaffUsersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byUserId: {
        requestsMetadata: WithUserItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["userId"],
    },
    bulkDelete: {
        requestsMetadata: BulkDeleteRequestBuilderRequestsMetadata,
    },
    bulkReactivate: {
        requestsMetadata: BulkReactivateRequestBuilderRequestsMetadata,
    },
    bulkSuspend: {
        requestsMetadata: BulkSuspendRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TenantsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TenantsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFindTenantsAsStaffResponseFromDiscriminatorValue,
        queryParametersMapper: TenantsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: TenantsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreateTenantAsStaffResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateTenantAsStaffBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
