/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
	createAppProblemDetailsFromDiscriminatorValue,
	createCreateTenantAsStaffResultFromDiscriminatorValue,
	createFindTenantsAsStaffResponseFromDiscriminatorValue,
	createValidationProblemDetailsFromDiscriminatorValue,
	serializeCreateTenantAsStaffBody,
	serializeCreateTenantAsStaffResult,
	type AppProblemDetails,
	type CreateTenantAsStaffBody,
	type CreateTenantAsStaffResult,
	type FindTenantsAsStaffResponse,
	type ValidationProblemDetails,
} from '../../models/index.js';
// @ts-ignore
import {
	type WithTenantItemRequestBuilder,
	WithTenantItemRequestBuilderNavigationMetadata,
	WithTenantItemRequestBuilderRequestsMetadata,
} from './item/index.js';
// @ts-ignore
import {
	type BaseRequestBuilder,
	type KeysToExcludeForNavigationMetadata,
	type NavigationMetadata,
	type Parsable,
	type ParsableFactory,
	type RequestConfiguration,
	type RequestInformation,
	type RequestsMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/tenants
 */
export interface TenantsRequestBuilder
	extends BaseRequestBuilder<TenantsRequestBuilder> {
	/**
	 * Gets an item from the MainApi.Client.staff.tenants.item collection
	 * @param tenantId Unique identifier of the item
	 * @returns {WithTenantItemRequestBuilder}
	 */
	byTenantId(tenantId: string): WithTenantItemRequestBuilder;
	/**
	 * Find tenants with pagination
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {Promise<FindTenantsAsStaffResponse>}
	 * @throws {AppProblemDetails} error when the service returns a 400 status code
	 * @throws {AppProblemDetails} error when the service returns a 401 status code
	 * @throws {AppProblemDetails} error when the service returns a 403 status code
	 * @throws {ValidationProblemDetails} error when the service returns a 422 status code
	 * @throws {AppProblemDetails} error when the service returns a 500 status code
	 */
	get(
		requestConfiguration?:
			| RequestConfiguration<TenantsRequestBuilderGetQueryParameters>
			| undefined,
	): Promise<FindTenantsAsStaffResponse | undefined>;
	/**
	 * Create a new tenant
	 * @param body The request body
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {Promise<CreateTenantAsStaffResult>}
	 * @throws {AppProblemDetails} error when the service returns a 400 status code
	 * @throws {AppProblemDetails} error when the service returns a 401 status code
	 * @throws {AppProblemDetails} error when the service returns a 403 status code
	 * @throws {ValidationProblemDetails} error when the service returns a 422 status code
	 * @throws {AppProblemDetails} error when the service returns a 500 status code
	 */
	post(
		body: CreateTenantAsStaffBody,
		requestConfiguration?: RequestConfiguration<object> | undefined,
	): Promise<CreateTenantAsStaffResult | undefined>;
	/**
	 * Find tenants with pagination
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {RequestInformation}
	 */
	toGetRequestInformation(
		requestConfiguration?:
			| RequestConfiguration<TenantsRequestBuilderGetQueryParameters>
			| undefined,
	): RequestInformation;
	/**
	 * Create a new tenant
	 * @param body The request body
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {RequestInformation}
	 */
	toPostRequestInformation(
		body: CreateTenantAsStaffBody,
		requestConfiguration?: RequestConfiguration<object> | undefined,
	): RequestInformation;
}
/**
 * Find tenants with pagination
 */
export interface TenantsRequestBuilderGetQueryParameters {
	cursor?: string;
	limit?: string;
	q?: string;
	sortId?: string;
	sortOrder?: string;
	status?: string;
}
/**
 * Uri template for the request builder.
 */
export const TenantsRequestBuilderUriTemplate =
	'{+baseurl}/staff/tenants{?Cursor*,Limit*,SortId*,SortOrder*,Status*,q*}';
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const TenantsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
	cursor: 'Cursor',
	limit: 'Limit',
	sortId: 'SortId',
	sortOrder: 'SortOrder',
	status: 'Status',
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TenantsRequestBuilderNavigationMetadata: Record<
	Exclude<keyof TenantsRequestBuilder, KeysToExcludeForNavigationMetadata>,
	NavigationMetadata
> = {
	byTenantId: {
		requestsMetadata: WithTenantItemRequestBuilderRequestsMetadata,
		navigationMetadata: WithTenantItemRequestBuilderNavigationMetadata,
		pathParametersMappings: ['tenantId'],
	},
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TenantsRequestBuilderRequestsMetadata: RequestsMetadata = {
	get: {
		uriTemplate: TenantsRequestBuilderUriTemplate,
		responseBodyContentType: 'application/json',
		errorMappings: {
			400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
		},
		adapterMethodName: 'send',
		responseBodyFactory: createFindTenantsAsStaffResponseFromDiscriminatorValue,
		queryParametersMapper: TenantsRequestBuilderGetQueryParametersMapper,
	},
	post: {
		uriTemplate: TenantsRequestBuilderUriTemplate,
		responseBodyContentType: 'application/json',
		errorMappings: {
			400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
		},
		adapterMethodName: 'send',
		responseBodyFactory: createCreateTenantAsStaffResultFromDiscriminatorValue,
		requestBodyContentType: 'application/json',
		requestBodySerializer: serializeCreateTenantAsStaffBody,
		requestInformationContentSetMethod: 'setContentFromParsable',
	},
};
/* tslint:enable */
/* eslint-enable */
