/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createFindTenantProfileUsersAsStaffResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, type AppProblemDetails, type FindTenantProfileUsersAsStaffResult, type ValidationProblemDetails } from '../../../../../../models/index.js';
// @ts-ignore
import { AssignmentResolutionRequestBuilderRequestsMetadata, type AssignmentResolutionRequestBuilder } from './assignmentResolution/index.js';
// @ts-ignore
import { type WithUser_account_ItemRequestBuilder, WithUser_account_ItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/tenants/{tenantId}/profiles/{profileId}/users
 */
export interface UsersRequestBuilder extends BaseRequestBuilder<UsersRequestBuilder> {
    /**
     * The assignmentResolution property
     */
    get assignmentResolution(): AssignmentResolutionRequestBuilder;
    /**
     * Gets an item from the PublyApp.Api.Client.staff.tenants.item.profiles.item.users.item collection
     * @param user_account_id Unique identifier of the item
     * @returns {WithUser_account_ItemRequestBuilder}
     */
     byUser_account_id(user_account_id: string) : WithUser_account_ItemRequestBuilder;
    /**
     * Find tenant members assigned to a tenant profile
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FindTenantProfileUsersAsStaffResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {AppProblemDetails} error when the service returns a 404 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 429 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<UsersRequestBuilderGetQueryParameters> | undefined) : Promise<FindTenantProfileUsersAsStaffResult | undefined>;
    /**
     * Find tenant members assigned to a tenant profile
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<UsersRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Find tenant members assigned to a tenant profile
 */
export interface UsersRequestBuilderGetQueryParameters {
    limit?: string;
    page?: string;
    q?: string;
    sortId?: string;
    sortOrder?: string;
}
/**
 * Uri template for the request builder.
 */
export const UsersRequestBuilderUriTemplate = "{+baseurl}/staff/tenants/{tenantId}/profiles/{profileId}/users{?limit*,page*,q*,sort_id*,sort_order*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const UsersRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "sortId": "sort_id",
    "sortOrder": "sort_order",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UsersRequestBuilderNavigationMetadata: Record<Exclude<keyof UsersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byUser_account_id: {
        requestsMetadata: WithUser_account_ItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["user_account_id"],
    },
    assignmentResolution: {
        requestsMetadata: AssignmentResolutionRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const UsersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: UsersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFindTenantProfileUsersAsStaffResultFromDiscriminatorValue,
        queryParametersMapper: UsersRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
