/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithUserAccountItemRequestBuilder, WithUserAccountItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/tenants/{tenantId}/profiles/{profileId}/users
 */
export interface UsersRequestBuilder extends BaseRequestBuilder<UsersRequestBuilder> {
    /**
     * Gets an item from the PublyApp.Api.Client.staff.tenants.item.profiles.item.users.item collection
     * @param userAccountId Unique identifier of the item
     * @returns {WithUserAccountItemRequestBuilder}
     */
     byUserAccountId(userAccountId: string) : WithUserAccountItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const UsersRequestBuilderUriTemplate = "{+baseurl}/staff/tenants/{tenantId}/profiles/{profileId}/users";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UsersRequestBuilderNavigationMetadata: Record<Exclude<keyof UsersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byUserAccountId: {
        requestsMetadata: WithUserAccountItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["userAccountId"],
    },
};
/* tslint:enable */
/* eslint-enable */
