/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithUser_account_ItemRequestBuilder, WithUser_account_ItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/tenants/{tenantId}/profiles/{profileId}/users
 */
export interface UsersRequestBuilder extends BaseRequestBuilder<UsersRequestBuilder> {
    /**
     * Gets an item from the PublyApp.Api.Client.staff.tenants.item.profiles.item.users.item collection
     * @param user_account_id Unique identifier of the item
     * @returns {WithUser_account_ItemRequestBuilder}
     */
     byUser_account_id(user_account_id: string) : WithUser_account_ItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const UsersRequestBuilderUriTemplate = "{+baseurl}/staff/tenants/{tenantId}/profiles/{profileId}/users";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UsersRequestBuilderNavigationMetadata: Record<Exclude<keyof UsersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byUser_account_id: {
        requestsMetadata: WithUser_account_ItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["user_account_id"],
    },
};
/* tslint:enable */
/* eslint-enable */
