/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createFindInvitationsForTenantAsStaffResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, type AppProblemDetails, type FindInvitationsForTenantAsStaffResult, type ValidationProblemDetails } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/tenants/{tenantId}/invitations
 */
export interface InvitationsRequestBuilder extends BaseRequestBuilder<InvitationsRequestBuilder> {
    /**
     * Find invitations for a tenant
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FindInvitationsForTenantAsStaffResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<InvitationsRequestBuilderGetQueryParameters> | undefined) : Promise<FindInvitationsForTenantAsStaffResult | undefined>;
    /**
     * Find invitations for a tenant
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<InvitationsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Find invitations for a tenant
 */
export interface InvitationsRequestBuilderGetQueryParameters {
    cursor?: string;
    limit?: string;
    q?: string;
    sortId?: string;
    sortOrder?: string;
    status?: string;
}
/**
 * Uri template for the request builder.
 */
export const InvitationsRequestBuilderUriTemplate = "{+baseurl}/staff/tenants/{tenantId}/invitations{?cursor*,limit*,q*,sort_id*,sort_order*,status*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const InvitationsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "sortId": "sort_id",
    "sortOrder": "sort_order",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const InvitationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: InvitationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFindInvitationsForTenantAsStaffResultFromDiscriminatorValue,
        queryParametersMapper: InvitationsRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
