/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createBulkTenantUserActionResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, serializeBulkRemoveTenantUsersBody, serializeBulkTenantUserActionResult, type AppProblemDetails, type BulkRemoveTenantUsersBody, type BulkTenantUserActionResult, type ValidationProblemDetails } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/tenants/{tenantId}/users/bulk-remove
 */
export interface BulkRemoveRequestBuilder extends BaseRequestBuilder<BulkRemoveRequestBuilder> {
    /**
     * Remove multiple users from a tenant
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BulkTenantUserActionResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     post(body: BulkRemoveTenantUsersBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BulkTenantUserActionResult | undefined>;
    /**
     * Remove multiple users from a tenant
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: BulkRemoveTenantUsersBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BulkRemoveRequestBuilderUriTemplate = "{+baseurl}/staff/tenants/{tenantId}/users/bulk-remove";
/**
 * Metadata for all the requests in the request builder.
 */
export const BulkRemoveRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: BulkRemoveRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createBulkTenantUserActionResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeBulkRemoveTenantUsersBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
