import { nanoid } from 'nanoid';
import type { StaffMemberRowData } from './staff-members-table';

export const mockDataStaffMembers: StaffMemberRowData[] = [
	{
		id: nanoid(),
		avatarUrl: '/assets/images/mock/avatar/avatar-1.webp',
		firstName: 'Alex',
		lastName: 'Hunter',
		role: 'Admin',
		status: 'active',
		email: 'alex.hunter@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/assets/images/mock/avatar/avatar-2.webp',
		firstName: 'Sarah',
		lastName: 'Connor',
		role: 'Manager',
		status: 'active',
		email: 'sarah.connor@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/assets/images/mock/avatar/avatar-3.webp',
		firstName: 'James',
		lastName: 'Wilson',
		role: 'Staff',
		status: 'inactive',
		email: 'james.wilson@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/assets/images/mock/avatar/avatar-4.webp',
		firstName: 'Emma',
		lastName: 'Davis',
		role: 'Admin',
		status: 'active',
		email: 'emma.davis@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/assets/images/mock/avatar/avatar-5.webp',
		firstName: 'Michael',
		lastName: 'Brown',
		role: 'Staff',
		status: 'active',
		email: 'michael.brown@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/assets/images/mock/avatar/avatar-6.webp',
		firstName: 'Sarah',
		lastName: 'Connor',
		role: 'Manager',
		status: 'active',
		email: 'sarah.connor@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/assets/images/mock/avatar/avatar-7.webp',
		firstName: 'James',
		lastName: 'Wilson',
		role: 'Staff',
		status: 'inactive',
		email: 'james.wilson@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/assets/images/mock/avatar/avatar-8.webp',
		firstName: 'Emma',
		lastName: 'Davis',
		role: 'Admin',
		status: 'active',
		email: 'emma.davis@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/assets/images/mock/avatar/avatar-9.webp',
		firstName: 'Michael',
		lastName: 'Brown',
		role: 'Staff',
		status: 'active',
		email: 'michael.brown@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/assets/images/mock/avatar/avatar-10.webp',
		firstName: 'Sarah',
		lastName: 'Connor',
		role: 'Manager',
		status: 'active',
		email: 'sarah.connor@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/assets/images/mock/avatar/avatar-11.webp',
		firstName: 'James',
		lastName: 'Wilson',
		role: 'Staff',
		status: 'inactive',
		email: 'james.wilson@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/assets/images/mock/avatar/avatar-12.webp',
		firstName: 'Emma',
		lastName: 'Davis',
		role: 'Admin',
		status: 'active',
		email: 'emma.davis@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/assets/images/mock/avatar/avatar-13.webp',
		firstName: 'Michael',
		lastName: 'Brown',
		role: 'Staff',
		status: 'active',
		email: 'michael.brown@example.com',
	},
];
