import { nanoid } from 'nanoid';
import type { StaffMemberRowData } from './staff-members-table';

export const mockDataStaffMembers: StaffMemberRowData[] = [
	{
		id: nanoid(),
		avatarUrl: '/static/images/avatars/avatar_1.jpg',
		firstName: 'Alex',
		lastName: 'Hunter',
		role: 'Admin',
		status: 'active',
		email: 'alex.hunter@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/static/images/avatars/avatar_2.jpg',
		firstName: 'Sarah',
		lastName: 'Connor',
		role: 'Manager',
		status: 'active',
		email: 'sarah.connor@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/static/images/avatars/avatar_3.jpg',
		firstName: 'James',
		lastName: 'Wilson',
		role: 'Staff',
		status: 'inactive',
		email: 'james.wilson@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/static/images/avatars/avatar_4.jpg',
		firstName: 'Emma',
		lastName: 'Davis',
		role: 'Admin',
		status: 'active',
		email: 'emma.davis@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/static/images/avatars/avatar_5.jpg',
		firstName: 'Michael',
		lastName: 'Brown',
		role: 'Staff',
		status: 'active',
		email: 'michael.brown@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/static/images/avatars/avatar_2.jpg',
		firstName: 'Sarah',
		lastName: 'Connor',
		role: 'Manager',
		status: 'active',
		email: 'sarah.connor@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/static/images/avatars/avatar_3.jpg',
		firstName: 'James',
		lastName: 'Wilson',
		role: 'Staff',
		status: 'inactive',
		email: 'james.wilson@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/static/images/avatars/avatar_4.jpg',
		firstName: 'Emma',
		lastName: 'Davis',
		role: 'Admin',
		status: 'active',
		email: 'emma.davis@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/static/images/avatars/avatar_5.jpg',
		firstName: 'Michael',
		lastName: 'Brown',
		role: 'Staff',
		status: 'active',
		email: 'michael.brown@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/static/images/avatars/avatar_2.jpg',
		firstName: 'Sarah',
		lastName: 'Connor',
		role: 'Manager',
		status: 'active',
		email: 'sarah.connor@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/static/images/avatars/avatar_3.jpg',
		firstName: 'James',
		lastName: 'Wilson',
		role: 'Staff',
		status: 'inactive',
		email: 'james.wilson@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/static/images/avatars/avatar_4.jpg',
		firstName: 'Emma',
		lastName: 'Davis',
		role: 'Admin',
		status: 'active',
		email: 'emma.davis@example.com',
	},
	{
		id: nanoid(),
		avatarUrl: '/static/images/avatars/avatar_5.jpg',
		firstName: 'Michael',
		lastName: 'Brown',
		role: 'Staff',
		status: 'active',
		email: 'michael.brown@example.com',
	},
];
