/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithDeadLetterItemRequestBuilder, WithDeadLetterItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/dead-letter
 */
export interface DeadLetterRequestBuilder extends BaseRequestBuilder<DeadLetterRequestBuilder> {
    /**
     * Gets an item from the PublyApp.Api.Client.staff.deadLetter.item collection
     * @param deadLetterId Unique identifier of the item
     * @returns {WithDeadLetterItemRequestBuilder}
     */
     byDeadLetterId(deadLetterId: string) : WithDeadLetterItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DeadLetterRequestBuilderUriTemplate = "{+baseurl}/staff/dead-letter";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DeadLetterRequestBuilderNavigationMetadata: Record<Exclude<keyof DeadLetterRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byDeadLetterId: {
        navigationMetadata: WithDeadLetterItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["deadLetterId"],
    },
};
/* tslint:enable */
/* eslint-enable */
