/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiResponseFromDiscriminatorValue, createResetPasswordResultFromDiscriminatorValue, serializeResetPasswordBody, serializeResetPasswordResult, type ApiResponse, type ResetPasswordBody, type ResetPasswordResult } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth/reset-password
 */
export interface ResetPasswordRequestBuilder extends BaseRequestBuilder<ResetPasswordRequestBuilder> {
    /**
     * Reset Password
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResetPasswordResult>}
     * @throws {ApiResponse} error when the service returns a 400 status code
     * @throws {ApiResponse} error when the service returns a 500 status code
     */
     post(body: ResetPasswordBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ResetPasswordResult | undefined>;
    /**
     * Reset Password
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ResetPasswordBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ResetPasswordRequestBuilderUriTemplate = "{+baseurl}/auth/reset-password";
/**
 * Metadata for all the requests in the request builder.
 */
export const ResetPasswordRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ResetPasswordRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createResetPasswordResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeResetPasswordBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
