/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as loginRouteImport } from './routes/login'
import { Route as fieldValidationRouteImport } from './routes/field-validation'
import { Route as authedLayoutRouteImport } from './routes/authed/layout'
import { Route as indexRouteImport } from './routes/index'
import { Route as authedTenantRouteImport } from './routes/authed/tenant'
import { Route as authedStaffRouteImport } from './routes/authed/staff'
import { Route as authedStaffStaffUsersRouteImport } from './routes/authed/staff/staff-users'
import { Route as authedStaffInvitationsIndexRouteImport } from './routes/authed/staff/invitations/index'
import { Route as authedStaffInvitationsNewRouteImport } from './routes/authed/staff/invitations/new'
import { Route as authedStaffInvitationsInvitationIdRouteImport } from './routes/authed/staff/invitations/$invitationId'

const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const fieldValidationRoute = fieldValidationRouteImport.update({
  id: '/field-validation',
  path: '/field-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const authedLayoutRoute = authedLayoutRouteImport.update({
  id: '/_authed-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authedTenantRoute = authedTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffRoute = authedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffStaffUsersRoute = authedStaffStaffUsersRouteImport.update({
  id: '/staff/staff-users',
  path: '/staff/staff-users',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffInvitationsIndexRoute =
  authedStaffInvitationsIndexRouteImport.update({
    id: '/staff/invitations',
    path: '/staff/invitations',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffInvitationsNewRoute =
  authedStaffInvitationsNewRouteImport.update({
    id: '/staff/invitations/new',
    path: '/staff/invitations/new',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffInvitationsInvitationIdRoute =
  authedStaffInvitationsInvitationIdRouteImport.update({
    id: '/staff/invitations/$invitationId',
    path: '/staff/invitations/$invitationId',
    getParentRoute: () => authedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/field-validation': typeof fieldValidationRoute
  '/login': typeof loginRoute
  '/staff': typeof authedStaffRoute
  '/tenant': typeof authedTenantRoute
  '/staff/staff-users': typeof authedStaffStaffUsersRoute
  '/staff/invitations': typeof authedStaffInvitationsIndexRoute
  '/staff/invitations/new': typeof authedStaffInvitationsNewRoute
  '/staff/invitations/$invitationId': typeof authedStaffInvitationsInvitationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/field-validation': typeof fieldValidationRoute
  '/login': typeof loginRoute
  '/staff': typeof authedStaffRoute
  '/tenant': typeof authedTenantRoute
  '/staff/staff-users': typeof authedStaffStaffUsersRoute
  '/staff/invitations': typeof authedStaffInvitationsIndexRoute
  '/staff/invitations/new': typeof authedStaffInvitationsNewRoute
  '/staff/invitations/$invitationId': typeof authedStaffInvitationsInvitationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/_authed-layout': typeof authedLayoutRouteWithChildren
  '/field-validation': typeof fieldValidationRoute
  '/login': typeof loginRoute
  '/_authed-layout/staff': typeof authedStaffRoute
  '/_authed-layout/tenant': typeof authedTenantRoute
  '/_authed-layout/staff/staff-users': typeof authedStaffStaffUsersRoute
  '/_authed-layout/staff/invitations/': typeof authedStaffInvitationsIndexRoute
  '/_authed-layout/staff/invitations/new': typeof authedStaffInvitationsNewRoute
  '/_authed-layout/staff/invitations/$invitationId': typeof authedStaffInvitationsInvitationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/field-validation'
    | '/login'
    | '/staff'
    | '/tenant'
    | '/staff/staff-users'
    | '/staff/invitations'
    | '/staff/invitations/new'
    | '/staff/invitations/$invitationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/field-validation'
    | '/login'
    | '/staff'
    | '/tenant'
    | '/staff/staff-users'
    | '/staff/invitations'
    | '/staff/invitations/new'
    | '/staff/invitations/$invitationId'
  id:
    | '__root__'
    | '/'
    | '/_authed-layout'
    | '/field-validation'
    | '/login'
    | '/_authed-layout/staff'
    | '/_authed-layout/tenant'
    | '/_authed-layout/staff/staff-users'
    | '/_authed-layout/staff/invitations/'
    | '/_authed-layout/staff/invitations/new'
    | '/_authed-layout/staff/invitations/$invitationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  authedLayoutRoute: typeof authedLayoutRouteWithChildren
  fieldValidationRoute: typeof fieldValidationRoute
  loginRoute: typeof loginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-validation': {
      id: '/field-validation'
      path: '/field-validation'
      fullPath: '/field-validation'
      preLoaderRoute: typeof fieldValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed-layout': {
      id: '/_authed-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof authedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed-layout/tenant': {
      id: '/_authed-layout/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof authedTenantRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff': {
      id: '/_authed-layout/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof authedStaffRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/staff-users': {
      id: '/_authed-layout/staff/staff-users'
      path: '/staff/staff-users'
      fullPath: '/staff/staff-users'
      preLoaderRoute: typeof authedStaffStaffUsersRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/invitations/': {
      id: '/_authed-layout/staff/invitations/'
      path: '/staff/invitations'
      fullPath: '/staff/invitations'
      preLoaderRoute: typeof authedStaffInvitationsIndexRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/invitations/new': {
      id: '/_authed-layout/staff/invitations/new'
      path: '/staff/invitations/new'
      fullPath: '/staff/invitations/new'
      preLoaderRoute: typeof authedStaffInvitationsNewRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/invitations/$invitationId': {
      id: '/_authed-layout/staff/invitations/$invitationId'
      path: '/staff/invitations/$invitationId'
      fullPath: '/staff/invitations/$invitationId'
      preLoaderRoute: typeof authedStaffInvitationsInvitationIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
  }
}

interface authedLayoutRouteChildren {
  authedStaffRoute: typeof authedStaffRoute
  authedTenantRoute: typeof authedTenantRoute
  authedStaffStaffUsersRoute: typeof authedStaffStaffUsersRoute
  authedStaffInvitationsIndexRoute: typeof authedStaffInvitationsIndexRoute
  authedStaffInvitationsNewRoute: typeof authedStaffInvitationsNewRoute
  authedStaffInvitationsInvitationIdRoute: typeof authedStaffInvitationsInvitationIdRoute
}

const authedLayoutRouteChildren: authedLayoutRouteChildren = {
  authedStaffRoute: authedStaffRoute,
  authedTenantRoute: authedTenantRoute,
  authedStaffStaffUsersRoute: authedStaffStaffUsersRoute,
  authedStaffInvitationsIndexRoute: authedStaffInvitationsIndexRoute,
  authedStaffInvitationsNewRoute: authedStaffInvitationsNewRoute,
  authedStaffInvitationsInvitationIdRoute:
    authedStaffInvitationsInvitationIdRoute,
}

const authedLayoutRouteWithChildren = authedLayoutRoute._addFileChildren(
  authedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  authedLayoutRoute: authedLayoutRouteWithChildren,
  fieldValidationRoute: fieldValidationRoute,
  loginRoute: loginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
