/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as loginRouteImport } from './routes/login'
import { Route as fieldValidationRouteImport } from './routes/field-validation'
import { Route as authedLayoutRouteImport } from './routes/authed/layout'
import { Route as indexRouteImport } from './routes/index'
import { Route as authedTenantRouteImport } from './routes/authed/tenant'
import { Route as authedStaffRouteImport } from './routes/authed/staff'
import { Route as authedStaffInvitationsIndexRouteImport } from './routes/authed/staff/invitations/index'
import { Route as authedStaffTenantsRouteImport } from './routes/authed/staff/tenants'
import { Route as authedStaffStaffUsersRouteImport } from './routes/authed/staff/staff-users'
import { Route as authedStaffProfilesRouteImport } from './routes/authed/staff/profiles'
import { Route as authedStaffTenantsTenantIdRouteImport } from './routes/authed/staff/tenants/$tenantId'
import { Route as authedStaffStaffUsersUserIdRouteImport } from './routes/authed/staff/staff-users/$userId'
import { Route as authedStaffProfilesNewRouteImport } from './routes/authed/staff/profiles-new'
import { Route as authedStaffProfilesProfileIdRouteImport } from './routes/authed/staff/profiles/$profileId'
import { Route as authedStaffInvitationsNewRouteImport } from './routes/authed/staff/invitations/new'
import { Route as authedStaffInvitationsInvitationIdRouteImport } from './routes/authed/staff/invitations/$invitationId'
import { Route as authedStaffTenantsTenantIdUsersRouteImport } from './routes/authed/staff/tenants/$tenantId/users'
import { Route as authedStaffTenantsTenantIdProfilesRouteImport } from './routes/authed/staff/tenants/$tenantId/profiles'
import { Route as authedStaffTenantsTenantIdProfilesNewRouteImport } from './routes/authed/staff/tenants/$tenantId/profiles-new'
import { Route as authedStaffTenantsTenantIdInvitationsRouteImport } from './routes/authed/staff/tenants/$tenantId/invitations'
import { Route as authedStaffProfilesProfileIdUsersRouteImport } from './routes/authed/staff/profiles/$profileId/users'
import { Route as authedStaffTenantsTenantIdProfilesProfileIdRouteImport } from './routes/authed/staff/tenants/$tenantId/profiles/$profileId'

const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const fieldValidationRoute = fieldValidationRouteImport.update({
  id: '/field-validation',
  path: '/field-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const authedLayoutRoute = authedLayoutRouteImport.update({
  id: '/_authed-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authedTenantRoute = authedTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffRoute = authedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffInvitationsIndexRoute =
  authedStaffInvitationsIndexRouteImport.update({
    id: '/staff/invitations',
    path: '/staff/invitations',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsRoute = authedStaffTenantsRouteImport.update({
  id: '/staff/tenants',
  path: '/staff/tenants',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffStaffUsersRoute = authedStaffStaffUsersRouteImport.update({
  id: '/staff/staff-users',
  path: '/staff/staff-users',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffProfilesRoute = authedStaffProfilesRouteImport.update({
  id: '/staff/profiles',
  path: '/staff/profiles',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffTenantsTenantIdRoute =
  authedStaffTenantsTenantIdRouteImport.update({
    id: '/staff/tenants/$tenantId',
    path: '/staff/tenants/$tenantId',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffStaffUsersUserIdRoute =
  authedStaffStaffUsersUserIdRouteImport.update({
    id: '/staff/staff-users/$userId',
    path: '/staff/staff-users/$userId',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffProfilesNewRoute = authedStaffProfilesNewRouteImport.update({
  id: '/staff/profiles/new',
  path: '/staff/profiles/new',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffProfilesProfileIdRoute =
  authedStaffProfilesProfileIdRouteImport.update({
    id: '/staff/profiles/$profileId',
    path: '/staff/profiles/$profileId',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffInvitationsNewRoute =
  authedStaffInvitationsNewRouteImport.update({
    id: '/staff/invitations/new',
    path: '/staff/invitations/new',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffInvitationsInvitationIdRoute =
  authedStaffInvitationsInvitationIdRouteImport.update({
    id: '/staff/invitations/$invitationId',
    path: '/staff/invitations/$invitationId',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdUsersRoute =
  authedStaffTenantsTenantIdUsersRouteImport.update({
    id: '/staff/tenants/$tenantId/users',
    path: '/staff/tenants/$tenantId/users',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdProfilesRoute =
  authedStaffTenantsTenantIdProfilesRouteImport.update({
    id: '/staff/tenants/$tenantId/profiles',
    path: '/staff/tenants/$tenantId/profiles',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdProfilesNewRoute =
  authedStaffTenantsTenantIdProfilesNewRouteImport.update({
    id: '/staff/tenants/$tenantId/profiles/new',
    path: '/staff/tenants/$tenantId/profiles/new',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdInvitationsRoute =
  authedStaffTenantsTenantIdInvitationsRouteImport.update({
    id: '/staff/tenants/$tenantId/invitations',
    path: '/staff/tenants/$tenantId/invitations',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffProfilesProfileIdUsersRoute =
  authedStaffProfilesProfileIdUsersRouteImport.update({
    id: '/staff/profiles/$profileId/users',
    path: '/staff/profiles/$profileId/users',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdProfilesProfileIdRoute =
  authedStaffTenantsTenantIdProfilesProfileIdRouteImport.update({
    id: '/staff/tenants/$tenantId/profiles/$profileId',
    path: '/staff/tenants/$tenantId/profiles/$profileId',
    getParentRoute: () => authedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/field-validation': typeof fieldValidationRoute
  '/login': typeof loginRoute
  '/staff': typeof authedStaffRoute
  '/tenant': typeof authedTenantRoute
  '/staff/profiles': typeof authedStaffProfilesRoute
  '/staff/staff-users': typeof authedStaffStaffUsersRoute
  '/staff/tenants': typeof authedStaffTenantsRoute
  '/staff/invitations': typeof authedStaffInvitationsIndexRoute
  '/staff/invitations/$invitationId': typeof authedStaffInvitationsInvitationIdRoute
  '/staff/invitations/new': typeof authedStaffInvitationsNewRoute
  '/staff/profiles/$profileId': typeof authedStaffProfilesProfileIdRoute
  '/staff/profiles/new': typeof authedStaffProfilesNewRoute
  '/staff/staff-users/$userId': typeof authedStaffStaffUsersUserIdRoute
  '/staff/tenants/$tenantId': typeof authedStaffTenantsTenantIdRoute
  '/staff/profiles/$profileId/users': typeof authedStaffProfilesProfileIdUsersRoute
  '/staff/tenants/$tenantId/invitations': typeof authedStaffTenantsTenantIdInvitationsRoute
  '/staff/tenants/$tenantId/profiles': typeof authedStaffTenantsTenantIdProfilesRoute
  '/staff/tenants/$tenantId/profiles/new': typeof authedStaffTenantsTenantIdProfilesNewRoute
  '/staff/tenants/$tenantId/users': typeof authedStaffTenantsTenantIdUsersRoute
  '/staff/tenants/$tenantId/profiles/$profileId': typeof authedStaffTenantsTenantIdProfilesProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/field-validation': typeof fieldValidationRoute
  '/login': typeof loginRoute
  '/staff': typeof authedStaffRoute
  '/tenant': typeof authedTenantRoute
  '/staff/profiles': typeof authedStaffProfilesRoute
  '/staff/staff-users': typeof authedStaffStaffUsersRoute
  '/staff/tenants': typeof authedStaffTenantsRoute
  '/staff/invitations': typeof authedStaffInvitationsIndexRoute
  '/staff/invitations/$invitationId': typeof authedStaffInvitationsInvitationIdRoute
  '/staff/invitations/new': typeof authedStaffInvitationsNewRoute
  '/staff/profiles/$profileId': typeof authedStaffProfilesProfileIdRoute
  '/staff/profiles/new': typeof authedStaffProfilesNewRoute
  '/staff/staff-users/$userId': typeof authedStaffStaffUsersUserIdRoute
  '/staff/tenants/$tenantId': typeof authedStaffTenantsTenantIdRoute
  '/staff/profiles/$profileId/users': typeof authedStaffProfilesProfileIdUsersRoute
  '/staff/tenants/$tenantId/invitations': typeof authedStaffTenantsTenantIdInvitationsRoute
  '/staff/tenants/$tenantId/profiles': typeof authedStaffTenantsTenantIdProfilesRoute
  '/staff/tenants/$tenantId/profiles/new': typeof authedStaffTenantsTenantIdProfilesNewRoute
  '/staff/tenants/$tenantId/users': typeof authedStaffTenantsTenantIdUsersRoute
  '/staff/tenants/$tenantId/profiles/$profileId': typeof authedStaffTenantsTenantIdProfilesProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/_authed-layout': typeof authedLayoutRouteWithChildren
  '/field-validation': typeof fieldValidationRoute
  '/login': typeof loginRoute
  '/_authed-layout/staff': typeof authedStaffRoute
  '/_authed-layout/tenant': typeof authedTenantRoute
  '/_authed-layout/staff/profiles': typeof authedStaffProfilesRoute
  '/_authed-layout/staff/staff-users': typeof authedStaffStaffUsersRoute
  '/_authed-layout/staff/tenants': typeof authedStaffTenantsRoute
  '/_authed-layout/staff/invitations': typeof authedStaffInvitationsIndexRoute
  '/_authed-layout/staff/invitations/$invitationId': typeof authedStaffInvitationsInvitationIdRoute
  '/_authed-layout/staff/invitations/new': typeof authedStaffInvitationsNewRoute
  '/_authed-layout/staff/profiles/$profileId': typeof authedStaffProfilesProfileIdRoute
  '/_authed-layout/staff/profiles/new': typeof authedStaffProfilesNewRoute
  '/_authed-layout/staff/staff-users/$userId': typeof authedStaffStaffUsersUserIdRoute
  '/_authed-layout/staff/tenants/$tenantId': typeof authedStaffTenantsTenantIdRoute
  '/_authed-layout/staff/profiles/$profileId/users': typeof authedStaffProfilesProfileIdUsersRoute
  '/_authed-layout/staff/tenants/$tenantId/invitations': typeof authedStaffTenantsTenantIdInvitationsRoute
  '/_authed-layout/staff/tenants/$tenantId/profiles': typeof authedStaffTenantsTenantIdProfilesRoute
  '/_authed-layout/staff/tenants/$tenantId/profiles/new': typeof authedStaffTenantsTenantIdProfilesNewRoute
  '/_authed-layout/staff/tenants/$tenantId/users': typeof authedStaffTenantsTenantIdUsersRoute
  '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId': typeof authedStaffTenantsTenantIdProfilesProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/field-validation'
    | '/login'
    | '/staff'
    | '/tenant'
    | '/staff/profiles'
    | '/staff/staff-users'
    | '/staff/tenants'
    | '/staff/invitations'
    | '/staff/invitations/$invitationId'
    | '/staff/invitations/new'
    | '/staff/profiles/$profileId'
    | '/staff/profiles/new'
    | '/staff/staff-users/$userId'
    | '/staff/tenants/$tenantId'
    | '/staff/profiles/$profileId/users'
    | '/staff/tenants/$tenantId/invitations'
    | '/staff/tenants/$tenantId/profiles'
    | '/staff/tenants/$tenantId/profiles/new'
    | '/staff/tenants/$tenantId/users'
    | '/staff/tenants/$tenantId/profiles/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/field-validation'
    | '/login'
    | '/staff'
    | '/tenant'
    | '/staff/profiles'
    | '/staff/staff-users'
    | '/staff/tenants'
    | '/staff/invitations'
    | '/staff/invitations/$invitationId'
    | '/staff/invitations/new'
    | '/staff/profiles/$profileId'
    | '/staff/profiles/new'
    | '/staff/staff-users/$userId'
    | '/staff/tenants/$tenantId'
    | '/staff/profiles/$profileId/users'
    | '/staff/tenants/$tenantId/invitations'
    | '/staff/tenants/$tenantId/profiles'
    | '/staff/tenants/$tenantId/profiles/new'
    | '/staff/tenants/$tenantId/users'
    | '/staff/tenants/$tenantId/profiles/$profileId'
  id:
    | '__root__'
    | '/'
    | '/_authed-layout'
    | '/field-validation'
    | '/login'
    | '/_authed-layout/staff'
    | '/_authed-layout/tenant'
    | '/_authed-layout/staff/profiles'
    | '/_authed-layout/staff/staff-users'
    | '/_authed-layout/staff/tenants'
    | '/_authed-layout/staff/invitations'
    | '/_authed-layout/staff/invitations/$invitationId'
    | '/_authed-layout/staff/invitations/new'
    | '/_authed-layout/staff/profiles/$profileId'
    | '/_authed-layout/staff/profiles/new'
    | '/_authed-layout/staff/staff-users/$userId'
    | '/_authed-layout/staff/tenants/$tenantId'
    | '/_authed-layout/staff/profiles/$profileId/users'
    | '/_authed-layout/staff/tenants/$tenantId/invitations'
    | '/_authed-layout/staff/tenants/$tenantId/profiles'
    | '/_authed-layout/staff/tenants/$tenantId/profiles/new'
    | '/_authed-layout/staff/tenants/$tenantId/users'
    | '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  authedLayoutRoute: typeof authedLayoutRouteWithChildren
  fieldValidationRoute: typeof fieldValidationRoute
  loginRoute: typeof loginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-validation': {
      id: '/field-validation'
      path: '/field-validation'
      fullPath: '/field-validation'
      preLoaderRoute: typeof fieldValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed-layout': {
      id: '/_authed-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof authedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed-layout/tenant': {
      id: '/_authed-layout/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof authedTenantRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff': {
      id: '/_authed-layout/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof authedStaffRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/invitations': {
      id: '/_authed-layout/staff/invitations'
      path: '/staff/invitations'
      fullPath: '/staff/invitations'
      preLoaderRoute: typeof authedStaffInvitationsIndexRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants': {
      id: '/_authed-layout/staff/tenants'
      path: '/staff/tenants'
      fullPath: '/staff/tenants'
      preLoaderRoute: typeof authedStaffTenantsRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/staff-users': {
      id: '/_authed-layout/staff/staff-users'
      path: '/staff/staff-users'
      fullPath: '/staff/staff-users'
      preLoaderRoute: typeof authedStaffStaffUsersRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/profiles': {
      id: '/_authed-layout/staff/profiles'
      path: '/staff/profiles'
      fullPath: '/staff/profiles'
      preLoaderRoute: typeof authedStaffProfilesRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId': {
      id: '/_authed-layout/staff/tenants/$tenantId'
      path: '/staff/tenants/$tenantId'
      fullPath: '/staff/tenants/$tenantId'
      preLoaderRoute: typeof authedStaffTenantsTenantIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/staff-users/$userId': {
      id: '/_authed-layout/staff/staff-users/$userId'
      path: '/staff/staff-users/$userId'
      fullPath: '/staff/staff-users/$userId'
      preLoaderRoute: typeof authedStaffStaffUsersUserIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/profiles/new': {
      id: '/_authed-layout/staff/profiles/new'
      path: '/staff/profiles/new'
      fullPath: '/staff/profiles/new'
      preLoaderRoute: typeof authedStaffProfilesNewRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/profiles/$profileId': {
      id: '/_authed-layout/staff/profiles/$profileId'
      path: '/staff/profiles/$profileId'
      fullPath: '/staff/profiles/$profileId'
      preLoaderRoute: typeof authedStaffProfilesProfileIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/invitations/new': {
      id: '/_authed-layout/staff/invitations/new'
      path: '/staff/invitations/new'
      fullPath: '/staff/invitations/new'
      preLoaderRoute: typeof authedStaffInvitationsNewRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/invitations/$invitationId': {
      id: '/_authed-layout/staff/invitations/$invitationId'
      path: '/staff/invitations/$invitationId'
      fullPath: '/staff/invitations/$invitationId'
      preLoaderRoute: typeof authedStaffInvitationsInvitationIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/users': {
      id: '/_authed-layout/staff/tenants/$tenantId/users'
      path: '/staff/tenants/$tenantId/users'
      fullPath: '/staff/tenants/$tenantId/users'
      preLoaderRoute: typeof authedStaffTenantsTenantIdUsersRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/profiles': {
      id: '/_authed-layout/staff/tenants/$tenantId/profiles'
      path: '/staff/tenants/$tenantId/profiles'
      fullPath: '/staff/tenants/$tenantId/profiles'
      preLoaderRoute: typeof authedStaffTenantsTenantIdProfilesRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/profiles/new': {
      id: '/_authed-layout/staff/tenants/$tenantId/profiles/new'
      path: '/staff/tenants/$tenantId/profiles/new'
      fullPath: '/staff/tenants/$tenantId/profiles/new'
      preLoaderRoute: typeof authedStaffTenantsTenantIdProfilesNewRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/invitations': {
      id: '/_authed-layout/staff/tenants/$tenantId/invitations'
      path: '/staff/tenants/$tenantId/invitations'
      fullPath: '/staff/tenants/$tenantId/invitations'
      preLoaderRoute: typeof authedStaffTenantsTenantIdInvitationsRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/profiles/$profileId/users': {
      id: '/_authed-layout/staff/profiles/$profileId/users'
      path: '/staff/profiles/$profileId/users'
      fullPath: '/staff/profiles/$profileId/users'
      preLoaderRoute: typeof authedStaffProfilesProfileIdUsersRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId': {
      id: '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId'
      path: '/staff/tenants/$tenantId/profiles/$profileId'
      fullPath: '/staff/tenants/$tenantId/profiles/$profileId'
      preLoaderRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
  }
}

interface authedLayoutRouteChildren {
  authedStaffRoute: typeof authedStaffRoute
  authedTenantRoute: typeof authedTenantRoute
  authedStaffProfilesRoute: typeof authedStaffProfilesRoute
  authedStaffStaffUsersRoute: typeof authedStaffStaffUsersRoute
  authedStaffTenantsRoute: typeof authedStaffTenantsRoute
  authedStaffInvitationsIndexRoute: typeof authedStaffInvitationsIndexRoute
  authedStaffInvitationsInvitationIdRoute: typeof authedStaffInvitationsInvitationIdRoute
  authedStaffInvitationsNewRoute: typeof authedStaffInvitationsNewRoute
  authedStaffProfilesProfileIdRoute: typeof authedStaffProfilesProfileIdRoute
  authedStaffProfilesNewRoute: typeof authedStaffProfilesNewRoute
  authedStaffStaffUsersUserIdRoute: typeof authedStaffStaffUsersUserIdRoute
  authedStaffTenantsTenantIdRoute: typeof authedStaffTenantsTenantIdRoute
  authedStaffProfilesProfileIdUsersRoute: typeof authedStaffProfilesProfileIdUsersRoute
  authedStaffTenantsTenantIdInvitationsRoute: typeof authedStaffTenantsTenantIdInvitationsRoute
  authedStaffTenantsTenantIdProfilesRoute: typeof authedStaffTenantsTenantIdProfilesRoute
  authedStaffTenantsTenantIdProfilesNewRoute: typeof authedStaffTenantsTenantIdProfilesNewRoute
  authedStaffTenantsTenantIdUsersRoute: typeof authedStaffTenantsTenantIdUsersRoute
  authedStaffTenantsTenantIdProfilesProfileIdRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdRoute
}

const authedLayoutRouteChildren: authedLayoutRouteChildren = {
  authedStaffRoute: authedStaffRoute,
  authedTenantRoute: authedTenantRoute,
  authedStaffProfilesRoute: authedStaffProfilesRoute,
  authedStaffStaffUsersRoute: authedStaffStaffUsersRoute,
  authedStaffTenantsRoute: authedStaffTenantsRoute,
  authedStaffInvitationsIndexRoute: authedStaffInvitationsIndexRoute,
  authedStaffInvitationsInvitationIdRoute:
    authedStaffInvitationsInvitationIdRoute,
  authedStaffInvitationsNewRoute: authedStaffInvitationsNewRoute,
  authedStaffProfilesProfileIdRoute: authedStaffProfilesProfileIdRoute,
  authedStaffProfilesNewRoute: authedStaffProfilesNewRoute,
  authedStaffStaffUsersUserIdRoute: authedStaffStaffUsersUserIdRoute,
  authedStaffTenantsTenantIdRoute: authedStaffTenantsTenantIdRoute,
  authedStaffProfilesProfileIdUsersRoute:
    authedStaffProfilesProfileIdUsersRoute,
  authedStaffTenantsTenantIdInvitationsRoute:
    authedStaffTenantsTenantIdInvitationsRoute,
  authedStaffTenantsTenantIdProfilesRoute:
    authedStaffTenantsTenantIdProfilesRoute,
  authedStaffTenantsTenantIdProfilesNewRoute:
    authedStaffTenantsTenantIdProfilesNewRoute,
  authedStaffTenantsTenantIdUsersRoute: authedStaffTenantsTenantIdUsersRoute,
  authedStaffTenantsTenantIdProfilesProfileIdRoute:
    authedStaffTenantsTenantIdProfilesProfileIdRoute,
}

const authedLayoutRouteWithChildren = authedLayoutRoute._addFileChildren(
  authedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  authedLayoutRoute: authedLayoutRouteWithChildren,
  fieldValidationRoute: fieldValidationRoute,
  loginRoute: loginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
