/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
	createAppProblemDetailsFromDiscriminatorValue,
	createGetVerificationLinkResultFromDiscriminatorValue,
	createValidationProblemDetailsFromDiscriminatorValue,
	type AppProblemDetails,
	type GetVerificationLinkResult,
	type ValidationProblemDetails,
} from '../../models/index.js';
// @ts-ignore
import {
	type BaseRequestBuilder,
	type Parsable,
	type ParsableFactory,
	type RequestConfiguration,
	type RequestInformation,
	type RequestsMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth/verification-link
 */
export interface VerificationLinkRequestBuilder
	extends BaseRequestBuilder<VerificationLinkRequestBuilder> {
	/**
	 * Get Verification Link
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {Promise<GetVerificationLinkResult>}
	 * @throws {AppProblemDetails} error when the service returns a 400 status code
	 * @throws {AppProblemDetails} error when the service returns a 404 status code
	 * @throws {ValidationProblemDetails} error when the service returns a 422 status code
	 * @throws {AppProblemDetails} error when the service returns a 500 status code
	 */
	get(
		requestConfiguration?:
			| RequestConfiguration<VerificationLinkRequestBuilderGetQueryParameters>
			| undefined,
	): Promise<GetVerificationLinkResult | undefined>;
	/**
	 * Get Verification Link
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {RequestInformation}
	 */
	toGetRequestInformation(
		requestConfiguration?:
			| RequestConfiguration<VerificationLinkRequestBuilderGetQueryParameters>
			| undefined,
	): RequestInformation;
}
/**
 * Get Verification Link
 */
export interface VerificationLinkRequestBuilderGetQueryParameters {
	userId?: string;
}
/**
 * Uri template for the request builder.
 */
export const VerificationLinkRequestBuilderUriTemplate =
	'{+baseurl}/auth/verification-link?UserId={UserId}';
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const VerificationLinkRequestBuilderGetQueryParametersMapper: Record<
	string,
	string
> = {
	userId: 'UserId',
};
/**
 * Metadata for all the requests in the request builder.
 */
export const VerificationLinkRequestBuilderRequestsMetadata: RequestsMetadata =
	{
		get: {
			uriTemplate: VerificationLinkRequestBuilderUriTemplate,
			responseBodyContentType: 'application/json',
			errorMappings: {
				400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
				404: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
				422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
				500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			},
			adapterMethodName: 'send',
			responseBodyFactory:
				createGetVerificationLinkResultFromDiscriminatorValue,
			queryParametersMapper:
				VerificationLinkRequestBuilderGetQueryParametersMapper,
		},
	};
/* tslint:enable */
/* eslint-enable */
