/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiResponseFromDiscriminatorValue, createGetStaffMemberByIdResultFromDiscriminatorValue, type ApiResponse, type GetStaffMemberByIdResult } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/staff-members/{userId}
 */
export interface WithUserItemRequestBuilder extends BaseRequestBuilder<WithUserItemRequestBuilder> {
    /**
     * Get a staff member by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetStaffMemberByIdResult>}
     * @throws {ApiResponse} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GetStaffMemberByIdResult | undefined>;
    /**
     * Get a staff member by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithUserItemRequestBuilderUriTemplate = "{+baseurl}/staff/staff-members/{userId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithUserItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithUserItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetStaffMemberByIdResultFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
