/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createFindTenantUserCompaniesForStaffResultFromDiscriminatorValue, createTenantUserCompanyBulkActionResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, serializeAssignTenantUserCompaniesForStaffBody, serializeTenantUserCompanyBulkActionResult, type AppProblemDetails, type AssignTenantUserCompaniesForStaffBody, type FindTenantUserCompaniesForStaffResult, type TenantUserCompanyBulkActionResult, type ValidationProblemDetails } from '../../../../models/index.js';
// @ts-ignore
import { BulkReactivateRequestBuilderRequestsMetadata, type BulkReactivateRequestBuilder } from './bulkReactivate/index.js';
// @ts-ignore
import { BulkRemoveRequestBuilderRequestsMetadata, type BulkRemoveRequestBuilder } from './bulkRemove/index.js';
// @ts-ignore
import { BulkSuspendRequestBuilderRequestsMetadata, type BulkSuspendRequestBuilder } from './bulkSuspend/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/tenant-users/{userId}/companies
 */
export interface CompaniesRequestBuilder extends BaseRequestBuilder<CompaniesRequestBuilder> {
    /**
     * The bulkReactivate property
     */
    get bulkReactivate(): BulkReactivateRequestBuilder;
    /**
     * The bulkRemove property
     */
    get bulkRemove(): BulkRemoveRequestBuilder;
    /**
     * The bulkSuspend property
     */
    get bulkSuspend(): BulkSuspendRequestBuilder;
    /**
     * Find companies assigned to a tenant user
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FindTenantUserCompaniesForStaffResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {AppProblemDetails} error when the service returns a 404 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 429 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<CompaniesRequestBuilderGetQueryParameters> | undefined) : Promise<FindTenantUserCompaniesForStaffResult | undefined>;
    /**
     * Assign companies to a tenant user
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TenantUserCompanyBulkActionResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {AppProblemDetails} error when the service returns a 404 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 429 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     post(body: AssignTenantUserCompaniesForStaffBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TenantUserCompanyBulkActionResult | undefined>;
    /**
     * Find companies assigned to a tenant user
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CompaniesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Assign companies to a tenant user
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AssignTenantUserCompaniesForStaffBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Find companies assigned to a tenant user
 */
export interface CompaniesRequestBuilderGetQueryParameters {
    cursor?: string;
    limit?: string;
    q?: string;
    sortId?: string;
    sortOrder?: string;
}
/**
 * Uri template for the request builder.
 */
export const CompaniesRequestBuilderUriTemplate = "{+baseurl}/staff/tenant-users/{userId}/companies{?cursor*,limit*,q*,sort_id*,sort_order*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const CompaniesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "sortId": "sort_id",
    "sortOrder": "sort_order",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CompaniesRequestBuilderNavigationMetadata: Record<Exclude<keyof CompaniesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bulkReactivate: {
        requestsMetadata: BulkReactivateRequestBuilderRequestsMetadata,
    },
    bulkRemove: {
        requestsMetadata: BulkRemoveRequestBuilderRequestsMetadata,
    },
    bulkSuspend: {
        requestsMetadata: BulkSuspendRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CompaniesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CompaniesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFindTenantUserCompaniesForStaffResultFromDiscriminatorValue,
        queryParametersMapper: CompaniesRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: CompaniesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTenantUserCompanyBulkActionResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAssignTenantUserCompaniesForStaffBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
