/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createGetScopeAuthDataTenantFromDiscriminatorValue, type AppProblemDetails, type GetScopeAuthDataTenant } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth/scope-auth-data
 */
export interface ScopeAuthDataRequestBuilder extends BaseRequestBuilder<ScopeAuthDataRequestBuilder> {
    /**
     * Get Scope Auth Data
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetScopeAuthDataTenant>}
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<ScopeAuthDataRequestBuilderGetQueryParameters> | undefined) : Promise<GetScopeAuthDataTenant | undefined>;
    /**
     * Get Scope Auth Data
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ScopeAuthDataRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get Scope Auth Data
 */
export interface ScopeAuthDataRequestBuilderGetQueryParameters {
    scope?: string;
}
/**
 * Uri template for the request builder.
 */
export const ScopeAuthDataRequestBuilderUriTemplate = "{+baseurl}/auth/scope-auth-data?scope={scope}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ScopeAuthDataRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ScopeAuthDataRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetScopeAuthDataTenantFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
