/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiResponseFromDiscriminatorValue, createFindTenantProfilesAsStaffResultFromDiscriminatorValue, type ApiResponse, type FindTenantProfilesAsStaffResult } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/profiles/tenant/{tenantId}
 */
export interface WithTenantItemRequestBuilder extends BaseRequestBuilder<WithTenantItemRequestBuilder> {
    /**
     * Find profiles
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FindTenantProfilesAsStaffResult>}
     * @throws {ApiResponse} error when the service returns a 400 status code
     * @throws {ApiResponse} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<WithTenantItemRequestBuilderGetQueryParameters> | undefined) : Promise<FindTenantProfilesAsStaffResult | undefined>;
    /**
     * Find profiles
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<WithTenantItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Find profiles
 */
export interface WithTenantItemRequestBuilderGetQueryParameters {
    limit?: string;
    page?: string;
    sortId?: string;
    sortOrder?: string;
}
/**
 * Uri template for the request builder.
 */
export const WithTenantItemRequestBuilderUriTemplate = "{+baseurl}/staff/profiles/tenant/{tenantId}{?Limit*,Page*,SortId*,SortOrder*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const WithTenantItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "limit": "Limit",
    "page": "Page",
    "sortId": "SortId",
    "sortOrder": "SortOrder",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithTenantItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithTenantItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFindTenantProfilesAsStaffResultFromDiscriminatorValue,
        queryParametersMapper: WithTenantItemRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
