/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiResponseFromDiscriminatorValue, createCreateTenantAsStaffResultFromDiscriminatorValue, serializeCreateTenantAsStaffBody, serializeCreateTenantAsStaffResult, type ApiResponse, type CreateTenantAsStaffBody, type CreateTenantAsStaffResult } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/tenants
 */
export interface TenantsRequestBuilder extends BaseRequestBuilder<TenantsRequestBuilder> {
    /**
     * Create a new tenant
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreateTenantAsStaffResult>}
     * @throws {ApiResponse} error when the service returns a 400 status code
     * @throws {ApiResponse} error when the service returns a 500 status code
     */
     post(body: CreateTenantAsStaffBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreateTenantAsStaffResult | undefined>;
    /**
     * Create a new tenant
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateTenantAsStaffBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TenantsRequestBuilderUriTemplate = "{+baseurl}/staff/tenants";
/**
 * Metadata for all the requests in the request builder.
 */
export const TenantsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: TenantsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreateTenantAsStaffResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateTenantAsStaffBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
