import type { TenantRowData } from './tenants-table';

export const mockDataTenants: TenantRowData[] = [
	{
		id: 'org_1',
		name: 'Alpha Tech',
		logoUrl: 'https://logo.clearbit.com/redbull.com',
		users: { count: 50, maxAllowed: 100 },
		status: 'active',
		pricingPlan: 'free',
	},
	{
		id: 'org_2',
		name: 'Beta Labs',
		logoUrl: 'https://logo.clearbit.com/office.com',
		users: { count: 80, maxAllowed: 100 },
		status: 'active',
		pricingPlan: 'free',
	},
	{
		id: 'org_3',
		name: 'Gamma Solutions',
		logoUrl: 'https://logo.clearbit.com/amazon.com',
		users: { count: 10, maxAllowed: 100 },
		status: 'active',
		pricingPlan: 'free',
	},
	{
		id: 'org_4',
		name: 'Delta Innovations',
		logoUrl: 'https://logo.clearbit.com/tesla.com',
		users: { count: 95, maxAllowed: 100 },
		status: 'active',
		pricingPlan: 'free',
	},
	{
		id: 'org_5',
		name: 'Epsilon Systems',
		logoUrl: 'https://logo.clearbit.com/netflix.com',
		users: { count: 30, maxAllowed: 100 },
		status: 'active',
		pricingPlan: 'free',
	},
	{
		id: 'org_6',
		name: 'Zeta Networks',
		logoUrl: 'https://logo.clearbit.com/adobe.com',
		users: { count: 120, maxAllowed: 200 },
		status: 'active',
		pricingPlan: 'bronze',
	},
	{
		id: 'org_7',
		name: 'Eta Designs',
		logoUrl: 'https://logo.clearbit.com/redbull.com',
		users: { count: 150, maxAllowed: 200 },
		status: 'active',
		pricingPlan: 'bronze',
	},
	{
		id: 'org_8',
		name: 'Theta Analytics',
		logoUrl: 'https://logo.clearbit.com/office.com',
		users: { count: 180, maxAllowed: 200 },
		status: 'active',
		pricingPlan: 'bronze',
	},
	{
		id: 'org_9',
		name: 'Iota Robotics',
		logoUrl: 'https://logo.clearbit.com/amazon.com',
		users: { count: 50, maxAllowed: 200 },
		status: 'active',
		pricingPlan: 'bronze',
	},
	{
		id: 'org_10',
		name: 'Kappa Media',
		logoUrl: 'https://logo.clearbit.com/tesla.com',
		users: { count: 200, maxAllowed: 200 },
		status: 'active',
		pricingPlan: 'bronze',
	},
	{
		id: 'org_11',
		name: 'Lambda Cloud',
		logoUrl: 'https://logo.clearbit.com/netflix.com',
		users: { count: 250, maxAllowed: 500 },
		status: 'active',
		pricingPlan: 'silver',
	},
	{
		id: 'org_12',
		name: 'Mu Security',
		logoUrl: 'https://logo.clearbit.com/adobe.com',
		users: { count: 400, maxAllowed: 500 },
		status: 'active',
		pricingPlan: 'silver',
	},
	{
		id: 'org_13',
		name: 'Nu Finance',
		logoUrl: 'https://logo.clearbit.com/salesforce.com',
		users: { count: 300, maxAllowed: 500 },
		status: 'active',
		pricingPlan: 'silver',
	},
	{
		id: 'org_14',
		name: 'Xi Logistics',
		logoUrl: 'https://logo.clearbit.com/oracle.com',
		users: { count: 500, maxAllowed: 500 },
		status: 'active',
		pricingPlan: 'silver',
	},
	{
		id: 'org_15',
		name: 'Omicron Health',
		logoUrl: 'https://logo.clearbit.com/ibm.com',
		users: { count: 100, maxAllowed: 500 },
		status: 'active',
		pricingPlan: 'silver',
	},
	{
		id: 'org_16',
		name: 'Pi AI',
		logoUrl: 'https://logo.clearbit.com/intel.com',
		users: { count: 600, maxAllowed: 1000 },
		status: 'active',
		pricingPlan: 'gold',
	},
	{
		id: 'org_17',
		name: 'Rho Energy',
		logoUrl: 'https://logo.clearbit.com/nvidia.com',
		users: { count: 900, maxAllowed: 1000 },
		status: 'active',
		pricingPlan: 'gold',
	},
	{
		id: 'org_18',
		name: 'Sigma Motors',
		logoUrl: 'https://logo.clearbit.com/sony.com',
		users: { count: 1000, maxAllowed: 1000 },
		status: 'active',
		pricingPlan: 'gold',
	},
	{
		id: 'org_19',
		name: 'Tau Aerospace',
		logoUrl: 'https://logo.clearbit.com/tiktok.com',
		users: { count: 1500, maxAllowed: 5000 },
		status: 'active',
		pricingPlan: 'platinum',
	},
	{
		id: 'org_20',
		name: 'Upsilon Banking',
		logoUrl: 'https://logo.clearbit.com/pinterest.com',
		users: { count: 3000, maxAllowed: 5000 },
		status: 'active',
		pricingPlan: 'platinum',
	},
	{
		id: 'org_21',
		name: 'Phoenix Labs (Old)',
		logoUrl: 'https://logo.clearbit.com/reddit.com',
		users: { count: 0, maxAllowed: 100 },
		status: 'archived',
		pricingPlan: 'free',
	},
	{
		id: 'org_22',
		name: 'Ancient Systems',
		logoUrl: 'https://logo.clearbit.com/walmart.com',
		users: { count: 50, maxAllowed: 200 },
		status: 'archived',
		pricingPlan: 'bronze',
	},
	{
		id: 'org_23',
		name: 'Legacy Tech',
		logoUrl: 'https://logo.clearbit.com/alibaba.com',
		users: { count: 200, maxAllowed: 500 },
		status: 'archived',
		pricingPlan: 'silver',
	},
	{
		id: 'org_24',
		name: 'Obsolete Corp',
		logoUrl: 'https://logo.clearbit.com/ebay.com',
		users: { count: 800, maxAllowed: 1000 },
		status: 'archived',
		pricingPlan: 'gold',
	},
	{
		id: 'org_25',
		name: 'Defunct Ltd',
		logoUrl: 'https://logo.clearbit.com/jpmorganchase.com',
		users: { count: 2000, maxAllowed: 5000 },
		status: 'archived',
		pricingPlan: 'platinum',
	},
	{
		id: 'org_26',
		name: 'Retired Solutions',
		logoUrl: 'https://logo.clearbit.com/visa.com',
		users: { count: 10, maxAllowed: 100 },
		status: 'archived',
		pricingPlan: 'free',
	},
	{
		id: 'org_27',
		name: 'Vintage Cloud',
		logoUrl: 'https://logo.clearbit.com/toyota.com',
		users: { count: 100, maxAllowed: 200 },
		status: 'archived',
		pricingPlan: 'bronze',
	},
	{
		id: 'org_28',
		name: 'Deprecated AI',
		logoUrl: 'https://logo.clearbit.com/salesforce.com',
		users: { count: 300, maxAllowed: 500 },
		status: 'archived',
		pricingPlan: 'silver',
	},
	{
		id: 'org_29',
		name: 'Sunset Industries',
		logoUrl: 'https://logo.clearbit.com/adobe.com',
		users: { count: 700, maxAllowed: 1000 },
		status: 'archived',
		pricingPlan: 'gold',
	},
	{
		id: 'org_30',
		name: 'Discontinued Global',
		logoUrl: 'https://logo.clearbit.com/ibm.com',
		users: { count: 4000, maxAllowed: 5000 },
		status: 'archived',
		pricingPlan: 'platinum',
	},
];
