/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as indexRouteImport } from './routes/index'
import { Route as authedLayoutRouteImport } from './routes/authed/layout'
import { Route as acceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as fieldValidationRouteImport } from './routes/field-validation'
import { Route as healthRouteImport } from './routes/health'
import { Route as loginRouteImport } from './routes/login'
import { Route as resetPasswordRouteImport } from './routes/reset-password'
import { Route as signupRouteImport } from './routes/signup'
import { Route as verifyEmailRouteImport } from './routes/verify-email'
import { Route as authedStaffRouteImport } from './routes/authed/staff'
import { Route as authedTenantRouteImport } from './routes/authed/tenant'
import { Route as authedStaffAuditLogsRouteImport } from './routes/authed/staff/audit-logs'
import { Route as authedStaffDashboardRouteImport } from './routes/authed/staff/dashboard'
import { Route as authedStaffInvitationsIndexRouteImport } from './routes/authed/staff/invitations/index'
import { Route as authedStaffJobsRouteImport } from './routes/authed/staff/jobs'
import { Route as authedStaffProfilesRouteImport } from './routes/authed/staff/profiles'
import { Route as authedStaffStaffUsersRouteImport } from './routes/authed/staff/staff-users'
import { Route as authedStaffTenantsRouteImport } from './routes/authed/staff/tenants'
import { Route as authedTenantAccountRouteImport } from './routes/authed/tenant/account'
import { Route as authedTenantOrganizationsRouteImport } from './routes/authed/tenant/organizations'
import { Route as authedTenantPostsRouteImport } from './routes/authed/tenant/posts'
import { Route as authedTenantSettingsRouteImport } from './routes/authed/tenant/settings'
import { Route as authedStaffAuditLogsLogIdRouteImport } from './routes/authed/staff/audit-logs/$logId'
import { Route as authedStaffDashboardIndexRouteImport } from './routes/authed/staff/dashboard/index'
import { Route as authedStaffDashboardActivityRouteImport } from './routes/authed/staff/dashboard/activity'
import { Route as authedStaffDashboardReportsRouteImport } from './routes/authed/staff/dashboard/reports'
import { Route as authedStaffInvitationsInvitationIdRouteImport } from './routes/authed/staff/invitations/$invitationId'
import { Route as authedStaffInvitationsNewRouteImport } from './routes/authed/staff/invitations/new'
import { Route as authedStaffJobsQueueRouteImport } from './routes/authed/staff/jobs/queue'
import { Route as authedStaffJobsDeadLetterRouteImport } from './routes/authed/staff/jobs/dead-letter'
import { Route as authedStaffJobsSystemJobsRouteImport } from './routes/authed/staff/jobs/system-jobs'
import { Route as authedStaffProfilesProfileIdRouteImport } from './routes/authed/staff/profiles/$profileId'
import { Route as authedStaffProfilesNewRouteImport } from './routes/authed/staff/profiles-new'
import { Route as authedStaffStaffUsersUserIdRouteImport } from './routes/authed/staff/staff-users/$userId'
import { Route as authedStaffTenantsTenantIdRouteImport } from './routes/authed/staff/tenants/$tenantId'
import { Route as authedStaffTenantsNewRouteImport } from './routes/authed/staff/tenants-new'
import { Route as authedTenantAccountProfileRouteImport } from './routes/authed/tenant/account/profile'
import { Route as authedTenantAccountNotificationsRouteImport } from './routes/authed/tenant/account/notifications'
import { Route as authedTenantAccountSecurityRouteImport } from './routes/authed/tenant/account/security'
import { Route as authedTenantPostsCalendarRouteImport } from './routes/authed/tenant/posts/calendar'
import { Route as authedTenantPostsDraftsRouteImport } from './routes/authed/tenant/posts/drafts'
import { Route as authedTenantPostsHistoryRouteImport } from './routes/authed/tenant/posts/history'
import { Route as authedTenantPostsQueueRouteImport } from './routes/authed/tenant/posts/queue'
import { Route as authedTenantSettingsGeneralRouteImport } from './routes/authed/tenant/settings/general'
import { Route as authedTenantSettingsBillingRouteImport } from './routes/authed/tenant/settings/billing'
import { Route as authedTenantSettingsIntegrationsRouteImport } from './routes/authed/tenant/settings/integrations'
import { Route as authedTenantSettingsMembersRouteImport } from './routes/authed/tenant/settings/members'
import { Route as authedTenantSettingsRolesRouteImport } from './routes/authed/tenant/settings/roles'
import { Route as authedTenantSettingsSecurityRouteImport } from './routes/authed/tenant/settings/security'
import { Route as authedTenantSettingsWorkspacesRouteImport } from './routes/authed/tenant/settings/workspaces'
import { Route as authedStaffProfilesProfileIdUsersRouteImport } from './routes/authed/staff/profiles/$profileId/users'
import { Route as authedStaffStaffUsersUserIdIndexRouteImport } from './routes/authed/staff/staff-users/$userId/index'
import { Route as authedStaffStaffUsersUserIdActivityRouteImport } from './routes/authed/staff/staff-users/$userId/activity'
import { Route as authedStaffStaffUsersUserIdEditRouteImport } from './routes/authed/staff/staff-users/$userId-edit'
import { Route as authedStaffStaffUsersUserIdPermissionsRouteImport } from './routes/authed/staff/staff-users/$userId/permissions'
import { Route as authedStaffStaffUsersUserIdSettingsRouteImport } from './routes/authed/staff/staff-users/$userId/settings'
import { Route as authedStaffTenantUsersDetailsUserIdRouteImport } from './routes/authed/staff/tenant-users-details-$userId'
import { Route as authedStaffTenantsTenantIdActivityRouteImport } from './routes/authed/staff/tenants/$tenantId/activity'
import { Route as authedStaffTenantsTenantIdEditRouteImport } from './routes/authed/staff/tenants/$tenantId-edit'
import { Route as authedStaffTenantsTenantIdInvitationsRouteImport } from './routes/authed/staff/tenants/$tenantId/invitations'
import { Route as authedStaffTenantsTenantIdProfilesRouteImport } from './routes/authed/staff/tenants/$tenantId/profiles'
import { Route as authedStaffTenantsTenantIdUsageRouteImport } from './routes/authed/staff/tenants/$tenantId/usage'
import { Route as authedStaffTenantsTenantIdUsersRouteImport } from './routes/authed/staff/tenants/$tenantId/users'
import { Route as authedTenantPostsPostIdEditRouteImport } from './routes/authed/tenant/posts/$postId/edit'
import { Route as authedStaffTenantUserDetailsTabFallbackRouteImport } from './routes/authed/staff/_tenant-user-details-tab-fallback'
import { Route as authedStaffTenantUsersUserIdGeneralRouteImport } from './routes/authed/staff/tenant-users/$userId-general'
import { Route as authedStaffTenantUsersUserIdOrganizationsRouteImport } from './routes/authed/staff/tenant-users/$userId-organizations'
import { Route as authedStaffTenantsTenantIdProfilesProfileIdRouteImport } from './routes/authed/staff/tenants/$tenantId/profiles/$profileId'
import { Route as authedStaffTenantsTenantIdProfilesNewRouteImport } from './routes/authed/staff/tenants/$tenantId/profiles-new'
import { Route as authedStaffTenantsTenantIdUsersUserIdRouteImport } from './routes/authed/staff/tenants/$tenantId/users/$userId'
import { Route as authedStaffTenantsTenantIdUsersInviteRouteImport } from './routes/authed/staff/tenants/$tenantId/users-invite'
import { Route as authedStaffTenantsTenantIdProfilesProfileIdIndexRouteImport } from './routes/authed/staff/tenants/$tenantId/profiles/$profileId/index'
import { Route as authedStaffTenantsTenantIdProfilesProfileIdEditRouteImport } from './routes/authed/staff/tenants/$tenantId/profiles/$profileId-edit'
import { Route as authedStaffTenantsTenantIdProfilesProfileIdMembersRouteImport } from './routes/authed/staff/tenants/$tenantId/profiles/$profileId/members'
import { Route as authedStaffTenantsTenantIdProfilesProfileIdPermissionsRouteImport } from './routes/authed/staff/tenants/$tenantId/profiles/$profileId/permissions'
import { Route as authedStaffTenantsTenantIdProfilesProfileIdUsersRouteImport } from './routes/authed/staff/tenants/$tenantId/profiles/$profileId/users'
import { Route as authedStaffTenantsTenantIdUsersUserIdEditRouteImport } from './routes/authed/staff/tenants/$tenantId/users/$userId-edit'

const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authedLayoutRoute = authedLayoutRouteImport.update({
  id: '/_authed-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const acceptInvitationRoute = acceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const fieldValidationRoute = fieldValidationRouteImport.update({
  id: '/field-validation',
  path: '/field-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const healthRoute = healthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const resetPasswordRoute = resetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const signupRoute = signupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const verifyEmailRoute = verifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authedStaffRoute = authedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedTenantRoute = authedTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffAuditLogsRoute = authedStaffAuditLogsRouteImport.update({
  id: '/staff/audit-logs',
  path: '/staff/audit-logs',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffDashboardRoute = authedStaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffInvitationsIndexRoute =
  authedStaffInvitationsIndexRouteImport.update({
    id: '/staff/invitations',
    path: '/staff/invitations',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffJobsRoute = authedStaffJobsRouteImport.update({
  id: '/staff/jobs',
  path: '/staff/jobs',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffProfilesRoute = authedStaffProfilesRouteImport.update({
  id: '/staff/profiles',
  path: '/staff/profiles',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffStaffUsersRoute = authedStaffStaffUsersRouteImport.update({
  id: '/staff/staff-users',
  path: '/staff/staff-users',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffTenantsRoute = authedStaffTenantsRouteImport.update({
  id: '/staff/tenants',
  path: '/staff/tenants',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedTenantAccountRoute = authedTenantAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => authedTenantRoute,
} as any)
const authedTenantOrganizationsRoute =
  authedTenantOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => authedTenantRoute,
  } as any)
const authedTenantPostsRoute = authedTenantPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => authedTenantRoute,
} as any)
const authedTenantSettingsRoute = authedTenantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authedTenantRoute,
} as any)
const authedStaffAuditLogsLogIdRoute =
  authedStaffAuditLogsLogIdRouteImport.update({
    id: '/staff/audit-logs/$logId',
    path: '/staff/audit-logs/$logId',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffDashboardIndexRoute =
  authedStaffDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authedStaffDashboardRoute,
  } as any)
const authedStaffDashboardActivityRoute =
  authedStaffDashboardActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => authedStaffDashboardRoute,
  } as any)
const authedStaffDashboardReportsRoute =
  authedStaffDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => authedStaffDashboardRoute,
  } as any)
const authedStaffInvitationsInvitationIdRoute =
  authedStaffInvitationsInvitationIdRouteImport.update({
    id: '/staff/invitations/$invitationId',
    path: '/staff/invitations/$invitationId',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffInvitationsNewRoute =
  authedStaffInvitationsNewRouteImport.update({
    id: '/staff/invitations/new',
    path: '/staff/invitations/new',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffJobsQueueRoute = authedStaffJobsQueueRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authedStaffJobsRoute,
} as any)
const authedStaffJobsDeadLetterRoute =
  authedStaffJobsDeadLetterRouteImport.update({
    id: '/dead-letter',
    path: '/dead-letter',
    getParentRoute: () => authedStaffJobsRoute,
  } as any)
const authedStaffJobsSystemJobsRoute =
  authedStaffJobsSystemJobsRouteImport.update({
    id: '/system-jobs',
    path: '/system-jobs',
    getParentRoute: () => authedStaffJobsRoute,
  } as any)
const authedStaffProfilesProfileIdRoute =
  authedStaffProfilesProfileIdRouteImport.update({
    id: '/staff/profiles/$profileId',
    path: '/staff/profiles/$profileId',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffProfilesNewRoute = authedStaffProfilesNewRouteImport.update({
  id: '/staff/profiles/new',
  path: '/staff/profiles/new',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedStaffStaffUsersUserIdRoute =
  authedStaffStaffUsersUserIdRouteImport.update({
    id: '/staff/staff-users/$userId',
    path: '/staff/staff-users/$userId',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdRoute =
  authedStaffTenantsTenantIdRouteImport.update({
    id: '/staff/tenants/$tenantId',
    path: '/staff/tenants/$tenantId',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsNewRoute = authedStaffTenantsNewRouteImport.update({
  id: '/staff/tenants/new',
  path: '/staff/tenants/new',
  getParentRoute: () => authedLayoutRoute,
} as any)
const authedTenantAccountProfileRoute =
  authedTenantAccountProfileRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authedTenantAccountRoute,
  } as any)
const authedTenantAccountNotificationsRoute =
  authedTenantAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => authedTenantAccountRoute,
  } as any)
const authedTenantAccountSecurityRoute =
  authedTenantAccountSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => authedTenantAccountRoute,
  } as any)
const authedTenantPostsCalendarRoute =
  authedTenantPostsCalendarRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authedTenantPostsRoute,
  } as any)
const authedTenantPostsDraftsRoute = authedTenantPostsDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => authedTenantPostsRoute,
} as any)
const authedTenantPostsHistoryRoute =
  authedTenantPostsHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => authedTenantPostsRoute,
  } as any)
const authedTenantPostsQueueRoute = authedTenantPostsQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => authedTenantPostsRoute,
} as any)
const authedTenantSettingsGeneralRoute =
  authedTenantSettingsGeneralRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authedTenantSettingsRoute,
  } as any)
const authedTenantSettingsBillingRoute =
  authedTenantSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => authedTenantSettingsRoute,
  } as any)
const authedTenantSettingsIntegrationsRoute =
  authedTenantSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => authedTenantSettingsRoute,
  } as any)
const authedTenantSettingsMembersRoute =
  authedTenantSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => authedTenantSettingsRoute,
  } as any)
const authedTenantSettingsRolesRoute =
  authedTenantSettingsRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => authedTenantSettingsRoute,
  } as any)
const authedTenantSettingsSecurityRoute =
  authedTenantSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => authedTenantSettingsRoute,
  } as any)
const authedTenantSettingsWorkspacesRoute =
  authedTenantSettingsWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => authedTenantSettingsRoute,
  } as any)
const authedStaffProfilesProfileIdUsersRoute =
  authedStaffProfilesProfileIdUsersRouteImport.update({
    id: '/staff/profiles/$profileId/users',
    path: '/staff/profiles/$profileId/users',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffStaffUsersUserIdIndexRoute =
  authedStaffStaffUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authedStaffStaffUsersUserIdRoute,
  } as any)
const authedStaffStaffUsersUserIdActivityRoute =
  authedStaffStaffUsersUserIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => authedStaffStaffUsersUserIdRoute,
  } as any)
const authedStaffStaffUsersUserIdEditRoute =
  authedStaffStaffUsersUserIdEditRouteImport.update({
    id: '/staff/staff-users/$userId/edit',
    path: '/staff/staff-users/$userId/edit',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffStaffUsersUserIdPermissionsRoute =
  authedStaffStaffUsersUserIdPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => authedStaffStaffUsersUserIdRoute,
  } as any)
const authedStaffStaffUsersUserIdSettingsRoute =
  authedStaffStaffUsersUserIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authedStaffStaffUsersUserIdRoute,
  } as any)
const authedStaffTenantUsersDetailsUserIdRoute =
  authedStaffTenantUsersDetailsUserIdRouteImport.update({
    id: '/staff/tenant-users/details/$userId',
    path: '/staff/tenant-users/details/$userId',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdActivityRoute =
  authedStaffTenantsTenantIdActivityRouteImport.update({
    id: '/staff/tenants/$tenantId/activity',
    path: '/staff/tenants/$tenantId/activity',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdEditRoute =
  authedStaffTenantsTenantIdEditRouteImport.update({
    id: '/staff/tenants/$tenantId/edit',
    path: '/staff/tenants/$tenantId/edit',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdInvitationsRoute =
  authedStaffTenantsTenantIdInvitationsRouteImport.update({
    id: '/staff/tenants/$tenantId/invitations',
    path: '/staff/tenants/$tenantId/invitations',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdProfilesRoute =
  authedStaffTenantsTenantIdProfilesRouteImport.update({
    id: '/staff/tenants/$tenantId/profiles',
    path: '/staff/tenants/$tenantId/profiles',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdUsageRoute =
  authedStaffTenantsTenantIdUsageRouteImport.update({
    id: '/staff/tenants/$tenantId/usage',
    path: '/staff/tenants/$tenantId/usage',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdUsersRoute =
  authedStaffTenantsTenantIdUsersRouteImport.update({
    id: '/staff/tenants/$tenantId/users',
    path: '/staff/tenants/$tenantId/users',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedTenantPostsPostIdEditRoute =
  authedTenantPostsPostIdEditRouteImport.update({
    id: '/posts/$postId/edit',
    path: '/posts/$postId/edit',
    getParentRoute: () => authedTenantRoute,
  } as any)
const authedStaffTenantUserDetailsTabFallbackRoute =
  authedStaffTenantUserDetailsTabFallbackRouteImport.update({
    id: '/staff/tenant-users/details/$userId/$tab',
    path: '/staff/tenant-users/details/$userId/$tab',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantUsersUserIdGeneralRoute =
  authedStaffTenantUsersUserIdGeneralRouteImport.update({
    id: '/staff/tenant-users/details/$userId/general',
    path: '/staff/tenant-users/details/$userId/general',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantUsersUserIdOrganizationsRoute =
  authedStaffTenantUsersUserIdOrganizationsRouteImport.update({
    id: '/staff/tenant-users/details/$userId/organizations',
    path: '/staff/tenant-users/details/$userId/organizations',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdProfilesProfileIdRoute =
  authedStaffTenantsTenantIdProfilesProfileIdRouteImport.update({
    id: '/staff/tenants/$tenantId/profiles/$profileId',
    path: '/staff/tenants/$tenantId/profiles/$profileId',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdProfilesNewRoute =
  authedStaffTenantsTenantIdProfilesNewRouteImport.update({
    id: '/staff/tenants/$tenantId/profiles/new',
    path: '/staff/tenants/$tenantId/profiles/new',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdUsersUserIdRoute =
  authedStaffTenantsTenantIdUsersUserIdRouteImport.update({
    id: '/staff/tenants/$tenantId/users/$userId',
    path: '/staff/tenants/$tenantId/users/$userId',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdUsersInviteRoute =
  authedStaffTenantsTenantIdUsersInviteRouteImport.update({
    id: '/staff/tenants/$tenantId/users/invite',
    path: '/staff/tenants/$tenantId/users/invite',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdProfilesProfileIdIndexRoute =
  authedStaffTenantsTenantIdProfilesProfileIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authedStaffTenantsTenantIdProfilesProfileIdRoute,
  } as any)
const authedStaffTenantsTenantIdProfilesProfileIdEditRoute =
  authedStaffTenantsTenantIdProfilesProfileIdEditRouteImport.update({
    id: '/staff/tenants/$tenantId/profiles/$profileId/edit',
    path: '/staff/tenants/$tenantId/profiles/$profileId/edit',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdProfilesProfileIdMembersRoute =
  authedStaffTenantsTenantIdProfilesProfileIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => authedStaffTenantsTenantIdProfilesProfileIdRoute,
  } as any)
const authedStaffTenantsTenantIdProfilesProfileIdPermissionsRoute =
  authedStaffTenantsTenantIdProfilesProfileIdPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => authedStaffTenantsTenantIdProfilesProfileIdRoute,
  } as any)
const authedStaffTenantsTenantIdProfilesProfileIdUsersRoute =
  authedStaffTenantsTenantIdProfilesProfileIdUsersRouteImport.update({
    id: '/staff/tenants/$tenantId/profiles/$profileId/users',
    path: '/staff/tenants/$tenantId/profiles/$profileId/users',
    getParentRoute: () => authedLayoutRoute,
  } as any)
const authedStaffTenantsTenantIdUsersUserIdEditRoute =
  authedStaffTenantsTenantIdUsersUserIdEditRouteImport.update({
    id: '/staff/tenants/$tenantId/users/$userId/edit',
    path: '/staff/tenants/$tenantId/users/$userId/edit',
    getParentRoute: () => authedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/accept-invitation': typeof acceptInvitationRoute
  '/field-validation': typeof fieldValidationRoute
  '/health': typeof healthRoute
  '/login': typeof loginRoute
  '/reset-password': typeof resetPasswordRoute
  '/signup': typeof signupRoute
  '/verify-email': typeof verifyEmailRoute
  '/staff': typeof authedStaffRoute
  '/tenant': typeof authedTenantRouteWithChildren
  '/staff/audit-logs': typeof authedStaffAuditLogsRoute
  '/staff/dashboard': typeof authedStaffDashboardRouteWithChildren
  '/staff/jobs': typeof authedStaffJobsRouteWithChildren
  '/staff/profiles': typeof authedStaffProfilesRoute
  '/staff/staff-users': typeof authedStaffStaffUsersRoute
  '/staff/tenants': typeof authedStaffTenantsRoute
  '/tenant/account': typeof authedTenantAccountRouteWithChildren
  '/tenant/organizations': typeof authedTenantOrganizationsRoute
  '/tenant/posts': typeof authedTenantPostsRouteWithChildren
  '/tenant/settings': typeof authedTenantSettingsRouteWithChildren
  '/staff/invitations': typeof authedStaffInvitationsIndexRoute
  '/staff/jobs/': typeof authedStaffJobsQueueRoute
  '/tenant/account/': typeof authedTenantAccountProfileRoute
  '/tenant/posts/': typeof authedTenantPostsCalendarRoute
  '/tenant/settings/': typeof authedTenantSettingsGeneralRoute
  '/staff/audit-logs/$logId': typeof authedStaffAuditLogsLogIdRoute
  '/staff/dashboard/activity': typeof authedStaffDashboardActivityRoute
  '/staff/dashboard/reports': typeof authedStaffDashboardReportsRoute
  '/staff/invitations/$invitationId': typeof authedStaffInvitationsInvitationIdRoute
  '/staff/invitations/new': typeof authedStaffInvitationsNewRoute
  '/staff/jobs/dead-letter': typeof authedStaffJobsDeadLetterRoute
  '/staff/jobs/system-jobs': typeof authedStaffJobsSystemJobsRoute
  '/staff/profiles/$profileId': typeof authedStaffProfilesProfileIdRoute
  '/staff/profiles/new': typeof authedStaffProfilesNewRoute
  '/staff/staff-users/$userId': typeof authedStaffStaffUsersUserIdRouteWithChildren
  '/staff/tenants/$tenantId': typeof authedStaffTenantsTenantIdRoute
  '/staff/tenants/new': typeof authedStaffTenantsNewRoute
  '/tenant/account/notifications': typeof authedTenantAccountNotificationsRoute
  '/tenant/account/security': typeof authedTenantAccountSecurityRoute
  '/tenant/posts/drafts': typeof authedTenantPostsDraftsRoute
  '/tenant/posts/history': typeof authedTenantPostsHistoryRoute
  '/tenant/posts/queue': typeof authedTenantPostsQueueRoute
  '/tenant/settings/billing': typeof authedTenantSettingsBillingRoute
  '/tenant/settings/integrations': typeof authedTenantSettingsIntegrationsRoute
  '/tenant/settings/members': typeof authedTenantSettingsMembersRoute
  '/tenant/settings/roles': typeof authedTenantSettingsRolesRoute
  '/tenant/settings/security': typeof authedTenantSettingsSecurityRoute
  '/tenant/settings/workspaces': typeof authedTenantSettingsWorkspacesRoute
  '/staff/dashboard/': typeof authedStaffDashboardIndexRoute
  '/staff/profiles/$profileId/users': typeof authedStaffProfilesProfileIdUsersRoute
  '/staff/staff-users/$userId/activity': typeof authedStaffStaffUsersUserIdActivityRoute
  '/staff/staff-users/$userId/edit': typeof authedStaffStaffUsersUserIdEditRoute
  '/staff/staff-users/$userId/permissions': typeof authedStaffStaffUsersUserIdPermissionsRoute
  '/staff/staff-users/$userId/settings': typeof authedStaffStaffUsersUserIdSettingsRoute
  '/staff/tenant-users/details/$userId': typeof authedStaffTenantUsersDetailsUserIdRoute
  '/staff/tenants/$tenantId/activity': typeof authedStaffTenantsTenantIdActivityRoute
  '/staff/tenants/$tenantId/edit': typeof authedStaffTenantsTenantIdEditRoute
  '/staff/tenants/$tenantId/invitations': typeof authedStaffTenantsTenantIdInvitationsRoute
  '/staff/tenants/$tenantId/profiles': typeof authedStaffTenantsTenantIdProfilesRoute
  '/staff/tenants/$tenantId/usage': typeof authedStaffTenantsTenantIdUsageRoute
  '/staff/tenants/$tenantId/users': typeof authedStaffTenantsTenantIdUsersRoute
  '/tenant/posts/$postId/edit': typeof authedTenantPostsPostIdEditRoute
  '/staff/staff-users/$userId/': typeof authedStaffStaffUsersUserIdIndexRoute
  '/staff/tenant-users/details/$userId/$tab': typeof authedStaffTenantUserDetailsTabFallbackRoute
  '/staff/tenant-users/details/$userId/general': typeof authedStaffTenantUsersUserIdGeneralRoute
  '/staff/tenant-users/details/$userId/organizations': typeof authedStaffTenantUsersUserIdOrganizationsRoute
  '/staff/tenants/$tenantId/profiles/$profileId': typeof authedStaffTenantsTenantIdProfilesProfileIdRouteWithChildren
  '/staff/tenants/$tenantId/profiles/new': typeof authedStaffTenantsTenantIdProfilesNewRoute
  '/staff/tenants/$tenantId/users/$userId': typeof authedStaffTenantsTenantIdUsersUserIdRoute
  '/staff/tenants/$tenantId/users/invite': typeof authedStaffTenantsTenantIdUsersInviteRoute
  '/staff/tenants/$tenantId/profiles/$profileId/edit': typeof authedStaffTenantsTenantIdProfilesProfileIdEditRoute
  '/staff/tenants/$tenantId/profiles/$profileId/members': typeof authedStaffTenantsTenantIdProfilesProfileIdMembersRoute
  '/staff/tenants/$tenantId/profiles/$profileId/permissions': typeof authedStaffTenantsTenantIdProfilesProfileIdPermissionsRoute
  '/staff/tenants/$tenantId/profiles/$profileId/users': typeof authedStaffTenantsTenantIdProfilesProfileIdUsersRoute
  '/staff/tenants/$tenantId/users/$userId/edit': typeof authedStaffTenantsTenantIdUsersUserIdEditRoute
  '/staff/tenants/$tenantId/profiles/$profileId/': typeof authedStaffTenantsTenantIdProfilesProfileIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/accept-invitation': typeof acceptInvitationRoute
  '/field-validation': typeof fieldValidationRoute
  '/health': typeof healthRoute
  '/login': typeof loginRoute
  '/reset-password': typeof resetPasswordRoute
  '/signup': typeof signupRoute
  '/verify-email': typeof verifyEmailRoute
  '/staff': typeof authedStaffRoute
  '/tenant': typeof authedTenantRouteWithChildren
  '/staff/audit-logs': typeof authedStaffAuditLogsRoute
  '/staff/profiles': typeof authedStaffProfilesRoute
  '/staff/staff-users': typeof authedStaffStaffUsersRoute
  '/staff/tenants': typeof authedStaffTenantsRoute
  '/tenant/organizations': typeof authedTenantOrganizationsRoute
  '/staff/invitations': typeof authedStaffInvitationsIndexRoute
  '/staff/jobs': typeof authedStaffJobsQueueRoute
  '/tenant/account': typeof authedTenantAccountProfileRoute
  '/tenant/posts': typeof authedTenantPostsCalendarRoute
  '/tenant/settings': typeof authedTenantSettingsGeneralRoute
  '/staff/audit-logs/$logId': typeof authedStaffAuditLogsLogIdRoute
  '/staff/dashboard/activity': typeof authedStaffDashboardActivityRoute
  '/staff/dashboard/reports': typeof authedStaffDashboardReportsRoute
  '/staff/invitations/$invitationId': typeof authedStaffInvitationsInvitationIdRoute
  '/staff/invitations/new': typeof authedStaffInvitationsNewRoute
  '/staff/jobs/dead-letter': typeof authedStaffJobsDeadLetterRoute
  '/staff/jobs/system-jobs': typeof authedStaffJobsSystemJobsRoute
  '/staff/profiles/$profileId': typeof authedStaffProfilesProfileIdRoute
  '/staff/profiles/new': typeof authedStaffProfilesNewRoute
  '/staff/tenants/$tenantId': typeof authedStaffTenantsTenantIdRoute
  '/staff/tenants/new': typeof authedStaffTenantsNewRoute
  '/tenant/account/notifications': typeof authedTenantAccountNotificationsRoute
  '/tenant/account/security': typeof authedTenantAccountSecurityRoute
  '/tenant/posts/drafts': typeof authedTenantPostsDraftsRoute
  '/tenant/posts/history': typeof authedTenantPostsHistoryRoute
  '/tenant/posts/queue': typeof authedTenantPostsQueueRoute
  '/tenant/settings/billing': typeof authedTenantSettingsBillingRoute
  '/tenant/settings/integrations': typeof authedTenantSettingsIntegrationsRoute
  '/tenant/settings/members': typeof authedTenantSettingsMembersRoute
  '/tenant/settings/roles': typeof authedTenantSettingsRolesRoute
  '/tenant/settings/security': typeof authedTenantSettingsSecurityRoute
  '/tenant/settings/workspaces': typeof authedTenantSettingsWorkspacesRoute
  '/staff/dashboard': typeof authedStaffDashboardIndexRoute
  '/staff/profiles/$profileId/users': typeof authedStaffProfilesProfileIdUsersRoute
  '/staff/staff-users/$userId/activity': typeof authedStaffStaffUsersUserIdActivityRoute
  '/staff/staff-users/$userId/edit': typeof authedStaffStaffUsersUserIdEditRoute
  '/staff/staff-users/$userId/permissions': typeof authedStaffStaffUsersUserIdPermissionsRoute
  '/staff/staff-users/$userId/settings': typeof authedStaffStaffUsersUserIdSettingsRoute
  '/staff/tenant-users/details/$userId': typeof authedStaffTenantUsersDetailsUserIdRoute
  '/staff/tenants/$tenantId/activity': typeof authedStaffTenantsTenantIdActivityRoute
  '/staff/tenants/$tenantId/edit': typeof authedStaffTenantsTenantIdEditRoute
  '/staff/tenants/$tenantId/invitations': typeof authedStaffTenantsTenantIdInvitationsRoute
  '/staff/tenants/$tenantId/profiles': typeof authedStaffTenantsTenantIdProfilesRoute
  '/staff/tenants/$tenantId/usage': typeof authedStaffTenantsTenantIdUsageRoute
  '/staff/tenants/$tenantId/users': typeof authedStaffTenantsTenantIdUsersRoute
  '/tenant/posts/$postId/edit': typeof authedTenantPostsPostIdEditRoute
  '/staff/staff-users/$userId': typeof authedStaffStaffUsersUserIdIndexRoute
  '/staff/tenant-users/details/$userId/$tab': typeof authedStaffTenantUserDetailsTabFallbackRoute
  '/staff/tenant-users/details/$userId/general': typeof authedStaffTenantUsersUserIdGeneralRoute
  '/staff/tenant-users/details/$userId/organizations': typeof authedStaffTenantUsersUserIdOrganizationsRoute
  '/staff/tenants/$tenantId/profiles/new': typeof authedStaffTenantsTenantIdProfilesNewRoute
  '/staff/tenants/$tenantId/users/$userId': typeof authedStaffTenantsTenantIdUsersUserIdRoute
  '/staff/tenants/$tenantId/users/invite': typeof authedStaffTenantsTenantIdUsersInviteRoute
  '/staff/tenants/$tenantId/profiles/$profileId/edit': typeof authedStaffTenantsTenantIdProfilesProfileIdEditRoute
  '/staff/tenants/$tenantId/profiles/$profileId/members': typeof authedStaffTenantsTenantIdProfilesProfileIdMembersRoute
  '/staff/tenants/$tenantId/profiles/$profileId/permissions': typeof authedStaffTenantsTenantIdProfilesProfileIdPermissionsRoute
  '/staff/tenants/$tenantId/profiles/$profileId/users': typeof authedStaffTenantsTenantIdProfilesProfileIdUsersRoute
  '/staff/tenants/$tenantId/users/$userId/edit': typeof authedStaffTenantsTenantIdUsersUserIdEditRoute
  '/staff/tenants/$tenantId/profiles/$profileId': typeof authedStaffTenantsTenantIdProfilesProfileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/_authed-layout': typeof authedLayoutRouteWithChildren
  '/accept-invitation': typeof acceptInvitationRoute
  '/field-validation': typeof fieldValidationRoute
  '/health': typeof healthRoute
  '/login': typeof loginRoute
  '/reset-password': typeof resetPasswordRoute
  '/signup': typeof signupRoute
  '/verify-email': typeof verifyEmailRoute
  '/_authed-layout/staff': typeof authedStaffRoute
  '/_authed-layout/tenant': typeof authedTenantRouteWithChildren
  '/_authed-layout/staff/audit-logs': typeof authedStaffAuditLogsRoute
  '/_authed-layout/staff/dashboard': typeof authedStaffDashboardRouteWithChildren
  '/_authed-layout/staff/jobs': typeof authedStaffJobsRouteWithChildren
  '/_authed-layout/staff/profiles': typeof authedStaffProfilesRoute
  '/_authed-layout/staff/staff-users': typeof authedStaffStaffUsersRoute
  '/_authed-layout/staff/tenants': typeof authedStaffTenantsRoute
  '/_authed-layout/tenant/account': typeof authedTenantAccountRouteWithChildren
  '/_authed-layout/tenant/organizations': typeof authedTenantOrganizationsRoute
  '/_authed-layout/tenant/posts': typeof authedTenantPostsRouteWithChildren
  '/_authed-layout/tenant/settings': typeof authedTenantSettingsRouteWithChildren
  '/_authed-layout/staff/invitations': typeof authedStaffInvitationsIndexRoute
  '/_authed-layout/staff/jobs/': typeof authedStaffJobsQueueRoute
  '/_authed-layout/tenant/account/': typeof authedTenantAccountProfileRoute
  '/_authed-layout/tenant/posts/': typeof authedTenantPostsCalendarRoute
  '/_authed-layout/tenant/settings/': typeof authedTenantSettingsGeneralRoute
  '/_authed-layout/staff/audit-logs/$logId': typeof authedStaffAuditLogsLogIdRoute
  '/_authed-layout/staff/dashboard/activity': typeof authedStaffDashboardActivityRoute
  '/_authed-layout/staff/dashboard/reports': typeof authedStaffDashboardReportsRoute
  '/_authed-layout/staff/invitations/$invitationId': typeof authedStaffInvitationsInvitationIdRoute
  '/_authed-layout/staff/invitations/new': typeof authedStaffInvitationsNewRoute
  '/_authed-layout/staff/jobs/dead-letter': typeof authedStaffJobsDeadLetterRoute
  '/_authed-layout/staff/jobs/system-jobs': typeof authedStaffJobsSystemJobsRoute
  '/_authed-layout/staff/profiles/$profileId': typeof authedStaffProfilesProfileIdRoute
  '/_authed-layout/staff/profiles/new': typeof authedStaffProfilesNewRoute
  '/_authed-layout/staff/staff-users/$userId': typeof authedStaffStaffUsersUserIdRouteWithChildren
  '/_authed-layout/staff/tenants/$tenantId': typeof authedStaffTenantsTenantIdRoute
  '/_authed-layout/staff/tenants/new': typeof authedStaffTenantsNewRoute
  '/_authed-layout/tenant/account/notifications': typeof authedTenantAccountNotificationsRoute
  '/_authed-layout/tenant/account/security': typeof authedTenantAccountSecurityRoute
  '/_authed-layout/tenant/posts/drafts': typeof authedTenantPostsDraftsRoute
  '/_authed-layout/tenant/posts/history': typeof authedTenantPostsHistoryRoute
  '/_authed-layout/tenant/posts/queue': typeof authedTenantPostsQueueRoute
  '/_authed-layout/tenant/settings/billing': typeof authedTenantSettingsBillingRoute
  '/_authed-layout/tenant/settings/integrations': typeof authedTenantSettingsIntegrationsRoute
  '/_authed-layout/tenant/settings/members': typeof authedTenantSettingsMembersRoute
  '/_authed-layout/tenant/settings/roles': typeof authedTenantSettingsRolesRoute
  '/_authed-layout/tenant/settings/security': typeof authedTenantSettingsSecurityRoute
  '/_authed-layout/tenant/settings/workspaces': typeof authedTenantSettingsWorkspacesRoute
  '/_authed-layout/staff/dashboard/': typeof authedStaffDashboardIndexRoute
  '/_authed-layout/staff/profiles/$profileId/users': typeof authedStaffProfilesProfileIdUsersRoute
  '/_authed-layout/staff/staff-users/$userId/activity': typeof authedStaffStaffUsersUserIdActivityRoute
  '/_authed-layout/staff/staff-users/$userId/edit': typeof authedStaffStaffUsersUserIdEditRoute
  '/_authed-layout/staff/staff-users/$userId/permissions': typeof authedStaffStaffUsersUserIdPermissionsRoute
  '/_authed-layout/staff/staff-users/$userId/settings': typeof authedStaffStaffUsersUserIdSettingsRoute
  '/_authed-layout/staff/tenant-users/details/$userId': typeof authedStaffTenantUsersDetailsUserIdRoute
  '/_authed-layout/staff/tenants/$tenantId/activity': typeof authedStaffTenantsTenantIdActivityRoute
  '/_authed-layout/staff/tenants/$tenantId/edit': typeof authedStaffTenantsTenantIdEditRoute
  '/_authed-layout/staff/tenants/$tenantId/invitations': typeof authedStaffTenantsTenantIdInvitationsRoute
  '/_authed-layout/staff/tenants/$tenantId/profiles': typeof authedStaffTenantsTenantIdProfilesRoute
  '/_authed-layout/staff/tenants/$tenantId/usage': typeof authedStaffTenantsTenantIdUsageRoute
  '/_authed-layout/staff/tenants/$tenantId/users': typeof authedStaffTenantsTenantIdUsersRoute
  '/_authed-layout/tenant/posts/$postId/edit': typeof authedTenantPostsPostIdEditRoute
  '/_authed-layout/staff/staff-users/$userId/': typeof authedStaffStaffUsersUserIdIndexRoute
  '/_authed-layout/staff/tenant-users/details/$userId/$tab': typeof authedStaffTenantUserDetailsTabFallbackRoute
  '/_authed-layout/staff/tenant-users/details/$userId/general': typeof authedStaffTenantUsersUserIdGeneralRoute
  '/_authed-layout/staff/tenant-users/details/$userId/organizations': typeof authedStaffTenantUsersUserIdOrganizationsRoute
  '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId': typeof authedStaffTenantsTenantIdProfilesProfileIdRouteWithChildren
  '/_authed-layout/staff/tenants/$tenantId/profiles/new': typeof authedStaffTenantsTenantIdProfilesNewRoute
  '/_authed-layout/staff/tenants/$tenantId/users/$userId': typeof authedStaffTenantsTenantIdUsersUserIdRoute
  '/_authed-layout/staff/tenants/$tenantId/users/invite': typeof authedStaffTenantsTenantIdUsersInviteRoute
  '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/edit': typeof authedStaffTenantsTenantIdProfilesProfileIdEditRoute
  '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/members': typeof authedStaffTenantsTenantIdProfilesProfileIdMembersRoute
  '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/permissions': typeof authedStaffTenantsTenantIdProfilesProfileIdPermissionsRoute
  '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/users': typeof authedStaffTenantsTenantIdProfilesProfileIdUsersRoute
  '/_authed-layout/staff/tenants/$tenantId/users/$userId/edit': typeof authedStaffTenantsTenantIdUsersUserIdEditRoute
  '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/': typeof authedStaffTenantsTenantIdProfilesProfileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/field-validation'
    | '/health'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/staff'
    | '/tenant'
    | '/staff/audit-logs'
    | '/staff/dashboard'
    | '/staff/jobs'
    | '/staff/profiles'
    | '/staff/staff-users'
    | '/staff/tenants'
    | '/tenant/account'
    | '/tenant/organizations'
    | '/tenant/posts'
    | '/tenant/settings'
    | '/staff/invitations'
    | '/staff/jobs/'
    | '/tenant/account/'
    | '/tenant/posts/'
    | '/tenant/settings/'
    | '/staff/audit-logs/$logId'
    | '/staff/dashboard/activity'
    | '/staff/dashboard/reports'
    | '/staff/invitations/$invitationId'
    | '/staff/invitations/new'
    | '/staff/jobs/dead-letter'
    | '/staff/jobs/system-jobs'
    | '/staff/profiles/$profileId'
    | '/staff/profiles/new'
    | '/staff/staff-users/$userId'
    | '/staff/tenants/$tenantId'
    | '/staff/tenants/new'
    | '/tenant/account/notifications'
    | '/tenant/account/security'
    | '/tenant/posts/drafts'
    | '/tenant/posts/history'
    | '/tenant/posts/queue'
    | '/tenant/settings/billing'
    | '/tenant/settings/integrations'
    | '/tenant/settings/members'
    | '/tenant/settings/roles'
    | '/tenant/settings/security'
    | '/tenant/settings/workspaces'
    | '/staff/dashboard/'
    | '/staff/profiles/$profileId/users'
    | '/staff/staff-users/$userId/activity'
    | '/staff/staff-users/$userId/edit'
    | '/staff/staff-users/$userId/permissions'
    | '/staff/staff-users/$userId/settings'
    | '/staff/tenant-users/details/$userId'
    | '/staff/tenants/$tenantId/activity'
    | '/staff/tenants/$tenantId/edit'
    | '/staff/tenants/$tenantId/invitations'
    | '/staff/tenants/$tenantId/profiles'
    | '/staff/tenants/$tenantId/usage'
    | '/staff/tenants/$tenantId/users'
    | '/tenant/posts/$postId/edit'
    | '/staff/staff-users/$userId/'
    | '/staff/tenant-users/details/$userId/$tab'
    | '/staff/tenant-users/details/$userId/general'
    | '/staff/tenant-users/details/$userId/organizations'
    | '/staff/tenants/$tenantId/profiles/$profileId'
    | '/staff/tenants/$tenantId/profiles/new'
    | '/staff/tenants/$tenantId/users/$userId'
    | '/staff/tenants/$tenantId/users/invite'
    | '/staff/tenants/$tenantId/profiles/$profileId/edit'
    | '/staff/tenants/$tenantId/profiles/$profileId/members'
    | '/staff/tenants/$tenantId/profiles/$profileId/permissions'
    | '/staff/tenants/$tenantId/profiles/$profileId/users'
    | '/staff/tenants/$tenantId/users/$userId/edit'
    | '/staff/tenants/$tenantId/profiles/$profileId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/field-validation'
    | '/health'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/staff'
    | '/tenant'
    | '/staff/audit-logs'
    | '/staff/profiles'
    | '/staff/staff-users'
    | '/staff/tenants'
    | '/tenant/organizations'
    | '/staff/invitations'
    | '/staff/jobs'
    | '/tenant/account'
    | '/tenant/posts'
    | '/tenant/settings'
    | '/staff/audit-logs/$logId'
    | '/staff/dashboard/activity'
    | '/staff/dashboard/reports'
    | '/staff/invitations/$invitationId'
    | '/staff/invitations/new'
    | '/staff/jobs/dead-letter'
    | '/staff/jobs/system-jobs'
    | '/staff/profiles/$profileId'
    | '/staff/profiles/new'
    | '/staff/tenants/$tenantId'
    | '/staff/tenants/new'
    | '/tenant/account/notifications'
    | '/tenant/account/security'
    | '/tenant/posts/drafts'
    | '/tenant/posts/history'
    | '/tenant/posts/queue'
    | '/tenant/settings/billing'
    | '/tenant/settings/integrations'
    | '/tenant/settings/members'
    | '/tenant/settings/roles'
    | '/tenant/settings/security'
    | '/tenant/settings/workspaces'
    | '/staff/dashboard'
    | '/staff/profiles/$profileId/users'
    | '/staff/staff-users/$userId/activity'
    | '/staff/staff-users/$userId/edit'
    | '/staff/staff-users/$userId/permissions'
    | '/staff/staff-users/$userId/settings'
    | '/staff/tenant-users/details/$userId'
    | '/staff/tenants/$tenantId/activity'
    | '/staff/tenants/$tenantId/edit'
    | '/staff/tenants/$tenantId/invitations'
    | '/staff/tenants/$tenantId/profiles'
    | '/staff/tenants/$tenantId/usage'
    | '/staff/tenants/$tenantId/users'
    | '/tenant/posts/$postId/edit'
    | '/staff/staff-users/$userId'
    | '/staff/tenant-users/details/$userId/$tab'
    | '/staff/tenant-users/details/$userId/general'
    | '/staff/tenant-users/details/$userId/organizations'
    | '/staff/tenants/$tenantId/profiles/new'
    | '/staff/tenants/$tenantId/users/$userId'
    | '/staff/tenants/$tenantId/users/invite'
    | '/staff/tenants/$tenantId/profiles/$profileId/edit'
    | '/staff/tenants/$tenantId/profiles/$profileId/members'
    | '/staff/tenants/$tenantId/profiles/$profileId/permissions'
    | '/staff/tenants/$tenantId/profiles/$profileId/users'
    | '/staff/tenants/$tenantId/users/$userId/edit'
    | '/staff/tenants/$tenantId/profiles/$profileId'
  id:
    | '__root__'
    | '/'
    | '/_authed-layout'
    | '/accept-invitation'
    | '/field-validation'
    | '/health'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_authed-layout/staff'
    | '/_authed-layout/tenant'
    | '/_authed-layout/staff/audit-logs'
    | '/_authed-layout/staff/dashboard'
    | '/_authed-layout/staff/jobs'
    | '/_authed-layout/staff/profiles'
    | '/_authed-layout/staff/staff-users'
    | '/_authed-layout/staff/tenants'
    | '/_authed-layout/tenant/account'
    | '/_authed-layout/tenant/organizations'
    | '/_authed-layout/tenant/posts'
    | '/_authed-layout/tenant/settings'
    | '/_authed-layout/staff/invitations'
    | '/_authed-layout/staff/jobs/'
    | '/_authed-layout/tenant/account/'
    | '/_authed-layout/tenant/posts/'
    | '/_authed-layout/tenant/settings/'
    | '/_authed-layout/staff/audit-logs/$logId'
    | '/_authed-layout/staff/dashboard/activity'
    | '/_authed-layout/staff/dashboard/reports'
    | '/_authed-layout/staff/invitations/$invitationId'
    | '/_authed-layout/staff/invitations/new'
    | '/_authed-layout/staff/jobs/dead-letter'
    | '/_authed-layout/staff/jobs/system-jobs'
    | '/_authed-layout/staff/profiles/$profileId'
    | '/_authed-layout/staff/profiles/new'
    | '/_authed-layout/staff/staff-users/$userId'
    | '/_authed-layout/staff/tenants/$tenantId'
    | '/_authed-layout/staff/tenants/new'
    | '/_authed-layout/tenant/account/notifications'
    | '/_authed-layout/tenant/account/security'
    | '/_authed-layout/tenant/posts/drafts'
    | '/_authed-layout/tenant/posts/history'
    | '/_authed-layout/tenant/posts/queue'
    | '/_authed-layout/tenant/settings/billing'
    | '/_authed-layout/tenant/settings/integrations'
    | '/_authed-layout/tenant/settings/members'
    | '/_authed-layout/tenant/settings/roles'
    | '/_authed-layout/tenant/settings/security'
    | '/_authed-layout/tenant/settings/workspaces'
    | '/_authed-layout/staff/dashboard/'
    | '/_authed-layout/staff/profiles/$profileId/users'
    | '/_authed-layout/staff/staff-users/$userId/activity'
    | '/_authed-layout/staff/staff-users/$userId/edit'
    | '/_authed-layout/staff/staff-users/$userId/permissions'
    | '/_authed-layout/staff/staff-users/$userId/settings'
    | '/_authed-layout/staff/tenant-users/details/$userId'
    | '/_authed-layout/staff/tenants/$tenantId/activity'
    | '/_authed-layout/staff/tenants/$tenantId/edit'
    | '/_authed-layout/staff/tenants/$tenantId/invitations'
    | '/_authed-layout/staff/tenants/$tenantId/profiles'
    | '/_authed-layout/staff/tenants/$tenantId/usage'
    | '/_authed-layout/staff/tenants/$tenantId/users'
    | '/_authed-layout/tenant/posts/$postId/edit'
    | '/_authed-layout/staff/staff-users/$userId/'
    | '/_authed-layout/staff/tenant-users/details/$userId/$tab'
    | '/_authed-layout/staff/tenant-users/details/$userId/general'
    | '/_authed-layout/staff/tenant-users/details/$userId/organizations'
    | '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId'
    | '/_authed-layout/staff/tenants/$tenantId/profiles/new'
    | '/_authed-layout/staff/tenants/$tenantId/users/$userId'
    | '/_authed-layout/staff/tenants/$tenantId/users/invite'
    | '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/edit'
    | '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/members'
    | '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/permissions'
    | '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/users'
    | '/_authed-layout/staff/tenants/$tenantId/users/$userId/edit'
    | '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  authedLayoutRoute: typeof authedLayoutRouteWithChildren
  acceptInvitationRoute: typeof acceptInvitationRoute
  fieldValidationRoute: typeof fieldValidationRoute
  healthRoute: typeof healthRoute
  loginRoute: typeof loginRoute
  resetPasswordRoute: typeof resetPasswordRoute
  signupRoute: typeof signupRoute
  verifyEmailRoute: typeof verifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed-layout': {
      id: '/_authed-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof authedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof acceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-validation': {
      id: '/field-validation'
      path: '/field-validation'
      fullPath: '/field-validation'
      preLoaderRoute: typeof fieldValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof healthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof resetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof signupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof verifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed-layout/staff': {
      id: '/_authed-layout/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof authedStaffRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/tenant': {
      id: '/_authed-layout/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof authedTenantRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/audit-logs': {
      id: '/_authed-layout/staff/audit-logs'
      path: '/staff/audit-logs'
      fullPath: '/staff/audit-logs'
      preLoaderRoute: typeof authedStaffAuditLogsRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/dashboard': {
      id: '/_authed-layout/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof authedStaffDashboardRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/invitations': {
      id: '/_authed-layout/staff/invitations'
      path: '/staff/invitations'
      fullPath: '/staff/invitations'
      preLoaderRoute: typeof authedStaffInvitationsIndexRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/jobs': {
      id: '/_authed-layout/staff/jobs'
      path: '/staff/jobs'
      fullPath: '/staff/jobs'
      preLoaderRoute: typeof authedStaffJobsRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/profiles': {
      id: '/_authed-layout/staff/profiles'
      path: '/staff/profiles'
      fullPath: '/staff/profiles'
      preLoaderRoute: typeof authedStaffProfilesRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/staff-users': {
      id: '/_authed-layout/staff/staff-users'
      path: '/staff/staff-users'
      fullPath: '/staff/staff-users'
      preLoaderRoute: typeof authedStaffStaffUsersRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants': {
      id: '/_authed-layout/staff/tenants'
      path: '/staff/tenants'
      fullPath: '/staff/tenants'
      preLoaderRoute: typeof authedStaffTenantsRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/tenant/account': {
      id: '/_authed-layout/tenant/account'
      path: '/account'
      fullPath: '/tenant/account'
      preLoaderRoute: typeof authedTenantAccountRouteImport
      parentRoute: typeof authedTenantRoute
    }
    '/_authed-layout/tenant/organizations': {
      id: '/_authed-layout/tenant/organizations'
      path: '/organizations'
      fullPath: '/tenant/organizations'
      preLoaderRoute: typeof authedTenantOrganizationsRouteImport
      parentRoute: typeof authedTenantRoute
    }
    '/_authed-layout/tenant/posts': {
      id: '/_authed-layout/tenant/posts'
      path: '/posts'
      fullPath: '/tenant/posts'
      preLoaderRoute: typeof authedTenantPostsRouteImport
      parentRoute: typeof authedTenantRoute
    }
    '/_authed-layout/tenant/settings': {
      id: '/_authed-layout/tenant/settings'
      path: '/settings'
      fullPath: '/tenant/settings'
      preLoaderRoute: typeof authedTenantSettingsRouteImport
      parentRoute: typeof authedTenantRoute
    }
    '/_authed-layout/staff/audit-logs/$logId': {
      id: '/_authed-layout/staff/audit-logs/$logId'
      path: '/staff/audit-logs/$logId'
      fullPath: '/staff/audit-logs/$logId'
      preLoaderRoute: typeof authedStaffAuditLogsLogIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/dashboard/': {
      id: '/_authed-layout/staff/dashboard/'
      path: '/'
      fullPath: '/staff/dashboard/'
      preLoaderRoute: typeof authedStaffDashboardIndexRouteImport
      parentRoute: typeof authedStaffDashboardRoute
    }
    '/_authed-layout/staff/dashboard/activity': {
      id: '/_authed-layout/staff/dashboard/activity'
      path: '/activity'
      fullPath: '/staff/dashboard/activity'
      preLoaderRoute: typeof authedStaffDashboardActivityRouteImport
      parentRoute: typeof authedStaffDashboardRoute
    }
    '/_authed-layout/staff/dashboard/reports': {
      id: '/_authed-layout/staff/dashboard/reports'
      path: '/reports'
      fullPath: '/staff/dashboard/reports'
      preLoaderRoute: typeof authedStaffDashboardReportsRouteImport
      parentRoute: typeof authedStaffDashboardRoute
    }
    '/_authed-layout/staff/invitations/$invitationId': {
      id: '/_authed-layout/staff/invitations/$invitationId'
      path: '/staff/invitations/$invitationId'
      fullPath: '/staff/invitations/$invitationId'
      preLoaderRoute: typeof authedStaffInvitationsInvitationIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/invitations/new': {
      id: '/_authed-layout/staff/invitations/new'
      path: '/staff/invitations/new'
      fullPath: '/staff/invitations/new'
      preLoaderRoute: typeof authedStaffInvitationsNewRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/jobs/': {
      id: '/_authed-layout/staff/jobs/'
      path: '/'
      fullPath: '/staff/jobs/'
      preLoaderRoute: typeof authedStaffJobsQueueRouteImport
      parentRoute: typeof authedStaffJobsRoute
    }
    '/_authed-layout/staff/jobs/dead-letter': {
      id: '/_authed-layout/staff/jobs/dead-letter'
      path: '/dead-letter'
      fullPath: '/staff/jobs/dead-letter'
      preLoaderRoute: typeof authedStaffJobsDeadLetterRouteImport
      parentRoute: typeof authedStaffJobsRoute
    }
    '/_authed-layout/staff/jobs/system-jobs': {
      id: '/_authed-layout/staff/jobs/system-jobs'
      path: '/system-jobs'
      fullPath: '/staff/jobs/system-jobs'
      preLoaderRoute: typeof authedStaffJobsSystemJobsRouteImport
      parentRoute: typeof authedStaffJobsRoute
    }
    '/_authed-layout/staff/profiles/$profileId': {
      id: '/_authed-layout/staff/profiles/$profileId'
      path: '/staff/profiles/$profileId'
      fullPath: '/staff/profiles/$profileId'
      preLoaderRoute: typeof authedStaffProfilesProfileIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/profiles/new': {
      id: '/_authed-layout/staff/profiles/new'
      path: '/staff/profiles/new'
      fullPath: '/staff/profiles/new'
      preLoaderRoute: typeof authedStaffProfilesNewRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/staff-users/$userId': {
      id: '/_authed-layout/staff/staff-users/$userId'
      path: '/staff/staff-users/$userId'
      fullPath: '/staff/staff-users/$userId'
      preLoaderRoute: typeof authedStaffStaffUsersUserIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId': {
      id: '/_authed-layout/staff/tenants/$tenantId'
      path: '/staff/tenants/$tenantId'
      fullPath: '/staff/tenants/$tenantId'
      preLoaderRoute: typeof authedStaffTenantsTenantIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/new': {
      id: '/_authed-layout/staff/tenants/new'
      path: '/staff/tenants/new'
      fullPath: '/staff/tenants/new'
      preLoaderRoute: typeof authedStaffTenantsNewRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/tenant/account/': {
      id: '/_authed-layout/tenant/account/'
      path: '/'
      fullPath: '/tenant/account/'
      preLoaderRoute: typeof authedTenantAccountProfileRouteImport
      parentRoute: typeof authedTenantAccountRoute
    }
    '/_authed-layout/tenant/account/notifications': {
      id: '/_authed-layout/tenant/account/notifications'
      path: '/notifications'
      fullPath: '/tenant/account/notifications'
      preLoaderRoute: typeof authedTenantAccountNotificationsRouteImport
      parentRoute: typeof authedTenantAccountRoute
    }
    '/_authed-layout/tenant/account/security': {
      id: '/_authed-layout/tenant/account/security'
      path: '/security'
      fullPath: '/tenant/account/security'
      preLoaderRoute: typeof authedTenantAccountSecurityRouteImport
      parentRoute: typeof authedTenantAccountRoute
    }
    '/_authed-layout/tenant/posts/': {
      id: '/_authed-layout/tenant/posts/'
      path: '/'
      fullPath: '/tenant/posts/'
      preLoaderRoute: typeof authedTenantPostsCalendarRouteImport
      parentRoute: typeof authedTenantPostsRoute
    }
    '/_authed-layout/tenant/posts/drafts': {
      id: '/_authed-layout/tenant/posts/drafts'
      path: '/drafts'
      fullPath: '/tenant/posts/drafts'
      preLoaderRoute: typeof authedTenantPostsDraftsRouteImport
      parentRoute: typeof authedTenantPostsRoute
    }
    '/_authed-layout/tenant/posts/history': {
      id: '/_authed-layout/tenant/posts/history'
      path: '/history'
      fullPath: '/tenant/posts/history'
      preLoaderRoute: typeof authedTenantPostsHistoryRouteImport
      parentRoute: typeof authedTenantPostsRoute
    }
    '/_authed-layout/tenant/posts/queue': {
      id: '/_authed-layout/tenant/posts/queue'
      path: '/queue'
      fullPath: '/tenant/posts/queue'
      preLoaderRoute: typeof authedTenantPostsQueueRouteImport
      parentRoute: typeof authedTenantPostsRoute
    }
    '/_authed-layout/tenant/settings/': {
      id: '/_authed-layout/tenant/settings/'
      path: '/'
      fullPath: '/tenant/settings/'
      preLoaderRoute: typeof authedTenantSettingsGeneralRouteImport
      parentRoute: typeof authedTenantSettingsRoute
    }
    '/_authed-layout/tenant/settings/billing': {
      id: '/_authed-layout/tenant/settings/billing'
      path: '/billing'
      fullPath: '/tenant/settings/billing'
      preLoaderRoute: typeof authedTenantSettingsBillingRouteImport
      parentRoute: typeof authedTenantSettingsRoute
    }
    '/_authed-layout/tenant/settings/integrations': {
      id: '/_authed-layout/tenant/settings/integrations'
      path: '/integrations'
      fullPath: '/tenant/settings/integrations'
      preLoaderRoute: typeof authedTenantSettingsIntegrationsRouteImport
      parentRoute: typeof authedTenantSettingsRoute
    }
    '/_authed-layout/tenant/settings/members': {
      id: '/_authed-layout/tenant/settings/members'
      path: '/members'
      fullPath: '/tenant/settings/members'
      preLoaderRoute: typeof authedTenantSettingsMembersRouteImport
      parentRoute: typeof authedTenantSettingsRoute
    }
    '/_authed-layout/tenant/settings/roles': {
      id: '/_authed-layout/tenant/settings/roles'
      path: '/roles'
      fullPath: '/tenant/settings/roles'
      preLoaderRoute: typeof authedTenantSettingsRolesRouteImport
      parentRoute: typeof authedTenantSettingsRoute
    }
    '/_authed-layout/tenant/settings/security': {
      id: '/_authed-layout/tenant/settings/security'
      path: '/security'
      fullPath: '/tenant/settings/security'
      preLoaderRoute: typeof authedTenantSettingsSecurityRouteImport
      parentRoute: typeof authedTenantSettingsRoute
    }
    '/_authed-layout/tenant/settings/workspaces': {
      id: '/_authed-layout/tenant/settings/workspaces'
      path: '/workspaces'
      fullPath: '/tenant/settings/workspaces'
      preLoaderRoute: typeof authedTenantSettingsWorkspacesRouteImport
      parentRoute: typeof authedTenantSettingsRoute
    }
    '/_authed-layout/staff/profiles/$profileId/users': {
      id: '/_authed-layout/staff/profiles/$profileId/users'
      path: '/staff/profiles/$profileId/users'
      fullPath: '/staff/profiles/$profileId/users'
      preLoaderRoute: typeof authedStaffProfilesProfileIdUsersRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/staff-users/$userId/': {
      id: '/_authed-layout/staff/staff-users/$userId/'
      path: '/'
      fullPath: '/staff/staff-users/$userId/'
      preLoaderRoute: typeof authedStaffStaffUsersUserIdIndexRouteImport
      parentRoute: typeof authedStaffStaffUsersUserIdRoute
    }
    '/_authed-layout/staff/staff-users/$userId/activity': {
      id: '/_authed-layout/staff/staff-users/$userId/activity'
      path: '/activity'
      fullPath: '/staff/staff-users/$userId/activity'
      preLoaderRoute: typeof authedStaffStaffUsersUserIdActivityRouteImport
      parentRoute: typeof authedStaffStaffUsersUserIdRoute
    }
    '/_authed-layout/staff/staff-users/$userId/edit': {
      id: '/_authed-layout/staff/staff-users/$userId/edit'
      path: '/staff/staff-users/$userId/edit'
      fullPath: '/staff/staff-users/$userId/edit'
      preLoaderRoute: typeof authedStaffStaffUsersUserIdEditRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/staff-users/$userId/permissions': {
      id: '/_authed-layout/staff/staff-users/$userId/permissions'
      path: '/permissions'
      fullPath: '/staff/staff-users/$userId/permissions'
      preLoaderRoute: typeof authedStaffStaffUsersUserIdPermissionsRouteImport
      parentRoute: typeof authedStaffStaffUsersUserIdRoute
    }
    '/_authed-layout/staff/staff-users/$userId/settings': {
      id: '/_authed-layout/staff/staff-users/$userId/settings'
      path: '/settings'
      fullPath: '/staff/staff-users/$userId/settings'
      preLoaderRoute: typeof authedStaffStaffUsersUserIdSettingsRouteImport
      parentRoute: typeof authedStaffStaffUsersUserIdRoute
    }
    '/_authed-layout/staff/tenant-users/details/$userId': {
      id: '/_authed-layout/staff/tenant-users/details/$userId'
      path: '/staff/tenant-users/details/$userId'
      fullPath: '/staff/tenant-users/details/$userId'
      preLoaderRoute: typeof authedStaffTenantUsersDetailsUserIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/activity': {
      id: '/_authed-layout/staff/tenants/$tenantId/activity'
      path: '/staff/tenants/$tenantId/activity'
      fullPath: '/staff/tenants/$tenantId/activity'
      preLoaderRoute: typeof authedStaffTenantsTenantIdActivityRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/edit': {
      id: '/_authed-layout/staff/tenants/$tenantId/edit'
      path: '/staff/tenants/$tenantId/edit'
      fullPath: '/staff/tenants/$tenantId/edit'
      preLoaderRoute: typeof authedStaffTenantsTenantIdEditRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/invitations': {
      id: '/_authed-layout/staff/tenants/$tenantId/invitations'
      path: '/staff/tenants/$tenantId/invitations'
      fullPath: '/staff/tenants/$tenantId/invitations'
      preLoaderRoute: typeof authedStaffTenantsTenantIdInvitationsRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/profiles': {
      id: '/_authed-layout/staff/tenants/$tenantId/profiles'
      path: '/staff/tenants/$tenantId/profiles'
      fullPath: '/staff/tenants/$tenantId/profiles'
      preLoaderRoute: typeof authedStaffTenantsTenantIdProfilesRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/usage': {
      id: '/_authed-layout/staff/tenants/$tenantId/usage'
      path: '/staff/tenants/$tenantId/usage'
      fullPath: '/staff/tenants/$tenantId/usage'
      preLoaderRoute: typeof authedStaffTenantsTenantIdUsageRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/users': {
      id: '/_authed-layout/staff/tenants/$tenantId/users'
      path: '/staff/tenants/$tenantId/users'
      fullPath: '/staff/tenants/$tenantId/users'
      preLoaderRoute: typeof authedStaffTenantsTenantIdUsersRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/tenant/posts/$postId/edit': {
      id: '/_authed-layout/tenant/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/tenant/posts/$postId/edit'
      preLoaderRoute: typeof authedTenantPostsPostIdEditRouteImport
      parentRoute: typeof authedTenantRoute
    }
    '/_authed-layout/staff/tenant-users/details/$userId/$tab': {
      id: '/_authed-layout/staff/tenant-users/details/$userId/$tab'
      path: '/staff/tenant-users/details/$userId/$tab'
      fullPath: '/staff/tenant-users/details/$userId/$tab'
      preLoaderRoute: typeof authedStaffTenantUserDetailsTabFallbackRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenant-users/details/$userId/general': {
      id: '/_authed-layout/staff/tenant-users/details/$userId/general'
      path: '/staff/tenant-users/details/$userId/general'
      fullPath: '/staff/tenant-users/details/$userId/general'
      preLoaderRoute: typeof authedStaffTenantUsersUserIdGeneralRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenant-users/details/$userId/organizations': {
      id: '/_authed-layout/staff/tenant-users/details/$userId/organizations'
      path: '/staff/tenant-users/details/$userId/organizations'
      fullPath: '/staff/tenant-users/details/$userId/organizations'
      preLoaderRoute: typeof authedStaffTenantUsersUserIdOrganizationsRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId': {
      id: '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId'
      path: '/staff/tenants/$tenantId/profiles/$profileId'
      fullPath: '/staff/tenants/$tenantId/profiles/$profileId'
      preLoaderRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/profiles/new': {
      id: '/_authed-layout/staff/tenants/$tenantId/profiles/new'
      path: '/staff/tenants/$tenantId/profiles/new'
      fullPath: '/staff/tenants/$tenantId/profiles/new'
      preLoaderRoute: typeof authedStaffTenantsTenantIdProfilesNewRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/users/$userId': {
      id: '/_authed-layout/staff/tenants/$tenantId/users/$userId'
      path: '/staff/tenants/$tenantId/users/$userId'
      fullPath: '/staff/tenants/$tenantId/users/$userId'
      preLoaderRoute: typeof authedStaffTenantsTenantIdUsersUserIdRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/users/invite': {
      id: '/_authed-layout/staff/tenants/$tenantId/users/invite'
      path: '/staff/tenants/$tenantId/users/invite'
      fullPath: '/staff/tenants/$tenantId/users/invite'
      preLoaderRoute: typeof authedStaffTenantsTenantIdUsersInviteRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/': {
      id: '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/'
      path: '/'
      fullPath: '/staff/tenants/$tenantId/profiles/$profileId/'
      preLoaderRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdIndexRouteImport
      parentRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/edit': {
      id: '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/edit'
      path: '/staff/tenants/$tenantId/profiles/$profileId/edit'
      fullPath: '/staff/tenants/$tenantId/profiles/$profileId/edit'
      preLoaderRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdEditRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/members': {
      id: '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/members'
      path: '/members'
      fullPath: '/staff/tenants/$tenantId/profiles/$profileId/members'
      preLoaderRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdMembersRouteImport
      parentRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/permissions': {
      id: '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/permissions'
      path: '/permissions'
      fullPath: '/staff/tenants/$tenantId/profiles/$profileId/permissions'
      preLoaderRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdPermissionsRouteImport
      parentRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/users': {
      id: '/_authed-layout/staff/tenants/$tenantId/profiles/$profileId/users'
      path: '/staff/tenants/$tenantId/profiles/$profileId/users'
      fullPath: '/staff/tenants/$tenantId/profiles/$profileId/users'
      preLoaderRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdUsersRouteImport
      parentRoute: typeof authedLayoutRoute
    }
    '/_authed-layout/staff/tenants/$tenantId/users/$userId/edit': {
      id: '/_authed-layout/staff/tenants/$tenantId/users/$userId/edit'
      path: '/staff/tenants/$tenantId/users/$userId/edit'
      fullPath: '/staff/tenants/$tenantId/users/$userId/edit'
      preLoaderRoute: typeof authedStaffTenantsTenantIdUsersUserIdEditRouteImport
      parentRoute: typeof authedLayoutRoute
    }
  }
}

interface authedTenantAccountRouteChildren {
  authedTenantAccountProfileRoute: typeof authedTenantAccountProfileRoute
  authedTenantAccountNotificationsRoute: typeof authedTenantAccountNotificationsRoute
  authedTenantAccountSecurityRoute: typeof authedTenantAccountSecurityRoute
}

const authedTenantAccountRouteChildren: authedTenantAccountRouteChildren = {
  authedTenantAccountProfileRoute: authedTenantAccountProfileRoute,
  authedTenantAccountNotificationsRoute: authedTenantAccountNotificationsRoute,
  authedTenantAccountSecurityRoute: authedTenantAccountSecurityRoute,
}

const authedTenantAccountRouteWithChildren =
  authedTenantAccountRoute._addFileChildren(authedTenantAccountRouteChildren)

interface authedTenantPostsRouteChildren {
  authedTenantPostsCalendarRoute: typeof authedTenantPostsCalendarRoute
  authedTenantPostsDraftsRoute: typeof authedTenantPostsDraftsRoute
  authedTenantPostsHistoryRoute: typeof authedTenantPostsHistoryRoute
  authedTenantPostsQueueRoute: typeof authedTenantPostsQueueRoute
}

const authedTenantPostsRouteChildren: authedTenantPostsRouteChildren = {
  authedTenantPostsCalendarRoute: authedTenantPostsCalendarRoute,
  authedTenantPostsDraftsRoute: authedTenantPostsDraftsRoute,
  authedTenantPostsHistoryRoute: authedTenantPostsHistoryRoute,
  authedTenantPostsQueueRoute: authedTenantPostsQueueRoute,
}

const authedTenantPostsRouteWithChildren =
  authedTenantPostsRoute._addFileChildren(authedTenantPostsRouteChildren)

interface authedTenantSettingsRouteChildren {
  authedTenantSettingsGeneralRoute: typeof authedTenantSettingsGeneralRoute
  authedTenantSettingsBillingRoute: typeof authedTenantSettingsBillingRoute
  authedTenantSettingsIntegrationsRoute: typeof authedTenantSettingsIntegrationsRoute
  authedTenantSettingsMembersRoute: typeof authedTenantSettingsMembersRoute
  authedTenantSettingsRolesRoute: typeof authedTenantSettingsRolesRoute
  authedTenantSettingsSecurityRoute: typeof authedTenantSettingsSecurityRoute
  authedTenantSettingsWorkspacesRoute: typeof authedTenantSettingsWorkspacesRoute
}

const authedTenantSettingsRouteChildren: authedTenantSettingsRouteChildren = {
  authedTenantSettingsGeneralRoute: authedTenantSettingsGeneralRoute,
  authedTenantSettingsBillingRoute: authedTenantSettingsBillingRoute,
  authedTenantSettingsIntegrationsRoute: authedTenantSettingsIntegrationsRoute,
  authedTenantSettingsMembersRoute: authedTenantSettingsMembersRoute,
  authedTenantSettingsRolesRoute: authedTenantSettingsRolesRoute,
  authedTenantSettingsSecurityRoute: authedTenantSettingsSecurityRoute,
  authedTenantSettingsWorkspacesRoute: authedTenantSettingsWorkspacesRoute,
}

const authedTenantSettingsRouteWithChildren =
  authedTenantSettingsRoute._addFileChildren(authedTenantSettingsRouteChildren)

interface authedTenantRouteChildren {
  authedTenantAccountRoute: typeof authedTenantAccountRouteWithChildren
  authedTenantOrganizationsRoute: typeof authedTenantOrganizationsRoute
  authedTenantPostsRoute: typeof authedTenantPostsRouteWithChildren
  authedTenantSettingsRoute: typeof authedTenantSettingsRouteWithChildren
  authedTenantPostsPostIdEditRoute: typeof authedTenantPostsPostIdEditRoute
}

const authedTenantRouteChildren: authedTenantRouteChildren = {
  authedTenantAccountRoute: authedTenantAccountRouteWithChildren,
  authedTenantOrganizationsRoute: authedTenantOrganizationsRoute,
  authedTenantPostsRoute: authedTenantPostsRouteWithChildren,
  authedTenantSettingsRoute: authedTenantSettingsRouteWithChildren,
  authedTenantPostsPostIdEditRoute: authedTenantPostsPostIdEditRoute,
}

const authedTenantRouteWithChildren = authedTenantRoute._addFileChildren(
  authedTenantRouteChildren,
)

interface authedStaffDashboardRouteChildren {
  authedStaffDashboardActivityRoute: typeof authedStaffDashboardActivityRoute
  authedStaffDashboardReportsRoute: typeof authedStaffDashboardReportsRoute
  authedStaffDashboardIndexRoute: typeof authedStaffDashboardIndexRoute
}

const authedStaffDashboardRouteChildren: authedStaffDashboardRouteChildren = {
  authedStaffDashboardActivityRoute: authedStaffDashboardActivityRoute,
  authedStaffDashboardReportsRoute: authedStaffDashboardReportsRoute,
  authedStaffDashboardIndexRoute: authedStaffDashboardIndexRoute,
}

const authedStaffDashboardRouteWithChildren =
  authedStaffDashboardRoute._addFileChildren(authedStaffDashboardRouteChildren)

interface authedStaffJobsRouteChildren {
  authedStaffJobsQueueRoute: typeof authedStaffJobsQueueRoute
  authedStaffJobsDeadLetterRoute: typeof authedStaffJobsDeadLetterRoute
  authedStaffJobsSystemJobsRoute: typeof authedStaffJobsSystemJobsRoute
}

const authedStaffJobsRouteChildren: authedStaffJobsRouteChildren = {
  authedStaffJobsQueueRoute: authedStaffJobsQueueRoute,
  authedStaffJobsDeadLetterRoute: authedStaffJobsDeadLetterRoute,
  authedStaffJobsSystemJobsRoute: authedStaffJobsSystemJobsRoute,
}

const authedStaffJobsRouteWithChildren = authedStaffJobsRoute._addFileChildren(
  authedStaffJobsRouteChildren,
)

interface authedStaffStaffUsersUserIdRouteChildren {
  authedStaffStaffUsersUserIdActivityRoute: typeof authedStaffStaffUsersUserIdActivityRoute
  authedStaffStaffUsersUserIdPermissionsRoute: typeof authedStaffStaffUsersUserIdPermissionsRoute
  authedStaffStaffUsersUserIdSettingsRoute: typeof authedStaffStaffUsersUserIdSettingsRoute
  authedStaffStaffUsersUserIdIndexRoute: typeof authedStaffStaffUsersUserIdIndexRoute
}

const authedStaffStaffUsersUserIdRouteChildren: authedStaffStaffUsersUserIdRouteChildren =
  {
    authedStaffStaffUsersUserIdActivityRoute:
      authedStaffStaffUsersUserIdActivityRoute,
    authedStaffStaffUsersUserIdPermissionsRoute:
      authedStaffStaffUsersUserIdPermissionsRoute,
    authedStaffStaffUsersUserIdSettingsRoute:
      authedStaffStaffUsersUserIdSettingsRoute,
    authedStaffStaffUsersUserIdIndexRoute:
      authedStaffStaffUsersUserIdIndexRoute,
  }

const authedStaffStaffUsersUserIdRouteWithChildren =
  authedStaffStaffUsersUserIdRoute._addFileChildren(
    authedStaffStaffUsersUserIdRouteChildren,
  )

interface authedStaffTenantsTenantIdProfilesProfileIdRouteChildren {
  authedStaffTenantsTenantIdProfilesProfileIdMembersRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdMembersRoute
  authedStaffTenantsTenantIdProfilesProfileIdPermissionsRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdPermissionsRoute
  authedStaffTenantsTenantIdProfilesProfileIdIndexRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdIndexRoute
}

const authedStaffTenantsTenantIdProfilesProfileIdRouteChildren: authedStaffTenantsTenantIdProfilesProfileIdRouteChildren =
  {
    authedStaffTenantsTenantIdProfilesProfileIdMembersRoute:
      authedStaffTenantsTenantIdProfilesProfileIdMembersRoute,
    authedStaffTenantsTenantIdProfilesProfileIdPermissionsRoute:
      authedStaffTenantsTenantIdProfilesProfileIdPermissionsRoute,
    authedStaffTenantsTenantIdProfilesProfileIdIndexRoute:
      authedStaffTenantsTenantIdProfilesProfileIdIndexRoute,
  }

const authedStaffTenantsTenantIdProfilesProfileIdRouteWithChildren =
  authedStaffTenantsTenantIdProfilesProfileIdRoute._addFileChildren(
    authedStaffTenantsTenantIdProfilesProfileIdRouteChildren,
  )

interface authedLayoutRouteChildren {
  authedStaffRoute: typeof authedStaffRoute
  authedTenantRoute: typeof authedTenantRouteWithChildren
  authedStaffAuditLogsRoute: typeof authedStaffAuditLogsRoute
  authedStaffDashboardRoute: typeof authedStaffDashboardRouteWithChildren
  authedStaffJobsRoute: typeof authedStaffJobsRouteWithChildren
  authedStaffProfilesRoute: typeof authedStaffProfilesRoute
  authedStaffStaffUsersRoute: typeof authedStaffStaffUsersRoute
  authedStaffTenantsRoute: typeof authedStaffTenantsRoute
  authedStaffInvitationsIndexRoute: typeof authedStaffInvitationsIndexRoute
  authedStaffAuditLogsLogIdRoute: typeof authedStaffAuditLogsLogIdRoute
  authedStaffInvitationsInvitationIdRoute: typeof authedStaffInvitationsInvitationIdRoute
  authedStaffInvitationsNewRoute: typeof authedStaffInvitationsNewRoute
  authedStaffProfilesProfileIdRoute: typeof authedStaffProfilesProfileIdRoute
  authedStaffProfilesNewRoute: typeof authedStaffProfilesNewRoute
  authedStaffStaffUsersUserIdRoute: typeof authedStaffStaffUsersUserIdRouteWithChildren
  authedStaffTenantsTenantIdRoute: typeof authedStaffTenantsTenantIdRoute
  authedStaffTenantsNewRoute: typeof authedStaffTenantsNewRoute
  authedStaffProfilesProfileIdUsersRoute: typeof authedStaffProfilesProfileIdUsersRoute
  authedStaffStaffUsersUserIdEditRoute: typeof authedStaffStaffUsersUserIdEditRoute
  authedStaffTenantUsersDetailsUserIdRoute: typeof authedStaffTenantUsersDetailsUserIdRoute
  authedStaffTenantsTenantIdActivityRoute: typeof authedStaffTenantsTenantIdActivityRoute
  authedStaffTenantsTenantIdEditRoute: typeof authedStaffTenantsTenantIdEditRoute
  authedStaffTenantsTenantIdInvitationsRoute: typeof authedStaffTenantsTenantIdInvitationsRoute
  authedStaffTenantsTenantIdProfilesRoute: typeof authedStaffTenantsTenantIdProfilesRoute
  authedStaffTenantsTenantIdUsageRoute: typeof authedStaffTenantsTenantIdUsageRoute
  authedStaffTenantsTenantIdUsersRoute: typeof authedStaffTenantsTenantIdUsersRoute
  authedStaffTenantUserDetailsTabFallbackRoute: typeof authedStaffTenantUserDetailsTabFallbackRoute
  authedStaffTenantUsersUserIdGeneralRoute: typeof authedStaffTenantUsersUserIdGeneralRoute
  authedStaffTenantUsersUserIdOrganizationsRoute: typeof authedStaffTenantUsersUserIdOrganizationsRoute
  authedStaffTenantsTenantIdProfilesProfileIdRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdRouteWithChildren
  authedStaffTenantsTenantIdProfilesNewRoute: typeof authedStaffTenantsTenantIdProfilesNewRoute
  authedStaffTenantsTenantIdUsersUserIdRoute: typeof authedStaffTenantsTenantIdUsersUserIdRoute
  authedStaffTenantsTenantIdUsersInviteRoute: typeof authedStaffTenantsTenantIdUsersInviteRoute
  authedStaffTenantsTenantIdProfilesProfileIdEditRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdEditRoute
  authedStaffTenantsTenantIdProfilesProfileIdUsersRoute: typeof authedStaffTenantsTenantIdProfilesProfileIdUsersRoute
  authedStaffTenantsTenantIdUsersUserIdEditRoute: typeof authedStaffTenantsTenantIdUsersUserIdEditRoute
}

const authedLayoutRouteChildren: authedLayoutRouteChildren = {
  authedStaffRoute: authedStaffRoute,
  authedTenantRoute: authedTenantRouteWithChildren,
  authedStaffAuditLogsRoute: authedStaffAuditLogsRoute,
  authedStaffDashboardRoute: authedStaffDashboardRouteWithChildren,
  authedStaffJobsRoute: authedStaffJobsRouteWithChildren,
  authedStaffProfilesRoute: authedStaffProfilesRoute,
  authedStaffStaffUsersRoute: authedStaffStaffUsersRoute,
  authedStaffTenantsRoute: authedStaffTenantsRoute,
  authedStaffInvitationsIndexRoute: authedStaffInvitationsIndexRoute,
  authedStaffAuditLogsLogIdRoute: authedStaffAuditLogsLogIdRoute,
  authedStaffInvitationsInvitationIdRoute:
    authedStaffInvitationsInvitationIdRoute,
  authedStaffInvitationsNewRoute: authedStaffInvitationsNewRoute,
  authedStaffProfilesProfileIdRoute: authedStaffProfilesProfileIdRoute,
  authedStaffProfilesNewRoute: authedStaffProfilesNewRoute,
  authedStaffStaffUsersUserIdRoute:
    authedStaffStaffUsersUserIdRouteWithChildren,
  authedStaffTenantsTenantIdRoute: authedStaffTenantsTenantIdRoute,
  authedStaffTenantsNewRoute: authedStaffTenantsNewRoute,
  authedStaffProfilesProfileIdUsersRoute:
    authedStaffProfilesProfileIdUsersRoute,
  authedStaffStaffUsersUserIdEditRoute: authedStaffStaffUsersUserIdEditRoute,
  authedStaffTenantUsersDetailsUserIdRoute:
    authedStaffTenantUsersDetailsUserIdRoute,
  authedStaffTenantsTenantIdActivityRoute:
    authedStaffTenantsTenantIdActivityRoute,
  authedStaffTenantsTenantIdEditRoute: authedStaffTenantsTenantIdEditRoute,
  authedStaffTenantsTenantIdInvitationsRoute:
    authedStaffTenantsTenantIdInvitationsRoute,
  authedStaffTenantsTenantIdProfilesRoute:
    authedStaffTenantsTenantIdProfilesRoute,
  authedStaffTenantsTenantIdUsageRoute: authedStaffTenantsTenantIdUsageRoute,
  authedStaffTenantsTenantIdUsersRoute: authedStaffTenantsTenantIdUsersRoute,
  authedStaffTenantUserDetailsTabFallbackRoute:
    authedStaffTenantUserDetailsTabFallbackRoute,
  authedStaffTenantUsersUserIdGeneralRoute:
    authedStaffTenantUsersUserIdGeneralRoute,
  authedStaffTenantUsersUserIdOrganizationsRoute:
    authedStaffTenantUsersUserIdOrganizationsRoute,
  authedStaffTenantsTenantIdProfilesProfileIdRoute:
    authedStaffTenantsTenantIdProfilesProfileIdRouteWithChildren,
  authedStaffTenantsTenantIdProfilesNewRoute:
    authedStaffTenantsTenantIdProfilesNewRoute,
  authedStaffTenantsTenantIdUsersUserIdRoute:
    authedStaffTenantsTenantIdUsersUserIdRoute,
  authedStaffTenantsTenantIdUsersInviteRoute:
    authedStaffTenantsTenantIdUsersInviteRoute,
  authedStaffTenantsTenantIdProfilesProfileIdEditRoute:
    authedStaffTenantsTenantIdProfilesProfileIdEditRoute,
  authedStaffTenantsTenantIdProfilesProfileIdUsersRoute:
    authedStaffTenantsTenantIdProfilesProfileIdUsersRoute,
  authedStaffTenantsTenantIdUsersUserIdEditRoute:
    authedStaffTenantsTenantIdUsersUserIdEditRoute,
}

const authedLayoutRouteWithChildren = authedLayoutRoute._addFileChildren(
  authedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  authedLayoutRoute: authedLayoutRouteWithChildren,
  acceptInvitationRoute: acceptInvitationRoute,
  fieldValidationRoute: fieldValidationRoute,
  healthRoute: healthRoute,
  loginRoute: loginRoute,
  resetPasswordRoute: resetPasswordRoute,
  signupRoute: signupRoute,
  verifyEmailRoute: verifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
