/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTenantItemRequestBuilder, WithTenantItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/profiles/tenant
 */
export interface TenantRequestBuilder extends BaseRequestBuilder<TenantRequestBuilder> {
    /**
     * Gets an item from the MainApi.Client.staff.profiles.tenant.item collection
     * @param tenantId Unique identifier of the item
     * @returns {WithTenantItemRequestBuilder}
     */
     byTenantId(tenantId: string) : WithTenantItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TenantRequestBuilderUriTemplate = "{+baseurl}/staff/profiles/tenant";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TenantRequestBuilderNavigationMetadata: Record<Exclude<keyof TenantRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTenantId: {
        requestsMetadata: WithTenantItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["tenantId"],
    },
};
/* tslint:enable */
/* eslint-enable */
