/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createSocialAccountCreatedFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, serializeConnectSocialAccountBody, serializeSocialAccountCreated, type AppProblemDetails, type ConnectSocialAccountBody, type SocialAccountCreated, type ValidationProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /social-accounts/connect
 */
export interface ConnectRequestBuilder extends BaseRequestBuilder<ConnectRequestBuilder> {
    /**
     * Connect a Bluesky account for the current tenant
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SocialAccountCreated>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {AppProblemDetails} error when the service returns a 409 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 429 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     * @throws {AppProblemDetails} error when the service returns a 503 status code
     */
     post(body: ConnectSocialAccountBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SocialAccountCreated | undefined>;
    /**
     * Connect a Bluesky account for the current tenant
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ConnectSocialAccountBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ConnectRequestBuilderUriTemplate = "{+baseurl}/social-accounts/connect";
/**
 * Metadata for all the requests in the request builder.
 */
export const ConnectRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ConnectRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            503: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSocialAccountCreatedFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeConnectSocialAccountBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
