/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createGetPublishTargetsForTenantResponseFromDiscriminatorValue, type AppProblemDetails, type GetPublishTargetsForTenantResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /posts/publish-targets
 */
export interface PublishTargetsRequestBuilder extends BaseRequestBuilder<PublishTargetsRequestBuilder> {
    /**
     * List visible social accounts as composer publish targets
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetPublishTargetsForTenantResponse>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {AppProblemDetails} error when the service returns a 429 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<PublishTargetsRequestBuilderGetQueryParameters> | undefined) : Promise<GetPublishTargetsForTenantResponse | undefined>;
    /**
     * List visible social accounts as composer publish targets
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<PublishTargetsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * List visible social accounts as composer publish targets
 */
export interface PublishTargetsRequestBuilderGetQueryParameters {
    projectId?: string;
}
/**
 * Uri template for the request builder.
 */
export const PublishTargetsRequestBuilderUriTemplate = "{+baseurl}/posts/publish-targets{?project_id*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const PublishTargetsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "projectId": "project_id",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PublishTargetsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PublishTargetsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetPublishTargetsForTenantResponseFromDiscriminatorValue,
        queryParametersMapper: PublishTargetsRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
