using System.Text.Json;
using System.Text;

if (args.Length != 2)
{
	Console.WriteLine("Usage: TranslationKeyGenerator <input-json-file> <output-cs-file>");
	Console.WriteLine("Example: TranslationKeyGenerator response-message.en.json Keys.g.cs");
	Environment.Exit(1);
}

var inputFile = args[0];
var outputFile = args[1];

try
{
	GenerateKeysClass(inputFile, outputFile);
	Console.WriteLine($"✅ Generated translation keys: {outputFile}");
}
catch (Exception ex)
{
	Console.WriteLine($"❌ Error generating translation keys: {ex.Message}");
	Environment.Exit(1);
}

static void GenerateKeysClass(string inputFile, string outputFile)
{
	if (!File.Exists(inputFile))
	{
		throw new FileNotFoundException($"Input file not found: {inputFile}");
	}

	// Read and parse the JSON file
	var jsonContent = File.ReadAllText(inputFile);
	using var doc = JsonDocument.Parse(jsonContent);

	var sb = new StringBuilder();

	// File header
	sb.AppendLine("// <auto-generated />");
	sb.AppendLine($"// Generated from {Path.GetFileName(inputFile)}");
	sb.AppendLine("// Do not modify this file directly. It will be regenerated on build.");
	sb.AppendLine("#nullable enable");
	sb.AppendLine();
	sb.AppendLine("using MainApi.Src.Lib;");
	sb.AppendLine();
	sb.AppendLine("namespace MainApi.Localization;");
	sb.AppendLine();
	sb.AppendLine("/// <summary>");
	sb.AppendLine("/// Type-safe translation keys generated from response message JSON");
	sb.AppendLine("/// </summary>");
	sb.AppendLine("public static partial class ResponseKeys");
	sb.AppendLine("{");

	// Generate properties for each key in the JSON
	var sortedKeys = new List<(string key, string value)>();

	foreach (var property in doc.RootElement.EnumerateObject())
	{
		sortedKeys.Add((property.Name, property.Value.GetString() ?? string.Empty));
	}

	// Sort keys alphabetically for consistent output
	sortedKeys.Sort((a, b) => string.Compare(a.key, b.key, StringComparison.Ordinal));

	foreach (var (key, value) in sortedKeys)
	{
		var propertyName = ToPascalCase(key);
		var escapedValue = EscapeXmlComment(value);

		sb.AppendLine("    /// <summary>");
		sb.AppendLine($"    /// {escapedValue}");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine($"    public static readonly TranslationKey {propertyName} = new(\"{key}\");");
		sb.AppendLine();
	}

	sb.AppendLine("}");

	// Ensure output directory exists
	var outputDir = Path.GetDirectoryName(outputFile);
	if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
	{
		Directory.CreateDirectory(outputDir);
	}

	// Write the generated file
	File.WriteAllText(outputFile, sb.ToString());
}

/// <summary>
/// Converts a kebab-case or snake-case string to PascalCase for C# property names
/// </summary>
static string ToPascalCase(string input)
{
	if (string.IsNullOrEmpty(input))
		return input;

	var parts = input.Split(new[] { '-', '_' }, StringSplitOptions.RemoveEmptyEntries);
	var result = new StringBuilder();

	foreach (var part in parts)
	{
		if (part.Length > 0)
		{
			result.Append(char.ToUpperInvariant(part[0]));
			if (part.Length > 1)
			{
				result.Append(part[1..].ToLowerInvariant());
			}
		}
	}

	return result.ToString();
}

/// <summary>
/// Escapes a string for use in C# XML documentation comments
/// </summary>
static string EscapeXmlComment(string text)
{
	if (string.IsNullOrEmpty(text))
		return string.Empty;

	return text
			.Replace("&", "&amp;")
			.Replace("<", "&lt;")
			.Replace(">", "&gt;")
			.Replace("\"", "&quot;")
			.Replace("'", "&apos;");
}
