/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createBulkReactivateTenantsResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, serializeBulkReactivateTenantsAsStaffBody, serializeBulkReactivateTenantsResult, type AppProblemDetails, type BulkReactivateTenantsAsStaffBody, type BulkReactivateTenantsResult, type ValidationProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/tenants/bulk-reactivate
 */
export interface BulkReactivateRequestBuilder extends BaseRequestBuilder<BulkReactivateRequestBuilder> {
    /**
     * Bulk reactivate tenants
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BulkReactivateTenantsResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     post(body: BulkReactivateTenantsAsStaffBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BulkReactivateTenantsResult | undefined>;
    /**
     * Bulk reactivate tenants
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: BulkReactivateTenantsAsStaffBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BulkReactivateRequestBuilderUriTemplate = "{+baseurl}/staff/tenants/bulk-reactivate";
/**
 * Metadata for all the requests in the request builder.
 */
export const BulkReactivateRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: BulkReactivateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createBulkReactivateTenantsResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeBulkReactivateTenantsAsStaffBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
