/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createBulkStaffProfileUserUnassignActionResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, serializeBulkStaffProfileUserUnassignActionResult, serializeUnassignStaffProfileUsersBody, type AppProblemDetails, type BulkStaffProfileUserUnassignActionResult, type UnassignStaffProfileUsersBody, type ValidationProblemDetails } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/profiles/{profileId}/users/unassign
 */
export interface UnassignRequestBuilder extends BaseRequestBuilder<UnassignRequestBuilder> {
    /**
     * Bulk-unassign staff users from a staff profile
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BulkStaffProfileUserUnassignActionResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {AppProblemDetails} error when the service returns a 404 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 429 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     post(body: UnassignStaffProfileUsersBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BulkStaffProfileUserUnassignActionResult | undefined>;
    /**
     * Bulk-unassign staff users from a staff profile
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: UnassignStaffProfileUsersBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UnassignRequestBuilderUriTemplate = "{+baseurl}/staff/profiles/{profileId}/users/unassign";
/**
 * Metadata for all the requests in the request builder.
 */
export const UnassignRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: UnassignRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createBulkStaffProfileUserUnassignActionResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUnassignStaffProfileUsersBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
