/**
 * @vitest-environment node
 *
 * KEPT RED TEST — issue #1852.
 *
 * ## Context
 *
 * Three PRs went red the same day for the same cause — unformatted files
 * that a commit should have fixed — and each on four checks at once
 * (`quality`, `quality-gate`, `supply-chain`, `front-ci-gate`). The cause:
 *
 * ```
 * git config core.hooksPath  ->  .husky/_
 * ```
 *
 * `core.hooksPath` is a RELATIVE path, so git resolves it inside the working
 * directory of *each* worktree. But `.husky/_` is generated by `husky install`
 * and is NOT tracked; only `.husky/pre-commit` and `.husky/pre-push` are. So a
 * freshly created worktree has no `.husky/_`, git finds no hooks, and neither
 * lint-staged nor the formatter ever runs before the commit. Nothing in the
 * check names says "formatting", so each red cost a diagnostic search.
 *
 * The fix (issue #1852): stop depending on the generated directory. The real
 * hooks stay versioned in `.husky/`, `prepare` runs a first-party installer
 * (`packages/scripts-ts/src/install-git-hooks.ts`) that points
 * `core.hooksPath` at the versioned `.husky` dir in the shared git config —
 * which every worktree of that clone inherits — and the installer fails loud
 * when the hooks cannot be wired. CI wires the hooks explicitly
 * (front-ci.yml::supply-chain::"Install Git hooks (mirrors prepare)").
 *
 * ## What the proof asserts
 *
 * A REAL fresh worktree, created the way every task worktree is created
 * (`git worktree add`), must NOT let an unformatted file through on commit:
 * the tracked pre-commit hook runs lint-staged on the staged file and oxfmt
 * rewrites it, so the committed content differs from the unformatted input.
 *
 * The proof asserts the BUG: the committed content is STILL the unformatted
 * input.
 *
 * ## Three-state discrimination
 *
 * - BUG PRESENT (hooks absent from fresh worktrees, pre-fix state): the
 *   commit succeeds untouched and the committed content equals the
 *   unformatted input. The assertion PASSES. The CI step *Verify paired red
 *   proofs* then turns RED — the "proof is stale" signal.
 *
 * - BUG ABSENT (fixed): the pre-commit hook runs `pnpm exec lint-staged`,
 *   oxfmt rewrites the probe and lint-staged re-stages it, and the committed
 *   content is the formatted file. The assertion FAILS with an AssertionError
 *   — the kept-red state the CI step demands.
 *
 * - MESURE IMPOSSIBLE: the worktree cannot be created, the commit fails
 *   (hook tooling missing, hook error, non-executable hook), or the probe
 *   cannot be read back. The test THROWS — the runner classifies a thrown
 *   Error as a broken measurement and fails CI loudly naming the cause; it
 *   never silently collapses to "bug absent".
 *
 * ## Replay
 *   cd apps/front && pnpm exec vitest run --config vitest.proofs.config.ts \
 *     tests/proofs/1852/red-1852-worktree-unformatted-commit.test.ts
 *
 * Expected: FAIL — on correct code the fresh worktree's pre-commit hook
 * reformats the probe, so the committed content is not the unformatted input.
 *
 * ## Mutations to introduce the red (restore the bug)
 *
 * 1. `core.hooksPath` set back to `.husky/_` (or any directory without
 *    tracked hooks): the fresh worktree resolves it to a nonexistent path,
 *    no hook runs, the commit passes through unchanged.
 * 2. Delete or strip `.husky/pre-commit` from the tracked tree: no formatter
 *    runs on commit.
 * 3. `install-git-hooks.ts` points `core.hooksPath` at the wrong directory
 *    or never runs (prepare removed / CI step removed): same as 1.
 *
 * ## Honest limits
 *
 * - The proof exercises the REAL pipeline (real worktree, real commit, real
 *   tracked pre-commit hook, real lint-staged, real oxfmt) with ONE seam: it
 *   symlinks `<worktree>/node_modules` -> the repo's `node_modules` so
 *   lint-staged resolves in the throwaway worktree without a second full
 *   `pnpm install`. A hook that is present but wrongly assumes a fresh
 *   install (e.g. hardcoded paths) could still be missed, but the default
 *   hook resolves pnpm from PATH exactly like a developer's environment.
 * - The test itself does not run the installer; it observes the environment
 *   the repo/CI set up. A mutation that silently drops `prepare` from
 *   package.json while the CI step "Install Git hooks (mirrors prepare)"
 *   remains would keep this proof green — that CI step runs
 *   `pnpm run prepare`, which fails when the script is gone (single source).
 */
import { execFileSync } from 'node:child_process';
import {
	accessSync,
	constants,
	existsSync,
	rmSync,
	symlinkSync,
	writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { expect, test } from 'vitest';

// apps/front is the vitest cwd; the repo root is one level up.
const ROOT = join(process.cwd(), '..');
const HOOKS = ['pre-commit', 'pre-push'] as const;

const UNFORMATTED_PROBE =
	'export const   probe = (  ) => {\n      return    42\n}\n';

test('a fresh worktree lets an unformatted commit through unchanged (issue #1852)', () => {
	const worktree = join(tmpdir(), `proof-1852-${process.pid}-${Date.now()}`);

	try {
		execFileSync(
			'git',
			['-C', ROOT, 'worktree', 'add', '--detach', worktree, 'HEAD'],
			{
				stdio: ['ignore', 'pipe', 'pipe'],
				encoding: 'utf-8',
			},
		);

		execFileSync(
			'git',
			['-C', worktree, 'config', 'user.email', 'proof-1852@publyapp.invalid'],
			{
				stdio: 'pipe',
			},
		);
		execFileSync('git', ['-C', worktree, 'config', 'user.name', 'proof-1852'], {
			stdio: 'pipe',
		});

		// The fresh worktree must have the versioned hooks checked out AND
		// executable — git 2.53 ignores a non-executable hook outright (with
		// only a hint line). If either is off, the measurement is impossible
		// and must fail loud, not silently pass.
		for (const hook of HOOKS) {
			const hookPath = join(worktree, '.husky', hook);
			if (!existsSync(hookPath)) {
				throw new Error(
					`MESURE IMPOSSIBLE: fresh worktree ${worktree} is missing the tracked hook .husky/${hook} — the checkout is broken, not the hook wiring.`,
				);
			}
			try {
				accessSync(hookPath, constants.X_OK);
			} catch {
				throw new Error(
					`MESURE IMPOSSIBLE: tracked hook .husky/${hook} is not executable in fresh worktree ${worktree} — git ignores non-executable hooks, so this checkout has NO hooks even though core.hooksPath is correct.`,
				);
			}
		}

		// One deliberate seam (see Honest limits): share the repo's
		// node_modules so lint-staged/oxfmt run without a second install.
		const wtModules = join(worktree, 'node_modules');
		if (!existsSync(wtModules)) {
			const type = process.platform === 'win32' ? 'junction' : 'dir';
			symlinkSync(join(ROOT, 'node_modules'), wtModules, type);
		}

		writeFileSync(join(worktree, 'probe-1852.ts'), UNFORMATTED_PROBE, 'utf-8');
		execFileSync('git', ['-C', worktree, 'add', 'probe-1852.ts'], {
			stdio: 'pipe',
		});
		execFileSync('git', ['-C', worktree, 'commit', '-m', 'probe-1852'], {
			stdio: ['ignore', 'pipe', 'pipe'],
			encoding: 'utf-8',
		});

		const committed = execFileSync(
			'git',
			['-C', worktree, 'show', 'HEAD:probe-1852.ts'],
			{
				encoding: 'utf-8',
			},
		);

		expect(committed).toBe(UNFORMATTED_PROBE);
	} finally {
		try {
			execFileSync(
				'git',
				['-C', ROOT, 'worktree', 'remove', '--force', worktree],
				{
					stdio: 'pipe',
				},
			);
		} catch {
			// The worktree may already be gone; the rm below is the real cleanup.
		}
		rmSync(worktree, { force: true, recursive: true });
	}
});
