// * https://reactrouter.com/api/other-api/adapter#react-routerexpress
// * https://github.com/remix-run/react-router-templates/blob/main/node-custom-server/server.js

// @ts-check
import compression from 'compression';
import express from 'express';
import helmet from 'helmet';
import morgan from 'morgan';
import { nanoid } from 'nanoid';
import { RouterContextProvider } from 'react-router';

const MODE = process.env.MODE;
const IS_DEVELOPMENT = process.env.NODE_ENV === 'development';
const PORT = process.env.PORT ? Number.parseInt(process.env.PORT, 10) : 5050;

const app = express();

app.use(compression());
app.disable('x-powered-by');
app.set('trust proxy', 1);
app.set('case sensitive routing', true);

/**
 * @typedef {import('express').Request & { ___NONCE___?: string }} RequestWithNonce
 */

/**
 * @typedef {object} ServerEntryModule
 * @property {import('react-router').RouterContext<string | undefined>} nonceContext
 * @property {(path: string) => boolean} isPreRenderPath
 * @property {string} STATIC_PRE_RENDER_PATHS_MAP_NONCE
 * @property {(params: {
 *   isDevelopment: boolean,
 *   reportOnly: boolean,
 *   nonce: string,
 *   additionalConnectSrc?: string[],
 * }) => { helmetConfig: import('helmet').HelmetOptions["contentSecurityPolicy"] }} getUnifiedCSPConfig
 */

const PRE_RENDER_HTML_PATH_MAP = new Map([
	['/index.html', '/'],
	['/login/index.html', '/login'],
]);

/**
 * @param {import('express').Request} request
 * @param {ServerEntryModule} entryModule
 */
const getNonceForRequest = (request, entryModule) => {
	const normalizedPath =
		PRE_RENDER_HTML_PATH_MAP.get(request.path) ?? request.path;

	return entryModule.isPreRenderPath(normalizedPath)
		? entryModule.STATIC_PRE_RENDER_PATHS_MAP_NONCE
		: nanoid();
};

const getConfiguredApiConnectSrc = () => {
	const apiBaseUrl = process.env.VITE_ASP_SERVER_URL;
	if (!apiBaseUrl) {
		return [];
	}

	try {
		const origin = new URL(apiBaseUrl).origin;
		return origin === 'null' ? [] : [origin];
	} catch {
		return [];
	}
};

/**
 * @param {RequestWithNonce} request
 * @param {import('react-router').RouterContext<string | undefined>} nonceContext
 */
const createLoadContext = (request, nonceContext) => {
	if (!request.___NONCE___) {
		throw new Error('Nonce has not been set');
	}

	const loadContext = new RouterContextProvider();
	loadContext.set(nonceContext, request.___NONCE___);

	return loadContext;
};

if (IS_DEVELOPMENT) {
	console.log('Starting development server');

	const viteDevServer = await import('vite').then((vite) => {
		return vite.createServer({
			server: { middlewareMode: true },
			mode: MODE,
		});
	});

	app.use(viteDevServer.middlewares);

	app.use(async (req, res, next) => {
		try {
			const source = await viteDevServer.ssrLoadModule('./server/app.ts');
			return await source.app(req, res, next);
		} catch (error) {
			if (typeof error === 'object' && error instanceof Error) {
				viteDevServer.ssrFixStacktrace(error);
			}

			next(error);
		}
	});
} else {
	console.log('Starting production server');

	app.use(
		'/assets',
		express.static('build/client/assets', { immutable: true, maxAge: '1y' }),
	);

	app.use(morgan('tiny'));

	/**
	 * @typedef {import('react-router').ServerBuild & {
	 *   app?: import('express').Application,
	 *   entry: { module: Partial<ServerEntryModule> }
	 * }} ServerModule
	 */

	/** @type {ServerModule} */
	let module;

	// @ts-ignore generated by build
	module = await import('./build/server/index.js');

	if (module.app) {
		app.use(module.app);
	} else {
		const entryModuleExports = module.entry.module;
		if (
			!entryModuleExports.nonceContext ||
			!entryModuleExports.isPreRenderPath ||
			!entryModuleExports.STATIC_PRE_RENDER_PATHS_MAP_NONCE ||
			!entryModuleExports.getUnifiedCSPConfig
		) {
			throw new Error(
				'React Router server build did not export server context helpers',
			);
		}
		const entryModule = /** @type {ServerEntryModule} */ (entryModuleExports);
		const configuredApiConnectSrc = getConfiguredApiConnectSrc();

		const { createRequestHandler } = await import('@react-router/express');
		app.use((req, res, next) => {
			const request = /** @type {RequestWithNonce} */ (req);
			const nonce = getNonceForRequest(
				request,
				/** @type {ServerEntryModule} */ (entryModule),
			);
			request.___NONCE___ = nonce;

			return helmet({
				contentSecurityPolicy: entryModule.getUnifiedCSPConfig({
					isDevelopment: false,
					reportOnly: false,
					nonce,
					additionalConnectSrc: configuredApiConnectSrc,
				}).helmetConfig,
			})(req, res, next);
		});
		app.use(express.static('build/client', { index: false, maxAge: '1h' }));
		app.use(
			createRequestHandler({
				build: module,
				getLoadContext: (req) => {
					return createLoadContext(
						/** @type {RequestWithNonce} */ (req),
						entryModule.nonceContext,
					);
				},
			}),
		);
	}
}

const SEPARATOR = '='.repeat(60);

app.listen(PORT, () => {
	console.log(`\n${SEPARATOR}`);
	console.log(
		`🚀  Server is running at: \x1b[32mhttp://localhost:${PORT}\x1b[0m`,
	);
	console.log(`${SEPARATOR}\n`);
});
