/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
	createAppProblemDetailsFromDiscriminatorValue,
	createCheckInvitationTokenResultFromDiscriminatorValue,
	createValidationProblemDetailsFromDiscriminatorValue,
	type AppProblemDetails,
	type CheckInvitationTokenResult,
	type ValidationProblemDetails,
} from '../../models/index.js';
// @ts-ignore
import {
	type BaseRequestBuilder,
	type Parsable,
	type ParsableFactory,
	type RequestConfiguration,
	type RequestInformation,
	type RequestsMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /invitations/check
 */
export interface CheckRequestBuilder
	extends BaseRequestBuilder<CheckRequestBuilder> {
	/**
	 * Check Invitation Token
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {Promise<CheckInvitationTokenResult>}
	 * @throws {AppProblemDetails} error when the service returns a 400 status code
	 * @throws {ValidationProblemDetails} error when the service returns a 422 status code
	 * @throws {AppProblemDetails} error when the service returns a 500 status code
	 */
	get(
		requestConfiguration?:
			| RequestConfiguration<CheckRequestBuilderGetQueryParameters>
			| undefined,
	): Promise<CheckInvitationTokenResult | undefined>;
	/**
	 * Check Invitation Token
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {RequestInformation}
	 */
	toGetRequestInformation(
		requestConfiguration?:
			| RequestConfiguration<CheckRequestBuilderGetQueryParameters>
			| undefined,
	): RequestInformation;
}
/**
 * Check Invitation Token
 */
export interface CheckRequestBuilderGetQueryParameters {
	id?: string;
	token?: string;
}
/**
 * Uri template for the request builder.
 */
export const CheckRequestBuilderUriTemplate =
	'{+baseurl}/invitations/check?Id={Id}&Token={Token}';
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const CheckRequestBuilderGetQueryParametersMapper: Record<string, string> = {
	id: 'Id',
	token: 'Token',
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CheckRequestBuilderRequestsMetadata: RequestsMetadata = {
	get: {
		uriTemplate: CheckRequestBuilderUriTemplate,
		responseBodyContentType: 'application/json',
		errorMappings: {
			400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
		},
		adapterMethodName: 'send',
		responseBodyFactory: createCheckInvitationTokenResultFromDiscriminatorValue,
		queryParametersMapper: CheckRequestBuilderGetQueryParametersMapper,
	},
};
/* tslint:enable */
/* eslint-enable */
