/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ActiveRequestBuilderRequestsMetadata, type ActiveRequestBuilder } from './active/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /notices
 */
export interface NoticesRequestBuilder extends BaseRequestBuilder<NoticesRequestBuilder> {
    /**
     * The active property
     */
    get active(): ActiveRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const NoticesRequestBuilderUriTemplate = "{+baseurl}/notices";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const NoticesRequestBuilderNavigationMetadata: Record<Exclude<keyof NoticesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    active: {
        requestsMetadata: ActiveRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
