#!/usr/bin/env bash
# checks that every .cs file tracked by git is:
#   1. included in a project referenced by PublyApp.slnx  (no orphaned files)
#   2. does not carry a <auto-generated/> header           (dotnet format skips these)
#
# Exit 0 = clean, exit 1 = one or more violations (names printed).

set -euo pipefail

# Resolve repo root from packages/scripts-cs/src/ (3 levels up) so all child
# commands (find, git, python) see the same working directory regardless of how
# the script was invoked.
REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$REPO_ROOT"

SLNX="PublyApp.slnx"

# ── Allowlist: directories/files intentionally excluded from PublyApp.slnx ───────────
# These are legitimately excluded from dotnet format's scope.
declare -A known_excluded_dirs
known_excluded_dirs["packages/lint-cs"]=1
known_excluded_dirs["packages/scripts-cs"]=1

is_known_excluded() {
  local file="$1"
  for dir in "${!known_excluded_dirs[@]}"; do
    if [[ "$file" == "$dir"/* ]]; then
      return 0
    fi
  done
  return 1
}

# ── Allowlist: known auto-generated files (dotnet format skips these by design) ─────
# EF Core migrations and the localization code generator produce these; they are
# re-generated on every migration/model change and must not be reformatted.
# A hand-authored file that someone adds <auto-generated/> to will NOT appear here,
# so the guard will catch it as a violation.
declare -A known_auto_generated_files
while IFS= read -r f; do
  known_auto_generated_files["$f"]=1
done < <(git ls-files 'apps/api/Migrations/')
known_auto_generated_files["apps/api/Localization/ResponseKeys.g.cs"]=1
known_auto_generated_files["apps/api/Localization/ResponseKeys.cs"]=1

is_known_auto_generated() {
  local file="$1"
  [[ -v known_auto_generated_files["$file"] ]]
}

# ── 1. Collect all .cs project directories from PublyApp.slnx ──────────────────
# Parse the slnx XML directly (no namespace) via python3 to extract Project Path
# attrs. Each csproj's directory is where dotnet format will look for sources.
declare -A in_solution
while IFS= read -r csproj; do
  proj_dir="${csproj%/*}"    # e.g. apps/api from apps/api/PublyApp.Api.csproj
  if [[ -d "$proj_dir" ]]; then
    while IFS= read -r cs; do
      cs="${cs#./}"
      in_solution["$cs"]=1
    done < <(find "$proj_dir" -name '*.cs' -not -path '*/bin/*' -not -path '*/obj/*')
  fi
done < <(python3 -c "
import sys, re
content = open(sys.argv[1]).read()
for m in re.finditer(r'<Project Path=\"([^\"]+\.csproj)\"', content):
    print(m.group(1))
" "$SLNX")

# ── 2. Check every git-tracked .cs file ─────────────────────────────────────────
violations=0
orphaned_reported=0

while IFS= read -r file; do
  if [[ "$file" == apps/api/openapi.json ]]; then
    continue
  fi

  if [[ ! -v in_solution["$file"] ]]; then
    if is_known_excluded "$file"; then
      echo "ORPHANED (allowlisted): $file is tracked by git but belongs to no project in $SLNX" >&2
      orphaned_reported=1
    else
      echo "ORPHANED: $file is tracked by git but belongs to no project in $SLNX — dotnet format will not see it" >&2
      violations=$((violations + 1))
    fi
  fi
done < <(git ls-files '*.cs')

# ── 3. Check for <auto-generated/> headers ────────────────────────────────────────
#
# .NET code generators (T4, EF Core scaffolding, Roslyn) emit a multi-line banner:
#   //--------------------------------------------------------------------------
#   // <auto-generated>
#   ...
# `head -1` alone missed this because line 1 is dashes and <auto-generated> is on
# line 2. We read a BOUNDED prefix of comment lines (first 10) — not the whole file
# — so the guard stays fast even on large files. If a generator moves its banner
# below line 10, the guard will not detect it here; that generator's files should
# already be in the allowlist (is_known_auto_generated), which is the authoritative
# list. The bounded prefix catches the standard 2-line banner and any hand-authored
# <auto-generated/> header, without scanning entire files.
AUTO_GENERATED_PREFIX_LINES=10
while IFS= read -r file; do
  # FAIL LOUDLY: an unreadable or empty file must not silently pass as "not
  # auto-generated". An absent/unreadable file is a guard failure, not a skip.
  if [[ ! -r "$file" ]]; then
    echo "AUTO-GENERATED: cannot read $file — guard refuses to assume a file that cannot be inspected is safe" >&2
    violations=$((violations + 1))
    continue
  fi

  if head -n "$AUTO_GENERATED_PREFIX_LINES" "$file" 2>/dev/null | grep -qi '<auto-generated'; then
    if is_known_auto_generated "$file"; then
      echo "AUTO-GENERATED (allowlisted): $file — known generated file (dotnet format skips by design)" >&2
    else
      echo "AUTO-GENERATED: $file carries an <auto-generated/> header — dotnet format will skip it" >&2
      violations=$((violations + 1))
    fi
  fi
done < <(git ls-files '*.cs')

# ── 4. Done ─────────────────────────────────────────────────────────────────────
if [[ $violations -gt 0 ]]; then
  echo "CSharpFormatGuard: $violations violation(s) found" >&2
  exit 1
fi

if [[ $orphaned_reported -gt 0 ]]; then
  echo "CSharpFormatGuard: known exclusions reported (all allowlisted — clean)" >&2
fi

echo "CSharpFormatGuard: all .cs files are covered by the formatter"
exit 0
