/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ScopesRequestBuilderNavigationMetadata, type ScopesRequestBuilder } from './scopes/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/permissions
 */
export interface PermissionsRequestBuilder extends BaseRequestBuilder<PermissionsRequestBuilder> {
    /**
     * The scopes property
     */
    get scopes(): ScopesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PermissionsRequestBuilderUriTemplate = "{+baseurl}/staff/permissions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PermissionsRequestBuilderNavigationMetadata: Record<Exclude<keyof PermissionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    scopes: {
        navigationMetadata: ScopesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
