/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
	createAppProblemDetailsFromDiscriminatorValue,
	createValidationProblemDetailsFromDiscriminatorValue,
	type AppProblemDetails,
	type ValidationProblemDetails,
} from '../../models/index.js';
// @ts-ignore
import {
	type AdditionalDataHolder,
	type BaseRequestBuilder,
	type Parsable,
	type ParsableFactory,
	type ParseNode,
	type RequestConfiguration,
	type RequestInformation,
	type RequestsMetadata,
	type SerializationWriter,
} from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PermissionsGetResponse}
 */
// @ts-ignore
export function createPermissionsGetResponseFromDiscriminatorValue(
	parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
	return deserializeIntoPermissionsGetResponse;
}
/**
 * The deserialization information for the current model
 * @param PermissionsGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPermissionsGetResponse(
	permissionsGetResponse: Partial<PermissionsGetResponse> | undefined = {},
): Record<string, (node: ParseNode) => void> {
	return {};
}
export interface PermissionsGetResponse
	extends AdditionalDataHolder,
		Parsable {}
/**
 * Builds and executes requests for operations under /staff/permissions
 */
export interface PermissionsRequestBuilder
	extends BaseRequestBuilder<PermissionsRequestBuilder> {
	/**
	 * Find staff permissions
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {Promise<PermissionsGetResponse>}
	 * @throws {AppProblemDetails} error when the service returns a 400 status code
	 * @throws {AppProblemDetails} error when the service returns a 401 status code
	 * @throws {AppProblemDetails} error when the service returns a 403 status code
	 * @throws {ValidationProblemDetails} error when the service returns a 422 status code
	 * @throws {AppProblemDetails} error when the service returns a 500 status code
	 */
	get(
		requestConfiguration?:
			| RequestConfiguration<PermissionsRequestBuilderGetQueryParameters>
			| undefined,
	): Promise<PermissionsGetResponse | undefined>;
	/**
	 * Find staff permissions
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {RequestInformation}
	 */
	toGetRequestInformation(
		requestConfiguration?:
			| RequestConfiguration<PermissionsRequestBuilderGetQueryParameters>
			| undefined,
	): RequestInformation;
}
/**
 * Find staff permissions
 */
export interface PermissionsRequestBuilderGetQueryParameters {
	language?: string;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PermissionsGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePermissionsGetResponse(
	writer: SerializationWriter,
	permissionsGetResponse:
		| Partial<PermissionsGetResponse>
		| undefined
		| null = {},
	isSerializingDerivedType: boolean = false,
): void {
	if (!permissionsGetResponse || isSerializingDerivedType) {
		return;
	}
	writer.writeAdditionalData(permissionsGetResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const PermissionsRequestBuilderUriTemplate =
	'{+baseurl}/staff/permissions{?Language*}';
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const PermissionsRequestBuilderGetQueryParametersMapper: Record<
	string,
	string
> = {
	language: 'Language',
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PermissionsRequestBuilderRequestsMetadata: RequestsMetadata = {
	get: {
		uriTemplate: PermissionsRequestBuilderUriTemplate,
		responseBodyContentType: 'application/json',
		errorMappings: {
			400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
		},
		adapterMethodName: 'send',
		responseBodyFactory: createPermissionsGetResponseFromDiscriminatorValue,
		queryParametersMapper: PermissionsRequestBuilderGetQueryParametersMapper,
	},
};
/* tslint:enable */
/* eslint-enable */
