/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiResponseFromDiscriminatorValue, createGetUserAuthDataResultFromDiscriminatorValue, type ApiResponse, type GetUserAuthDataResult } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth/user-auth-data
 */
export interface UserAuthDataRequestBuilder extends BaseRequestBuilder<UserAuthDataRequestBuilder> {
    /**
     * Get User Auth Data
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetUserAuthDataResult>}
     * @throws {ApiResponse} error when the service returns a 400 status code
     * @throws {ApiResponse} error when the service returns a 401 status code
     * @throws {ApiResponse} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GetUserAuthDataResult | undefined>;
    /**
     * Get User Auth Data
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UserAuthDataRequestBuilderUriTemplate = "{+baseurl}/auth/user-auth-data";
/**
 * Metadata for all the requests in the request builder.
 */
export const UserAuthDataRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: UserAuthDataRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetUserAuthDataResultFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
