/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiResponseFromDiscriminatorValue, createGetTenantAsStaffResultFromDiscriminatorValue, type ApiResponse, type GetTenantAsStaffResult } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/tenants/{tenantId}
 */
export interface WithTenantItemRequestBuilder extends BaseRequestBuilder<WithTenantItemRequestBuilder> {
    /**
     * Get a tenant
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetTenantAsStaffResult>}
     * @throws {ApiResponse} error when the service returns a 400 status code
     * @throws {ApiResponse} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GetTenantAsStaffResult | undefined>;
    /**
     * Get a tenant
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithTenantItemRequestBuilderUriTemplate = "{+baseurl}/staff/tenants/{tenantId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithTenantItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithTenantItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetTenantAsStaffResultFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
