/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiResponseFromDiscriminatorValue, createVerifyEmailRequestResultFromDiscriminatorValue, serializeVerifyEmailRequestBody, serializeVerifyEmailRequestResult, type ApiResponse, type VerifyEmailRequestBody, type VerifyEmailRequestResult } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth/verify-email-request
 */
export interface VerifyEmailRequestRequestBuilder extends BaseRequestBuilder<VerifyEmailRequestRequestBuilder> {
    /**
     * Verify Email Request
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VerifyEmailRequestResult>}
     * @throws {ApiResponse} error when the service returns a 400 status code
     */
     post(body: VerifyEmailRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<VerifyEmailRequestResult | undefined>;
    /**
     * Verify Email Request
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: VerifyEmailRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const VerifyEmailRequestRequestBuilderUriTemplate = "{+baseurl}/auth/verify-email-request";
/**
 * Metadata for all the requests in the request builder.
 */
export const VerifyEmailRequestRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: VerifyEmailRequestRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createVerifyEmailRequestResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeVerifyEmailRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
