#!/usr/bin/env node

import { spawn, spawnSync } from 'node:child_process';
import { lookup } from 'node:dns/promises';
import { once } from 'node:events';
import { existsSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { createServer } from 'node:net';
import path from 'node:path';
import process from 'node:process';
import { createInterface } from 'node:readline';
import { fileURLToPath } from 'node:url';

const ENVIRONMENT_GENERATION_MARKER =
	'# Generated by review-front-2 — do not edit';
const FRONTEND_TOKEN_PREFIX = 'pr';
const RESERVED_PORTS = new Set([5000, 5050, 5454]);
const BASE_PORT = 5000;
const ISSUE_TOKEN_PATTERN_SOURCE = '(^|[\\/_-])${number}(?=$|[/_-])';

const FRONTEND_ENV_FILE = '.env.development.local';
const FRONTEND_ENV_KEYS = [
	'FRONT_URL',
	'PUBLIC_API_BASE_URL',
	'SERVER_API_BASE_URL',
	'VITE_ASP_SERVER_URL',
	'PUBLIC_POSTHOG_PROJECT_TOKEN',
];

const ALLOWLISTED_VITE_ENV_KEYS = new Set([
	'ALL_PROXY',
	'BUNDLE_GEMFILE',
	'CI',
	'COREPACK_ENABLE_DOWNLOAD_PROMPT',
	'COREPACK_HOME',
	'DISABLE_OPENCOLLECTIVE',
	'HOME',
	'LANG',
	'LC_ALL',
	'NO_PROXY',
	'PATH',
	'SHELL',
	'TMP',
	'TEMP',
	'TMPDIR',
	'USER',
	'USERNAME',
	'XDG_CACHE_HOME',
	'XDG_CONFIG_HOME',
	'XDG_DATA_HOME',
	'XDG_STATE_HOME',
]);

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, '..');
const requestedRef = process.argv.at(2)?.trim() ?? '';
const hasInteractiveTerminal = process.stdin.isTTY && process.stdout.isTTY;

const formatShellWord = (value) => JSON.stringify(String(value));

const runCommand = (command, args, options = {}) => {
	const result = spawnSync(command, args, {
		cwd: options.cwd,
		env: { ...process.env, ...(options.env ?? {}) },
		encoding: 'utf8',
		stdio: options.stdio ?? 'pipe',
	});

	if (result.error) {
		throw result.error;
	}

	const status = result.status ?? -1;
	if (status !== 0) {
		const stderr = String(result.stderr ?? '').trim();
		const stdout = String(result.stdout ?? '').trim();
		const prefix = options.label ? `${options.label}: ` : '';
		throw new Error(
			`${prefix}${command} ${args.join(' ')} exited with status ${String(status)} ` +
				`${stderr || stdout ? `\n${stderr || stdout}` : ''}`,
		);
	}

	return {
		stdout: String(result.stdout ?? ''),
		stderr: String(result.stderr ?? ''),
		status,
	};
};

const runCommandOptional = (command, args, options = {}) => {
	try {
		return runCommand(command, args, options);
	} catch (error) {
		return {
			status: -1,
			stdout: '',
			stderr: String(error?.message ?? ''),
			error,
		};
	}
};

const runJson = (command, args, options = {}) => {
	const output = runCommand(command, args, options).stdout.trim();
	if (output.length === 0) {
		return null;
	}

	return JSON.parse(output);
};

const isGhMissingReference = (message) => {
	if (!message) {
		return false;
	}

	const lowered = message.toLowerCase();
	return (
		((lowered.includes('could not find') ||
			lowered.includes('could not resolve to a pullrequest') ||
			lowered.includes('could not resolve to a pull request')) &&
			(lowered.includes('pullrequest') ||
				lowered.includes('pull request') ||
				lowered.includes('issue'))) ||
		lowered.includes('not found')
	);
};

const isGhAuthFailure = (message) => {
	if (!message) {
		return false;
	}

	const lowered = message.toLowerCase();
	return (
		lowered.includes('authentication') ||
		lowered.includes('login') ||
		lowered.includes('not authenticated') ||
		lowered.includes('forbidden') ||
		lowered.includes('unauthorized') ||
		lowered.includes('http 401')
	);
};

const runGhJson = (args, options = {}) => {
	const { stdout, stderr, status } = runCommandOptional('gh', args, {
		...(options.env ? { env: options.env } : {}),
		label: options.label,
	});

	if (status === 0) {
		const output = stdout.trim();
		if (output.length === 0) {
			return null;
		}

		return JSON.parse(output);
	}

	const message = stderr.trim();
	if (isGhMissingReference(message)) {
		return null;
	}

	if (isGhAuthFailure(message)) {
		throw new Error(
			`GitHub auth is required to resolve PR/issue references. ${message}`,
		);
	}

	if (message.length > 0) {
		throw new Error(`gh failed for ${args[0]} ${args[1]}: ${message}`);
	}

	throw new Error(`gh failed for ${args[0]} ${args[1]}.`);
};

const askChoice = async (title, rows) => {
	console.log(title);
	rows.forEach((row, index) => {
		console.log(`${index + 1}. ${row}`);
	});

	if (!hasInteractiveTerminal) {
		throw new Error(
			'Interactive selection required but terminal is not interactive.',
		);
	}

	const rl = createInterface({
		input: process.stdin,
		output: process.stdout,
	});

	const selected = await new Promise((resolve) => {
		rl.question(`Select 1-${rows.length}: `, (input) => {
			rl.close();
			resolve(input.trim());
		});
	});

	const index = Number.parseInt(selected, 10);
	if (!Number.isInteger(index) || index < 1 || index > rows.length) {
		err(`Invalid selection: ${selected}`);
	}

	return index - 1;
};

const err = (message) => {
	console.error(message);
	process.exit(1);
};

const parseWorktrees = (raw) => {
	const entries = [];
	let current = null;

	for (const rawLine of raw.split('\n')) {
		const line = rawLine.replace(/\r$/, '');
		if (line.length === 0) {
			continue;
		}

		if (line.startsWith('worktree ')) {
			if (current) {
				entries.push(current);
			}
			current = {
				path: line.slice('worktree '.length),
				head: '',
				branch: null,
			};
			continue;
		}

		if (!current) {
			continue;
		}

		if (line.startsWith('HEAD ')) {
			current.head = line.slice('HEAD '.length);
			continue;
		}

		if (line.startsWith('branch ')) {
			current.branch = line
				.slice('branch '.length)
				.replace(/^refs\/heads\//, '');
		}
	}

	if (current) {
		entries.push(current);
	}

	return entries;
};

const getWorktrees = () => {
	const output = runCommand('git', ['worktree', 'list', '--porcelain'], {
		cwd: repoRoot,
	}).stdout;

	return parseWorktrees(output);
};

const isPortAvailableOnHost = async (host, port) => {
	return await new Promise((resolve) => {
		const server = createServer();
		server.once('error', () => {
			resolve(false);
		});
		server.listen(port, host, () => {
			server.close(() => {
				resolve(true);
			});
		});
	});
};

const derivePreferredPort = (prNumber) => {
	let candidate = BASE_PORT + (prNumber % 1000);
	if (RESERVED_PORTS.has(candidate)) {
		candidate += 1;
	}

	return candidate;
};

const choosePort = async (
	prNumber,
	{ host, probePortAvailable = isPortAvailableOnHost } = {},
) => {
	const candidate = derivePreferredPort(prNumber);

	for (let port = candidate; port <= 65535; port += 1) {
		if (RESERVED_PORTS.has(port)) {
			continue;
		}

		if (await probePortAvailable(host, port)) {
			if (port !== candidate) {
				console.log(
					`Preferred port ${String(candidate)} is unavailable on ${host}, ` +
						`using ${String(port)} for review session stability (cookie scope remains isolated).`,
				);
			}

			return port;
		}
	}

	err('No free port found for PR frontend launch.');
};

const getBranchPathByMap = (worktrees) => {
	const map = new Map();
	for (const worktree of worktrees) {
		if (worktree.branch) {
			map.set(worktree.branch, worktree.path);
		}
	}
	return map;
};

const hasLocalBranch = (branchName) => {
	const result = spawnSync(
		'git',
		['show-ref', '--heads', '--verify', `refs/heads/${branchName}`],
		{
			cwd: repoRoot,
			encoding: 'utf8',
			stdio: 'ignore',
		},
	);
	return result.status === 0;
};

const hasRemoteBranch = (branchName, remote = 'origin') => {
	const result = spawnSync(
		'git',
		['show-ref', '--verify', '--quiet', `refs/remotes/${remote}/${branchName}`],
		{
			cwd: repoRoot,
			encoding: 'utf8',
			stdio: 'ignore',
		},
	);
	return result.status === 0;
};

const getIssueBranchPattern = (number) =>
	new RegExp(
		ISSUE_TOKEN_PATTERN_SOURCE.replace('${number}', String(number)),
		'i',
	);

const resolveByPull = (pr, worktrees) => {
	const exact = worktrees.find(
		(worktree) => worktree.branch === pr.headRefName,
	);
	if (exact) {
		return exact;
	}

	return worktrees.find((worktree) => worktree.head === pr.headRefOid);
};

const runPrByNumber = (number) =>
	runGhJson([
		'pr',
		'view',
		String(number),
		'--json',
		'number,state,title,headRefName,headRefOid',
	]);

const runIssueByNumber = (number) =>
	runGhJson(['issue', 'view', String(number), '--json', 'title,number']);

const runPrsByHeadBranch = (branch) =>
	runGhJson([
		'pr',
		'list',
		'--state',
		'all',
		'--json',
		'number,state,headRefName',
		'--head',
		branch,
	]);

const resolvePrForIssueWorktree = async (worktree) => {
	if (!worktree.branch) {
		return null;
	}

	const candidates = await runPrsByHeadBranch(worktree.branch);
	if (!Array.isArray(candidates) || candidates.length === 0) {
		return null;
	}

	const openPr = candidates.find((candidate) => candidate.state === 'OPEN');
	const selected = openPr ?? candidates[0];

	if (selected.state === 'CLOSED' || selected.state === 'MERGED') {
		console.error(
			`Resolved branch ${worktree.branch} to ${selected.state.toLowerCase()} PR #${selected.number}.`,
		);
	}

	return selected;
};

const resolveByNumber = async (number, worktrees) => {
	const pr = runPrByNumber(number);
	if (pr) {
		if (pr.state && pr.state !== 'OPEN') {
			console.error(`Resolved PR #${pr.number} as ${pr.state.toLowerCase()}.`);
		}

		const resolved = resolveByPull(pr, worktrees);
		if (resolved) {
			return { kind: 'pr', source: pr, worktree: resolved };
		}

		const suggested = path.join(
			repoRoot,
			'.worktrees',
			`${FRONTEND_TOKEN_PREFIX}${number}`,
		);
		const quotedBranch = formatShellWord(pr.headRefName);
		const unquotedBranch = pr.headRefName;
		let pullCommand;
		if (hasLocalBranch(pr.headRefName)) {
			pullCommand = `git worktree add ${formatShellWord(suggested)} ${quotedBranch}`;
		} else if (hasRemoteBranch(pr.headRefName)) {
			pullCommand = `git fetch origin ${quotedBranch} && git worktree add ${formatShellWord(suggested)} -b ${quotedBranch} origin/${unquotedBranch}`;
		} else {
			pullCommand = `git worktree add ${formatShellWord(suggested)} --detach ${formatShellWord(pr.headRefOid)}`;
		}

		console.error(`Could not resolve PR #${number} by branch or head SHA.`);
		console.error('Run this to add it:');
		console.error(pullCommand);
		err(`Could not resolve PR #${number}.`);
	}

	const issue = runIssueByNumber(number);
	if (!issue) {
		err(`No PR or issue found for ${number}.`);
	}

	const pattern = getIssueBranchPattern(number);
	const matches = worktrees.filter((worktree) =>
		worktree.branch ? pattern.test(worktree.branch) : false,
	);
	if (matches.length === 0) {
		err(`No worktree branch matched issue pattern for #${number}.`);
	}
	if (matches.length > 1) {
		if (!hasInteractiveTerminal) {
			err(
				`Issue ${number} matched multiple branches, but terminal is not interactive.`,
			);
		}

		const rows = matches.map(
			(worktree) =>
				`${worktree.branch} | ${worktree.path} | head ${worktree.head}`,
		);
		const selected = await askChoice(
			`Multiple worktrees matched issue #${number}. Select one:`,
			rows,
		);
		return { kind: 'issue', worktree: matches[selected], source: issue };
	}

	return { kind: 'issue', worktree: matches[0], source: issue };
};

const resolveInteractivePicker = async (worktrees, byBranch) => {
	const prs = runGhJson([
		'pr',
		'list',
		'--state',
		'open',
		'--json',
		'number,title,headRefName',
	]);

	if (!Array.isArray(prs) || prs.length === 0) {
		err('No open PRs found for picker.');
	}

	const rows = prs.map((pr) => {
		const hasPath = byBranch.has(pr.headRefName);
		return {
			number: pr.number,
			title: pr.title,
			branch: pr.headRefName,
			path: byBranch.get(pr.headRefName) ?? 'none',
			origin: buildFrontendOrigin(pr.number),
			hasPath,
		};
	});

	rows.sort((left, right) => {
		if (left.hasPath === right.hasPath) {
			return left.number - right.number;
		}
		return left.hasPath ? -1 : 1;
	});

	const lines = rows.map(
		(row) =>
			`#${row.number} | ${row.branch} | ${row.path} | ${row.origin} | ${row.title}`,
	);
	const selected = await askChoice(
		'Choose PR to review (open PRs with worktrees first):',
		lines,
	);

	const row = rows[selected];
	return resolveByNumber(row.number, worktrees);
};

const resolveTarget = async (worktrees, byBranch) => {
	if (!requestedRef) {
		if (!hasInteractiveTerminal) {
			err('No PR/issue ref provided in a non-interactive terminal.');
		}

		return resolveInteractivePicker(worktrees, byBranch);
	}

	if (!/^\d+$/.test(requestedRef)) {
		err(`Expected a PR or issue number, got ${requestedRef}.`);
	}

	const number = Number.parseInt(requestedRef, 10);
	return resolveByNumber(number, worktrees);
};

const buildFrontendToken = (prNumber) => `${FRONTEND_TOKEN_PREFIX}${prNumber}`;

const buildFrontendHost = (frontendToken) => `${frontendToken}.localhost`;

const buildFrontendOrigin = (prNumber) =>
	`http://${buildFrontendHost(buildFrontendToken(prNumber))}:${derivePreferredPort(prNumber)}`;

const parseFrontendTokenFromPath = (worktreePath) => {
	const base = path.basename(worktreePath);
	const match = /^pr(\d+)$/i.exec(base);
	if (!match) {
		return null;
	}

	return `${FRONTEND_TOKEN_PREFIX}${match[1]}`;
};

const resolveFrontendToken = async (resolved, options = {}) => {
	if (resolved.kind === 'pr' && resolved.source?.number) {
		return buildFrontendToken(resolved.source.number);
	}

	if (resolved.kind === 'issue' && resolved.worktree) {
		const resolver = options.resolvePrByBranch ?? resolvePrForIssueWorktree;
		if (resolved.worktree.branch) {
			const issuePr = await resolver(resolved.worktree);
			if (issuePr?.number) {
				return buildFrontendToken(issuePr.number);
			}
		}

		return parseFrontendTokenFromPath(resolved.worktree.path);
	}

	return null;
};

const ensureApi = async () => {
	for (let attempt = 0; attempt < 6; attempt += 1) {
		try {
			const response = await fetch('http://127.0.0.1:5000/health', {
				signal: AbortSignal.timeout(1000),
			});

			if (response.ok) {
				return;
			}
		} catch {
			// Keep retrying while API comes up.
		}

		await new Promise((resolve) => {
			setTimeout(resolve, 1000);
		});
	}

	throw new Error(
		[
			'API on :5000 is not answering. Start it with:',
			'  just dev-db',
			'  just dev-api',
		].join('\n'),
	);
};

const generateEnv = (worktreePath, frontendToken, port) => {
	const frontendUrl = `http://${buildFrontendHost(frontendToken)}:${port}`;
	const allowedToken = process.env.PUBLIC_POSTHOG_PROJECT_TOKEN?.trim()
		? process.env.PUBLIC_POSTHOG_PROJECT_TOKEN.trim()
		: (process.env.POSTHOG_PROJECT_TOKEN?.trim() ?? '');
	const envValues = {
		FRONT_URL: frontendUrl,
		PUBLIC_API_BASE_URL: 'http://localhost:5000',
		SERVER_API_BASE_URL: 'http://localhost:5000',
		VITE_ASP_SERVER_URL: 'http://localhost:5000',
	};
	if (allowedToken.length > 0) {
		envValues.PUBLIC_POSTHOG_PROJECT_TOKEN = allowedToken;
	}

	const lines = [
		ENVIRONMENT_GENERATION_MARKER,
		...Object.entries(envValues).map(([key, value]) => `${key}=${value}`),
	];

	const target = path.join(worktreePath, FRONTEND_ENV_FILE);
	const temp = `${target}.${Date.now()}.tmp`;
	// writeFileSync + renameSync replaces the directory entry, so we do not follow hardlinks.
	writeFileSync(temp, `${lines.join('\n')}\n`, 'utf8');
	renameSync(temp, target);
};

const isGeneratedEnvOverlay = (worktreePath) => {
	const target = path.join(worktreePath, FRONTEND_ENV_FILE);
	if (!existsSync(target)) {
		return false;
	}

	const firstLine = readFileSync(target, 'utf8').split(/\r?\n/, 2)[0] ?? '';
	return firstLine === ENVIRONMENT_GENERATION_MARKER;
};

const buildViteEnv = () => {
	const env = {};
	for (const key of ALLOWLISTED_VITE_ENV_KEYS) {
		if (process.env[key] !== undefined) {
			env[key] = process.env[key];
		}
	}

	for (const [key, value] of Object.entries(process.env)) {
		if (key.startsWith('PUBLIC_') || key.startsWith('VITE_')) {
			env[key] = value;
		}
	}

	return env;
};

const ensureDependencies = (worktreePath) => {
	console.log('Checking pinned deps in worktree...');

	const assertPinnedPath = path.join(
		worktreePath,
		'apps',
		'front-2',
		'scripts',
		'assert-pinned.mjs',
	);
	if (existsSync(assertPinnedPath)) {
		runCommand('node', ['apps/front-2/scripts/assert-pinned.mjs'], {
			cwd: worktreePath,
			stdio: 'inherit',
		});
	} else {
		console.error(
			'Skipping assert-pinned check (missing target script): apps/front-2/scripts/assert-pinned.mjs',
		);
	}

	console.log('Installing front-2 deps (frozen, no scripts)...');
	runCommand('pnpm', ['install', '--frozen-lockfile', '--ignore-scripts'], {
		cwd: worktreePath,
		stdio: 'inherit',
	});

	const sharedTsPackage = path.join(
		worktreePath,
		'packages',
		'shared-ts',
		'package.json',
	);
	console.log('Running shared-ts postinstall...');
	if (existsSync(sharedTsPackage)) {
		runCommand('pnpm', ['--filter', '@org/shared-ts', 'run', 'postinstall'], {
			cwd: worktreePath,
			stdio: 'inherit',
		});
	} else {
		console.error(
			'Skipping shared-ts postinstall (missing packages/shared-ts/package.json)',
		);
	}
};

const parseTrackedChangesFromStatus = (output) => {
	return new Set(
		output
			.split('\n')
			.map((line) => line.slice(3).trim())
			.filter(Boolean),
	);
};

const trackedChanges = (worktreePath) => {
	const output = runCommand(
		'git',
		['-C', worktreePath, 'status', '--short', '--untracked-files=no'],
		{
			stdio: 'pipe',
		},
	).stdout;

	return parseTrackedChangesFromStatus(output);
};

const parseAddressForFrontend = async (
	frontendHost,
	{ dnsLookup = lookup } = {},
) => {
	const result = await dnsLookup(frontendHost, { all: false });
	if (
		!result ||
		typeof result.address !== 'string' ||
		result.address.length === 0
	) {
		err(`No address resolved for ${frontendHost}.`);
	}

	if (typeof result.family !== 'number') {
		err(`No address family resolved for ${frontendHost}.`);
	}

	return {
		address: result.address,
		family: result.family,
	};
};

const waitForFrontendReachable = async (url) => {
	for (let attempt = 0; attempt < 60; attempt += 1) {
		try {
			await fetch(url, {
				signal: AbortSignal.timeout(1000),
			});
			return;
		} catch {
			await new Promise((resolve) => {
				setTimeout(resolve, 250);
			});
		}
	}

	err(`Vite did not become reachable at ${url} before timeout.`);
};

const launchVite = async (
	worktreePath,
	bindHost,
	publicHost,
	port,
	bindCheckHost,
) => {
	const publicUrl = `http://${publicHost}:${port}`;
	const bindUrl = bindCheckHost ? `http://${bindCheckHost}:${port}` : publicUrl;
	const cwd = path.join(worktreePath, 'apps', 'front-2');
	const child = spawn(
		'pnpm',
		[
			'exec',
			'vite',
			'dev',
			'--host',
			bindHost,
			'--port',
			String(port),
			'--strictPort',
		],
		{
			cwd,
			stdio: 'inherit',
			env: buildViteEnv(),
		},
	);

	const shutdown = (signal) => {
		if (!child.killed) {
			child.kill(signal);
		}
	};
	process.on('SIGINT', () => shutdown('SIGINT'));
	process.on('SIGTERM', () => shutdown('SIGTERM'));

	await waitForFrontendReachable(bindUrl);

	const [code, signal] = await once(child, 'exit');
	if (signal) {
		console.log(`Vite exited on ${signal}.`);
		return { signal };
	}

	return { code };
};

const generateFrontendTokenForTarget = async (resolved) => {
	const token = await resolveFrontendToken(resolved);
	if (!token) {
		err(
			`Could not derive a PR token from ${String(resolved.worktree?.path ?? 'selected target')}.`,
		);
	}

	return token;
};

const generateFrontendUrl = (frontendToken, port) =>
	`http://${buildFrontendHost(frontendToken)}:${port}`;

const main = async () => {
	const worktrees = getWorktrees();
	const byBranch = getBranchPathByMap(worktrees);
	const resolved = await resolveTarget(worktrees, byBranch);

	const frontendToken = await generateFrontendTokenForTarget(resolved);
	const frontendHost = buildFrontendHost(frontendToken);
	const preferredPort = derivePreferredPort(
		Number.parseInt(frontendToken.slice(FRONTEND_TOKEN_PREFIX.length), 10),
	);
	const { address: bindAddress, family: bindFamily } =
		await parseAddressForFrontend(frontendHost);
	const bindDisplay = `${bindAddress} (${
		bindFamily === 6 ? 'IPv6' : `IPv${bindFamily}`
	})`;
	const port = await choosePort(
		Number.parseInt(frontendToken.slice(FRONTEND_TOKEN_PREFIX.length), 10),
		{ host: bindAddress },
	);
	const worktree = resolved.worktree;
	const frontendEnv = path.join(worktree.path, FRONTEND_ENV_FILE);

	if (existsSync(frontendEnv) && !isGeneratedEnvOverlay(worktree.path)) {
		err(
			`Refusing to use existing ${frontendEnv} because it is not generated by review-front-2.`,
		);
	}

	if (existsSync(path.join(worktree.path, '.env.development'))) {
		console.error(
			`Warning: found ${path.join(worktree.path, '.env.development')} and will prefer ${FRONTEND_ENV_FILE}.`,
		);
	}

	await ensureApi();
	ensureDependencies(worktree.path);

	generateEnv(worktree.path, frontendToken, port);

	const publicUrl = generateFrontendUrl(frontendToken, port);

	console.log('\n');
	console.log('Launching PR frontend review server');
	console.log(`worktree: ${worktree.path}`);
	console.log(`open:     ${publicUrl}`);
	console.log(`bind host: ${bindDisplay}`);
	console.log('Overlay:  .env.development.local (persisted on disk).');
	console.log('');
	console.log(
		'Tip: keep a second terminal for API/debug while both sessions run.',
	);
	console.log('');

	if (port !== preferredPort) {
		console.log(
			`Port ${String(port)} was selected because ${String(preferredPort)} is unavailable; this preserves cookie safety while keeping the PR session accessible.`,
		);
	}

	const beforeDirty = trackedChanges(worktree.path);
	const { code, signal } = await launchVite(
		worktree.path,
		bindAddress,
		frontendHost,
		port,
		bindFamily === 6 ? `[${bindAddress}]` : bindAddress,
	);
	const afterDirty = trackedChanges(worktree.path);
	const newlyDirty = [...afterDirty].filter((entry) => !beforeDirty.has(entry));
	if (newlyDirty.length > 0) {
		console.error('Warning: tracked files became dirty while the session ran.');
		for (const entry of newlyDirty) {
			console.error(`  ${entry}`);
		}
	}

	if (signal) {
		process.exit(0);
	}

	if (code !== 0) {
		err(`Vite exited with code ${String(code)}.`);
	}
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	await main();
}

export {
	FRONTEND_ENV_KEYS,
	parseWorktrees,
	choosePort,
	getIssueBranchPattern,
	generateEnv,
	parseTrackedChangesFromStatus,
	parseAddressForFrontend,
	parseFrontendTokenFromPath,
	buildFrontendToken,
	buildFrontendHost,
	buildFrontendOrigin,
	generateFrontendUrl,
	getWorktrees,
	resolveTarget,
	getBranchPathByMap,
	resolveFrontendToken,
	generateFrontendTokenForTarget,
};
