/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createGetUserTenantsResultFromDiscriminatorValue, type AppProblemDetails, type GetUserTenantsResult } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth/user-tenants
 */
export interface UserTenantsRequestBuilder extends BaseRequestBuilder<UserTenantsRequestBuilder> {
    /**
     * Get User Tenants
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetUserTenantsResult>}
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GetUserTenantsResult | undefined>;
    /**
     * Get User Tenants
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UserTenantsRequestBuilderUriTemplate = "{+baseurl}/auth/user-tenants";
/**
 * Metadata for all the requests in the request builder.
 */
export const UserTenantsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: UserTenantsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetUserTenantsResultFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
