import React from 'react';

import '@aktiveo/ui-react/styles/fonts.css';
import { AuthProvider } from '@aktiveo/ui-react/contexts/AuthProvider';

import QueryNextProvider from '../providers/QueryNextProvider';
import LayoutFront from '../components/layout/LayoutFront';
import ThemeProviderNext from '../providers/ThemeProviderNext';

// --------------------------------------------------------------------------------------//
//                                   initialize parse                                    //
// --------------------------------------------------------------------------------------/
const isServer = typeof window === 'undefined';

// ---- code copied from parse-react/ssr -------------------------------------------------
if ((process as any).browser) {
	// eslint-disable-next-line global-require
	global.Parse = require('parse');
} else {
	// eslint-disable-next-line global-require
	global.Parse = require('parse/node');
}

Parse.initialize('aktiveo');

if (!isServer) {
	Parse.enableLocalDatastore();
}
// ---- end of code copied from parse-react/ssr -------------------------------------------------

Parse.serverURL = 'http://localhost:6180/parse';

// --------------------------------------------------------------------------------------//
//                               Nextjs metadata for SEO                                //
// --------------------------------------------------------------------------------------//
// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en">
			<body>
				<AuthProvider>
					<QueryNextProvider>
						<ThemeProviderNext>
							<LayoutFront>{children}</LayoutFront>

							{/* {children} */}
						</ThemeProviderNext>
					</QueryNextProvider>
				</AuthProvider>
			</body>
		</html>
	);
};

export default RootLayout;
