/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createInvitationAcceptedFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, serializeAcceptInvitationBody, serializeInvitationAccepted, type AcceptInvitationBody, type AppProblemDetails, type InvitationAccepted, type ValidationProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /invitations/{token}/accept
 */
export interface AcceptRequestBuilder extends BaseRequestBuilder<AcceptRequestBuilder> {
    /**
     * Accept invitation and create account + session
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InvitationAccepted>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 404 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     post(body: AcceptInvitationBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<InvitationAccepted | undefined>;
    /**
     * Accept invitation and create account + session
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AcceptInvitationBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AcceptRequestBuilderUriTemplate = "{+baseurl}/invitations/{token}/accept";
/**
 * Metadata for all the requests in the request builder.
 */
export const AcceptRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AcceptRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createInvitationAcceptedFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAcceptInvitationBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
