/**
 * Wires Git hooks into every worktree of this clone (issue #1852).
 *
 * ## Why this exists
 *
 * `git config core.hooksPath` used to point at `.husky/_` — a directory
 * generated by `husky install` that is NOT tracked. The value is a RELATIVE
 * path, so git resolves it inside the working directory of each worktree: a
 * freshly created worktree had no `.husky/_`, git found no hooks, and commits
 * sailed through unformatted (three PRs went red on it, four checks each).
 *
 * ## What this script does
 *
 * 1. Points `core.hooksPath` at the VERSIONED `.husky` directory (which
 *    contains the tracked `pre-commit` and `pre-push` hooks). The path stays
 *    relative on purpose: git resolves it against each worktree's own root,
 *    and the tracked hook files exist in every checkout — so a brand new
 *    worktree, with zero manual steps, runs the exact same pre-commit
 *    pipeline (lint-staged → oxfmt) as the main clone. The setting lives in
 *    the clone's shared config, so it covers every existing worktree of the
 *    clone at once.
 * 2. VERIFIES the hooks are actually runnable: the hook files must exist in
 *    the checkout and be executable. Any problem fails LOUD with the cause
 *    and the repair — a worktree that believes it is protected while it is
 *    not is worse than one that knows it is not (issue #1852 requirement 1).
 *
 * The root `prepare` script runs this on every `pnpm install`. No developer
 * has to remember anything: a new clone gets hooks on its first install, and
 * a new worktree inherits them from the shared config immediately.
 *
 * This script deliberately uses only Node builtins and git: it must run from
 * `prepare` before any workspace dependency exists.
 */
import { execFileSync } from 'node:child_process';
import { accessSync, constants, existsSync } from 'node:fs';
import { join } from 'node:path';

const HOOKS_DIR = '.husky';
const HOOKS = ['pre-commit', 'pre-push'] as const;

const fail = (message: string): never => {
	console.error(`\n[install-git-hooks] ${message}`);
	console.error(
		'[install-git-hooks] Git hooks are NOT ACTIVE. Fix the cause above, then re-run `pnpm install` (or `pnpm run prepare`).',
	);
	process.exit(1);
};

const runGit = (args: string[]): string =>
	execFileSync('git', args, {
		encoding: 'utf-8',
		stdio: ['ignore', 'pipe', 'pipe'],
	}).trim();

let topLevel: string;
try {
	topLevel = runGit(['rev-parse', '--show-toplevel']);
} catch (err) {
	fail(
		`not inside a git work tree (git rev-parse --show-toplevel failed: ${(err as Error).message}).`,
	);
}

// Point core.hooksPath at the versioned hooks directory. The value is
// intentionally RELATIVE: git resolves it inside each worktree's root, and
// the tracked .husky/pre-commit + .husky/pre-push exist in every checkout.
// The setting is stored in the clone's shared config, so one install wires
// every existing and future worktree of the clone.
try {
	runGit(['config', 'core.hooksPath', HOOKS_DIR]);
} catch (err) {
	fail(
		`could not set core.hooksPath to "${HOOKS_DIR}" (${(err as Error).message}). ` +
			'Is the git config writable?',
	);
}

for (const hook of HOOKS) {
	const hookPath = join(topLevel, HOOKS_DIR, hook);

	if (!existsSync(hookPath)) {
		fail(
			`missing tracked hook file "${HOOKS_DIR}/${hook}" (looked at ${hookPath}). ` +
				'The checkout is incomplete.',
		);
	}

	try {
		accessSync(hookPath, constants.X_OK);
	} catch {
		fail(
			`hook file "${HOOKS_DIR}/${hook}" exists but is not executable. ` +
				`Fix with: chmod +x "${hookPath}"`,
		);
	}
}

const resolved = runGit(['config', '--get', 'core.hooksPath']);
console.log(
	`[install-git-hooks] OK: core.hooksPath=${resolved} (versioned hooks: ${HOOKS.join(', ')}) — active in every worktree of this clone.`,
);
