/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PublicationsRequestBuilderRequestsMetadata, type PublicationsRequestBuilder } from './publications/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /publishing
 */
export interface PublishingRequestBuilder extends BaseRequestBuilder<PublishingRequestBuilder> {
    /**
     * The publications property
     */
    get publications(): PublicationsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PublishingRequestBuilderUriTemplate = "{+baseurl}/publishing";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PublishingRequestBuilderNavigationMetadata: Record<Exclude<keyof PublishingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    publications: {
        requestsMetadata: PublicationsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
