/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createBulkStaffUserActionResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, serializeBulkStaffUserActionResult, serializeBulkSuspendStaffUsersBody, type AppProblemDetails, type BulkStaffUserActionResult, type BulkSuspendStaffUsersBody, type ValidationProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/users/bulk-suspend
 */
export interface BulkSuspendRequestBuilder extends BaseRequestBuilder<BulkSuspendRequestBuilder> {
    /**
     * Bulk suspend staff users
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BulkStaffUserActionResult>}
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     post(body: BulkSuspendStaffUsersBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BulkStaffUserActionResult | undefined>;
    /**
     * Bulk suspend staff users
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: BulkSuspendStaffUsersBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BulkSuspendRequestBuilderUriTemplate = "{+baseurl}/staff/users/bulk-suspend";
/**
 * Metadata for all the requests in the request builder.
 */
export const BulkSuspendRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: BulkSuspendRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createBulkStaffUserActionResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeBulkSuspendStaffUsersBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
