/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
	createAppProblemDetailsFromDiscriminatorValue,
	type AppProblemDetails,
} from '../models/index.js';
// @ts-ignore
import {
	type BaseRequestBuilder,
	type Parsable,
	type ParsableFactory,
	type RequestConfiguration,
	type RequestInformation,
	type RequestsMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /test
 */
export interface TestRequestBuilder
	extends BaseRequestBuilder<TestRequestBuilder> {
	/**
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {Promise<string>}
	 * @throws {AppProblemDetails} error when the service returns a 400 status code
	 * @throws {AppProblemDetails} error when the service returns a 401 status code
	 * @throws {AppProblemDetails} error when the service returns a 403 status code
	 * @throws {AppProblemDetails} error when the service returns a 500 status code
	 */
	get(
		requestConfiguration?: RequestConfiguration<object> | undefined,
	): Promise<string | undefined>;
	/**
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {RequestInformation}
	 */
	toGetRequestInformation(
		requestConfiguration?: RequestConfiguration<object> | undefined,
	): RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TestRequestBuilderUriTemplate = '{+baseurl}/test';
/**
 * Metadata for all the requests in the request builder.
 */
export const TestRequestBuilderRequestsMetadata: RequestsMetadata = {
	get: {
		uriTemplate: TestRequestBuilderUriTemplate,
		responseBodyContentType: 'text/plain;q=0.9',
		errorMappings: {
			400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
		},
		adapterMethodName: 'sendPrimitive',
		responseBodyFactory: 'string',
	},
};
/* tslint:enable */
/* eslint-enable */
