/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createFindSystemNoticesResponseFromDiscriminatorValue, createSystemNoticeCreatedFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, serializeCreateSystemNoticeBody, serializeSystemNoticeCreated, type AppProblemDetails, type CreateSystemNoticeBody, type FindSystemNoticesResponse, type SystemNoticeCreated, type ValidationProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type WithNoticeItemRequestBuilder, WithNoticeItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/notices
 */
export interface NoticesRequestBuilder extends BaseRequestBuilder<NoticesRequestBuilder> {
    /**
     * Gets an item from the MainApi.Client.staff.notices.item collection
     * @param noticeId Unique identifier of the item
     * @returns {WithNoticeItemRequestBuilder}
     */
     byNoticeId(noticeId: Guid) : WithNoticeItemRequestBuilder;
    /**
     * List all system notices with pagination
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FindSystemNoticesResponse>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<NoticesRequestBuilderGetQueryParameters> | undefined) : Promise<FindSystemNoticesResponse | undefined>;
    /**
     * Create a new system notice
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SystemNoticeCreated>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {AppProblemDetails} error when the service returns a 401 status code
     * @throws {AppProblemDetails} error when the service returns a 403 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     post(body: CreateSystemNoticeBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SystemNoticeCreated | undefined>;
    /**
     * List all system notices with pagination
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<NoticesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create a new system notice
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateSystemNoticeBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * List all system notices with pagination
 */
export interface NoticesRequestBuilderGetQueryParameters {
    cursor?: string;
    limit?: string;
    sortId?: string;
    sortOrder?: string;
}
/**
 * Uri template for the request builder.
 */
export const NoticesRequestBuilderUriTemplate = "{+baseurl}/staff/notices{?Cursor*,Limit*,SortId*,SortOrder*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const NoticesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "cursor": "Cursor",
    "limit": "Limit",
    "sortId": "SortId",
    "sortOrder": "SortOrder",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const NoticesRequestBuilderNavigationMetadata: Record<Exclude<keyof NoticesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byNoticeId: {
        requestsMetadata: WithNoticeItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["noticeId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const NoticesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: NoticesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFindSystemNoticesResponseFromDiscriminatorValue,
        queryParametersMapper: NoticesRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: NoticesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSystemNoticeCreatedFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateSystemNoticeBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
