import { nanoid } from 'nanoid';
import { TENANT_PROFILES_PERMISSIONS_ENUM } from '@/shared/lib/constants';

export type TenantProfile = {
	objectId: string;
	name: string;
	permissions: Record<string, boolean>;
};

export const _tenantProfiles: TenantProfile[] = [
	{
		objectId: nanoid(),
		name: 'R&D',
		permissions: {
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_BILLING]: true,
			// [TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_DASHBOARD]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_SETTINGS]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_USERS]: true,
		},
	},
	{
		objectId: nanoid(),
		name: 'Sales',
		permissions: {
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_DASHBOARD]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_BILLING]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_SETTINGS]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_USERS]: true,
		},
	},
	{
		objectId: nanoid(),
		name: 'Marketing',
		permissions: {
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_DASHBOARD]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_BILLING]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_SETTINGS]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_USERS]: true,
		},
	},
	{
		objectId: nanoid(),
		name: 'IT',
		permissions: {
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_BILLING]: true,
			// [TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_DASHBOARD]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_SETTINGS]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_USERS]: true,
		},
	},
	{
		objectId: nanoid(),
		name: 'Tech Support',
		permissions: {
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_DASHBOARD]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_BILLING]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_SETTINGS]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_USERS]: true,
		},
	},
	{
		objectId: nanoid(),
		name: 'Design',
		permissions: {
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_DASHBOARD]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_BILLING]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_SETTINGS]: true,
			[TENANT_PROFILES_PERMISSIONS_ENUM.CAN_ACCESS_USERS]: true,
		},
	},
];
