/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAppProblemDetailsFromDiscriminatorValue, createCheckResetPasswordTokenResultFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, type AppProblemDetails, type CheckResetPasswordTokenResult, type ValidationProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth/check-reset-password-token
 */
export interface CheckResetPasswordTokenRequestBuilder extends BaseRequestBuilder<CheckResetPasswordTokenRequestBuilder> {
    /**
     * Check Reset Password Token
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CheckResetPasswordTokenResult>}
     * @throws {AppProblemDetails} error when the service returns a 400 status code
     * @throws {ValidationProblemDetails} error when the service returns a 422 status code
     * @throws {AppProblemDetails} error when the service returns a 429 status code
     * @throws {AppProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<CheckResetPasswordTokenRequestBuilderGetQueryParameters> | undefined) : Promise<CheckResetPasswordTokenResult | undefined>;
    /**
     * Check Reset Password Token
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CheckResetPasswordTokenRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Check Reset Password Token
 */
export interface CheckResetPasswordTokenRequestBuilderGetQueryParameters {
    id?: string;
    token?: string;
}
/**
 * Uri template for the request builder.
 */
export const CheckResetPasswordTokenRequestBuilderUriTemplate = "{+baseurl}/auth/check-reset-password-token?id={id}&token={token}";
/**
 * Metadata for all the requests in the request builder.
 */
export const CheckResetPasswordTokenRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CheckResetPasswordTokenRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCheckResetPasswordTokenResultFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
