/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
	createAppProblemDetailsFromDiscriminatorValue,
	createGetAuditLogActionsResponseFromDiscriminatorValue,
	type AppProblemDetails,
	type GetAuditLogActionsResponse,
} from '../../../models/index.js';
// @ts-ignore
import {
	type BaseRequestBuilder,
	type Parsable,
	type ParsableFactory,
	type RequestConfiguration,
	type RequestInformation,
	type RequestsMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /staff/audit-logs/actions
 */
export interface ActionsRequestBuilder
	extends BaseRequestBuilder<ActionsRequestBuilder> {
	/**
	 * Get all available audit log action keys
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {Promise<GetAuditLogActionsResponse>}
	 * @throws {AppProblemDetails} error when the service returns a 401 status code
	 * @throws {AppProblemDetails} error when the service returns a 403 status code
	 * @throws {AppProblemDetails} error when the service returns a 500 status code
	 */
	get(
		requestConfiguration?: RequestConfiguration<object> | undefined,
	): Promise<GetAuditLogActionsResponse | undefined>;
	/**
	 * Get all available audit log action keys
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {RequestInformation}
	 */
	toGetRequestInformation(
		requestConfiguration?: RequestConfiguration<object> | undefined,
	): RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ActionsRequestBuilderUriTemplate =
	'{+baseurl}/staff/audit-logs/actions';
/**
 * Metadata for all the requests in the request builder.
 */
export const ActionsRequestBuilderRequestsMetadata: RequestsMetadata = {
	get: {
		uriTemplate: ActionsRequestBuilderUriTemplate,
		responseBodyContentType: 'application/json',
		errorMappings: {
			401: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			403: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
			500: createAppProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
		},
		adapterMethodName: 'send',
		responseBodyFactory: createGetAuditLogActionsResponseFromDiscriminatorValue,
	},
};
/* tslint:enable */
/* eslint-enable */
